---
title: "A table of gravel styles"
editor: source
---

::: {.callout-note}
1. The classification was computed using a robust [k-means method](https://en.wikipedia.org/wiki/K-means_clustering){target="_blank"}.
2. The classification is based on a frame size that fits a 175 cm high rider (generally frame size M or 54), according to manufacturer's charts.
:::

```{r setup-gravel-style, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      knitr.kable.NA = '')
source_path <- here::here("bike_geometry_project.R")
source(source_path)

library(DT)
library(reactable)

```

```{r gravel-style-table, echo=FALSE, eval=FALSE}
knitr::opts_chunk$set(knitr.kable.NA = '')

cluster_labels <- levels(geobike$kmeans_style)
style_class_table <- geobike[my_fit == TRUE, .SD, .SDcols = c("model", "kmeans_style")]
style_table <- dcast(setDT(style_class_table), rowid(kmeans_style) ~ kmeans_style, value.var = "model")[, .SD, .SDcols = cluster_labels] %>%
  clean_names() %>%
  setnames(new = c("Racy", "Relaxed", "Rowdy"))
style_table[is.na(style_table)] <- " "

# style_table %>%
#   kable(caption = "Classification of bikes is based on a frame size that fits a 175 cm (generally Size M/54) rider, according to manufacturer's charts.") %>%
#   kable_styling(full_width = FALSE)


bscols( widths = c(3, 9), filters, p1)

```

```{r, echo=FALSE, eval=FALSE}
keep_cols <- c("model", "kmeans_style", "material", "fork_class", "udh", "dropout", "axle_spacing", "handlebar",
               "tire_width_max_700c", "tire_width_max_650b")
n_col <- length(keep_cols)
style_table <- geobike[my_fit == TRUE, .SD, .SDcols = keep_cols]
style_wide <- dcast(setDT(style_table), rowid(kmeans_style) + material ~ kmeans_style, value.var = "model")
style_wide[, id := paste("row", .I)]
shared_data <- SharedData$new(style_wide, group = "style", key = "id")

# 4. Create the filters
filter_racy <- filter_select("racy_filter", "Racy", shared_data, ~racy)
filter_relaxed <- filter_select("relaxed_filter", "Relaxed", shared_data, ~relaxed)
filter_rowdy <- filter_select("rowdy_filter", "Rowdy", shared_data, ~rowdy)

# 5. Create the table
# Use the filtered shared_data to display the results
style_dt <- datatable(shared_data, filter = "none", rownames = FALSE)

# 6. Arrange the filters and table
# The combined HTML output can be saved to an HTML file or displayed in RStudio
bscols(
  widths = c(2, 2, 2, 6),
  list(filter_racy, filter_relaxed, filter_rowdy),
  style_dt
)
```

```{r working, echo=FALSE}
keep_cols <- c("model", "kmeans_style", "material", "fork_class", "udh", "dropout", "axle_spacing", "handlebar",
               "tire_width_max_700c", "tire_width_max_650b")
style_table <- geobike[my_fit == TRUE, .SD, .SDcols = keep_cols]
setnames(style_table, old = "kmeans_style", new = "style")
style_table[, id := .I]
# Put the data into a SharedData object for crosstalk
#shared <- SharedData$new(dt)
style_table_shared <- SharedData$new(style_table, key = ~id, group = "style_table")

racy <- style_table[style == "racy"]
setnames(racy, old = "model", new = "Racy")
relaxed <- style_table[style == "relaxed"]
setnames(relaxed, old = "model", new = "Relaxed")
rowdy <- style_table[style == "rowdy"]
setnames(rowdy, old = "model", new = "Rowdy")
# 2) Three pre-filtered SharedData objects (same group/key)
racy_shared    <- SharedData$new(racy,    key = ~id, group = "style_table")
relaxed_shard <- SharedData$new(relaxed, key = ~id, group = "style_table")
rowdy_shared   <- SharedData$new(rowdy,   key = ~id, group = "style_table")

ncm1 <- ncol(style_table) - 1
racy_col <- datatable(racy_shared,
                 rownames = FALSE,
                 options = list(
      columnDefs = list(list(targets = 1:ncm1, visible = FALSE)),
      pageLength = 100))
relaxed_col <- datatable(relaxed_shard,
                 rownames = FALSE,
                 options = list(
      columnDefs = list(list(targets = 1:ncm1, visible = FALSE)),
      pageLength = 100))
rowdy_col <- datatable(rowdy_shared,
                 rownames = FALSE,
                 options = list(
      columnDefs = list(list(targets = 1:ncm1, visible = FALSE)),
      pageLength = 100))

# filters
filters <- list(
  filter_checkbox("material", "Frame material", style_table_shared, ~material, inline = TRUE),
  filter_checkbox("fork", "Suspension correction (mm)", style_table_shared, ~fork_class, inline = TRUE),
  filter_checkbox("udh", "UDH", style_table_shared, ~udh, inline = TRUE),
  filter_checkbox("sliding", "Sliding dropout (mm)", style_table_shared, ~dropout, inline = TRUE),
  filter_checkbox("axle", "Axle spacing", style_table_shared, ~axle_spacing, inline = TRUE),
  filter_checkbox("handlebar", "Handlebar", style_table_shared, ~handlebar, inline = TRUE),
  filter_slider("tire_700", "Max 700c tire width (mm)", style_table_shared, ~tire_width_max_700c, step = 1),
  filter_slider("tire_650", "Max 650b tire width (in)", style_table_shared, ~tire_width_max_650b, step = 0.05)
  )

# Layout: filters on the left, three linked tables on the right
bscols(
  widths = c(3, 9),
  filters,
  bscols(
    widths = c(4, 4, 4),
    racy_col,
    relaxed_col,
    rowdy_col
  )
)
```

```{r, echo=FALSE, eval=FALSE}
filters <- list(
  filter_checkbox("material", "Frame material", style_table_shared, ~material, inline = TRUE),
  filter_checkbox("fork", "Suspension correction (mm)", style_table_shared, ~fork_class, inline = TRUE),
  filter_checkbox("udh", "UDH", style_table_shared, ~udh, inline = TRUE),
  filter_checkbox("sliding", "Sliding dropout (mm)", style_table_shared, ~dropout, inline = TRUE),
  filter_checkbox("axle", "Axle spacing", style_table_shared, ~axle_spacing, inline = TRUE),
  filter_checkbox("handlebar", "Handlebar", style_table_shared, ~handlebar, inline = TRUE),
  filter_slider("tire_700", "Max 700c tire width (mm)", style_table_shared, ~tire_width_max_700c, step = 1),
  filter_slider("tire_650", "Max 650b tire width (in)", style_table_shared, ~tire_width_max_650b, step = 0.05)
  )


style_wide <- dcast(setDT(style_table), rowid(kmeans_style) + material ~ kmeans_style, value.var = "model")
style_wide[, id := paste("row", .I)]
style_data <- SharedData$new(style_wide, group = "style", key = "id")

racy_col <- datatable(style_table,
                 rownames = FALSE,
                 options = list(
      columnDefs = list(list(targets = 1:ncm1, visible = FALSE))))
relaxed_col <- datatable(style_table,
                 rownames = FALSE,
                 options = list(
      columnDefs = list(list(targets = 1:ncm1, visible = FALSE))))
rowdy_col <- datatable(style_table,
                 rownames = FALSE,
                 options = list(
      columnDefs = list(list(targets = 1:ncm1, visible = FALSE))))
bscols(widths = c(3, 3, 3, 3), filters, racy_col, relaxed_col, rowdy_col)


```

