---
title: "Is a gravel bike a 1990s mountain bike?"
---

::: {.callout-note}
Classification of gravel bikes is based on a frame size that fits a 176 cm (5' 9.3") cm high rider, according to manufacturer's charts.
:::

```{r is-gravel-90s-mtb-setup, echo=FALSE, warning=FALSE, message=FALSE}
source_path <- here::here("bike_geometry_project.R")
source(source_path)

```

```{r is-gravel-90s-mtb-import, echo=FALSE, warning=FALSE, message=FALSE }
bikes_cols <- c("model", "year", "frame_size", "reach", "stack", "rear_center", "front_center", "head_tube_angle", "seat_tube_angle", "bottom_bracket_drop", "trail", "front_wheelbase", "stack_reach", "sta_hta", "restyle", "model_size")
bikes <- my_fit[, .SD, .SDcols = bikes_cols]
opacity <- rep(0.5, nrow(bikes))

# mountain
mtb90s <- import_bikes(style = "1990s mountain")
mtb90s[, restyle := "Mountain: 1990s"]
bikes <- rbind(bikes,
               mtb90s[my_fit == TRUE, .SD, .SDcols = bikes_cols])
opacity <- c(opacity, rep(1.0, nrow(mtb90s[my_fit == TRUE,])))

```


```{r is-gravel-90s-mtb-plot, echo=FALSE, warning=FALSE, message=FALSE, out.width = "100%", out.height = "100%"}
annotate_model_i <- bikes[restyle == "Mountain: 1990s", model]
p1 <- scatter_fig(data = bikes,
                  x_col = "reach",
                  y_col = "stack",
                  g_col = "restyle",
                  x_label = "Reach (mm)", y_label = "Stack (mm)",
                  dot_opacity = opacity,
                  dot_palette = c(pal_okabe_ito_7[1:3], pal_okabe_ito_7[7]),
                  annotate_model = annotate_model_i)
p2 <- scatter_fig(data = bikes,
                  x_col = "rear_center", y_col = "front_center",
                  g_col = "restyle",
                  x_label = "Rear Center (mm)", y_label = "Front Center (mm)",
                  x_info = "RC", y_info = "FC",
                  dot_opacity = opacity,
                  dot_palette = c(pal_okabe_ito_7[1:3], pal_okabe_ito_7[7]),
                  annotate_model = annotate_model_i)
p3 <- scatter_fig(data = bikes,
                  x_col = "head_tube_angle", y_col = "seat_tube_angle",
                  g_col = "restyle",
                  x_label = "Head Tube Angle (°)", y_label = "Seat Tube Angle (°)",
                  x_info = "HTA", y_info = "STA", digits = 1,
                  dot_opacity = opacity,
                  dot_palette = c(pal_okabe_ito_7[1:3], pal_okabe_ito_7[7]),
                  annotate_model = annotate_model_i)
p4 <- scatter_fig(data = bikes,
                  x_col = "head_tube_angle", y_col = "trail",
                  g_col = "restyle",
                  x_label = "Head Tube Angle (°)", y_label = "Trail (mm)",
                  x_info = "HTA", y_info = "Trail", digits = 1,
                  dot_opacity = opacity,
                  dot_palette = c(pal_okabe_ito_7[1:3], pal_okabe_ito_7[7]),
                  annotate_model = annotate_model_i,
                  same_xy_scale = FALSE)
p5 <- scatter_fig(data = bikes,
                  x_col = "front_wheelbase", y_col = "stack_reach",
                  g_col = "restyle",
                  x_label = "Front Center/Wheelbase", y_label = "Stack/Reach",
                  x_info = "FC/WB", y_info = "Stack/Reach", digits = 2,
                  dot_opacity = opacity,
                  dot_palette = c(pal_okabe_ito_7[1:3], pal_okabe_ito_7[7]),
                  annotate_model = annotate_model_i,
                  same_xy_scale = FALSE)
p6 <- scatter_fig(data = bikes,
                  x_col = "front_wheelbase", y_col = "sta_hta",
                  g_col = "restyle",
                  x_label = "Front Center/Wheelbase", y_label = "STA/HTA",
                  x_info = "FC/WB", y_info = "STA/HTA", digits = 2,
                  dot_opacity = opacity,
                  dot_palette = c(pal_okabe_ito_7[1:3], pal_okabe_ito_7[7]),
                  annotate_model = annotate_model_i,
                  same_xy_scale = FALSE)

p1
p2
p3
p4
p5
p6


```
