---
title: "Bike Geometry Project"
author: "Jeffrey Walker"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      knitr.kable.NA = '')
# wrangling packages
library(here) # here makes a project transportable
library(janitor) # clean_names
library(readxl) # read excel, duh!
library(data.table) # magical data frames
library(magrittr) # pipes
library(stringr) # string functions
library(forcats) # factor functions

# analysis packages
library(emmeans) # the workhorse for inference
library(nlme) # gls and some lmm
library(lme4) # linear mixed models
library(lmerTest) # linear mixed model inference
library(afex) # ANOVA linear models
library(glmmTMB) # generalized linear models
library(MASS) # negative binomial and some other functions
library(car) # model checking and ANOVA
library(DHARMa) # model checking
library(mvtnorm)

# graphing packages
library(ggsci) # color palettes
library(ggpubr) # publication quality plots
library(ggforce) # better jitter
library(cowplot) # combine plots
library(knitr) # kable tables
library(kableExtra) # kable_styling tables
library(ggdendro) # dendrogram
library(dendextend) # better dendrogram
library(ggiraph)
library(GGally)

# plotly
library(plotly)
library(flexdashboard)
library(crosstalk)

# ggplot_the_model.R packages not loaded above
library(insight)
library(lazyWeave)

# use here from the here package
here <- here::here
# use clean_names from the janitor package
clean_names <- janitor::clean_names
# use transpose from data.table
transpose <- data.table::transpose

# load functions used by this text written by me
# ggplot_the_model.R needs to be in the folder "R"
# if you didn't download this and add to your R folder in your
# project, then this line will cause an error
#source_path <- here("R", "ggplot_the_model.R")
#source(source_path)

data_folder <- "data"
image_folder <- "images"
output_folder <- "output"
```

```{r pal-okabe-ito, echo=FALSE}
pal_okabe_ito <- c(
  "#E69F00",
  "#56B4E9",
  "#009E73",
  "#F0E442",
  "#0072B2",
  "#D55E00",
  "#CC79A7"
)
pal_okabe_ito_blue <- pal_okabe_ito[c(5,6,1,2,3,7,4)] 
pal_okabe_ito_red <- pal_okabe_ito[c(6,5,3,1,2,7,4)] 
pal_okabe_ito_2 <- pal_okabe_ito[c(5,6)]
pal_okabe_ito_3 <- pal_okabe_ito[c(5,6,7)]
pal_okabe_ito_3_light <- pal_okabe_ito[c(1,2,7)]
pal_okabe_ito_4 <- pal_okabe_ito[c(5,6,7,2)]
```

```{r deg_2_rad, echo=FALSE}
deg_2_rad <- function(x){
  rad <- x*pi/180
  return(rad)
}
  
```

```{r ggdendro-extensions, echo=FALSE}
# https://atrebas.github.io/post/2019-06-08-lightweight-dendrograms/
dendro_data_k <- function(hc, k) {
  hcdata    <-  ggdendro::dendro_data(hc, type = "rectangle")
  seg       <-  hcdata$segments
  labclust  <-  cutree(hc, k)[hc$order]
  segclust  <-  rep(0L, nrow(seg))
  heights   <-  sort(hc$height, decreasing = TRUE)
  height    <-  mean(c(heights[k], heights[k - 1L]), na.rm = TRUE)
  
  for (i in 1:k) {
    xi      <-  hcdata$labels$x[labclust == i]
    idx1    <-  seg$x    >= min(xi) & seg$x    <= max(xi)
    idx2    <-  seg$xend >= min(xi) & seg$xend <= max(xi)
    idx3    <-  seg$yend < height
    idx     <-  idx1 & idx2 & idx3
    segclust[idx] <- i
  }
  
  idx                    <-  which(segclust == 0L)
  segclust[idx]          <-  segclust[idx + 1L]
  hcdata$segments$clust  <-  segclust
  hcdata$segments$line   <-  as.integer(segclust < 1L)
  hcdata$labels$clust    <-  labclust
  
  hcdata
}

set_labels_params <- function(nbLabels,
                              direction = c("tb", "bt", "lr", "rl"),
                              fan       = FALSE) {
  if (fan) {
    angle       <-  360 / nbLabels * 1:nbLabels + 90
    idx         <-  angle >= 90 & angle <= 270
    angle[idx]  <-  angle[idx] + 180
    hjust       <-  rep(0, nbLabels)
    hjust[idx]  <-  1
  } else {
    angle       <-  rep(0, nbLabels)
    hjust       <-  0
    if (direction %in% c("tb", "bt")) { angle <- angle + 45 }
    if (direction %in% c("tb", "rl")) { hjust <- 1 }
  }
  list(angle = angle, hjust = hjust, vjust = 0.5)
}

plot_ggdendro <- function(hcdata,
                          direction   = c("lr", "rl", "tb", "bt"),
                          fan         = FALSE,
                          scale.color = NULL,
                          branch.size = 1,
                          label.size  = 3,
                          nudge.label = 0.01,
                          expand.y    = 0.1) {
  

  direction <- match.arg(direction) # if fan = FALSE
  ybreaks   <- pretty(segment(hcdata)$y, n = 5)
  ymax      <- max(segment(hcdata)$y)
  
  ## branches
  p <- ggplot() +
    geom_segment(data         =  segment(hcdata),
                 aes(x        =  x,
                     y        =  y,
                     xend     =  xend,
                     yend     =  yend,
                     linetype =  factor(line),
                     colour   =  factor(clust)),
                 lineend      =  "round",
                 show.legend  =  FALSE,
                 size         =  branch.size)
  
  ## orientation
  if (fan) {
    p <- p +
      coord_polar(direction = -1) +
      scale_x_continuous(breaks = NULL,
                         limits = c(0, nrow(label(hcdata)))) +
      scale_y_reverse(breaks = ybreaks)
  } else {
    p <- p + scale_x_continuous(breaks = NULL)
    if (direction %in% c("rl", "lr")) {
      p <- p + coord_flip()
    }
    if (direction %in% c("bt", "lr")) {
      p <- p + scale_y_reverse(breaks = ybreaks)
    } else {
      p <- p + scale_y_continuous(breaks = ybreaks)
      nudge.label <- -(nudge.label)
    }
  }
  
  # labels
  labelParams <- set_labels_params(nrow(hcdata$labels), direction, fan)
  hcdata$labels$angle <- labelParams$angle
  
  p <- p +
    geom_text(data        =  label(hcdata),
              aes(x       =  x,
                  y       =  y,
                  label   =  label,
                  colour  =  factor(clust),
                  angle   =  angle),
              vjust       =  labelParams$vjust,
              hjust       =  labelParams$hjust,
              nudge_y     =  ymax * nudge.label,
              size        =  label.size,
              show.legend =  FALSE)
  
  # theme
    # p <- p + theme_pubr() +
    #   theme(axis.text.x=element_blank())
  
  # colors and limits
  if (!is.null(scale.color)) {
    scale.color <- c("#000000", scale.color) #my addition
    p <- p + scale_color_manual(values = scale.color)
  }
  
  ylim <- -round(ymax * expand.y, 1)
  p    <- p + expand_limits(y = ylim)

  
  p
}

```

```{r treed, echo=FALSE}
get_tree <- function(geobike_subset,
                  y_cols,
                  scale_it = TRUE,
                  center_it = TRUE,
                  hclust_method = "ward.D2"
){
  # dd <- dist(scale(geobike_subset[, .SD, .SDcols = y_cols],
  #                  center = center_it,
  #                  scale = scale_it),
  #            method = "euclidean")
  # dendro <- hclust(dd, method = hclust_method) %>%
  #   as.dendrogram() %>%
  #   place_labels(paste(geobike_subset[, model],
  #                      geobike_subset[, frame_size],
  #                      sep = ", "))
  
  cluster_data <- geobike_subset[, .SD, .SDcols = y_cols] %>%
    data.frame
  row.names(cluster_data) <- paste(geobike_subset[, model],
                                   geobike_subset[, frame_size],
                                   sep = ", ")
  d_matrix <- dist(scale(cluster_data,
                         center = center_it,
                         scale = scale_it),
                   method = "euclidean")
  hc <- hclust(d_matrix, method = hclust_method)
  return(hc)
  
}
```

```{r, echo=FALSE}
get_axle_crown <- function(){
  
}

get_chainstay_h <- function(chainstay_length, 
                            bottom_bracket_drop){
  # the horizontal component of chainstay length 
  # bbd = bottom bracket drop
  # csl = chainstay length
  chainstay_h <- sqrt(chainstay_length^2 - bottom_bracket_drop^2)
  return(chainstay_h)
}


get_rake_h <- function(offset, hta){
  # the horizontal component of fork offset
  rake_h <- offset/sin(deg_2_rad(hta))
  return(rake_h)
}

get_ht_h <- function(hta, htl){
  # the horizontal component of head_tube
  # hta = head tube angle
  # htl = head tube length
  ht_h <- htl*cos(deg_2_rad(hta))
  return(ht_h)
}
get_ht_v <- function(hta, htl){
  # the vertical component of head_tube
  # hta = head tube angle
  # htl = head tube length
  ht_v <- htl*sin(deg_2_rad(hta))
  return(ht_v)
}


get_fork_angle <- function(offset, axle_crown, head_tube_angle){
  # angle of fork axle-crown axis to horizontal
  # beta is angle of fork axle-crow to offset line
  beta <- acos(offset/axle_crown)*180/pi
  # delta is angle from offset line to horizontal
  delta <- 90 - head_tube_angle
  fork_angle <- beta - delta
  return(rake_h)
}
```

```{r head_tube_length, echo=FALSE}
# Solace OM3 does not specify head tube length. This can be
# computed using specs of Whisky MCX fork assuming this is
# the fork used to spec wheelbase
head_tube_length <- function(axle_crown, rake, stack, wheelbase){
  rake_h <- get_rake_h(geobike[, fork_offset_rake],
                       geobike[, head_tube_angle])
  fork_angle <- get_fork_angle(geobike[, fork_offset_rake],
                               geobike[, fork_axle_crown],
                               geobike[, head_tube_angle])
}
```

```{r chainstay_length, echo=FALSE}
# Vagabond Genesis does not specify chainstay length.
get_chainstay_length <- function(rake, reach, stack, wheelbase,
                                 hta, htl, bbd){
  head_tube_h <- get_ht_h(hta, htl)
  head_tube_v <- get_ht_v(hta, htl)
  fork_v <- stack -  bbd -
    head_tube_v
  
  fork_h1 = fork_v/tan(deg_2_rad(hta))
  rake_h <- get_rake_h(rake,
                       hta)
  chainstay_h <- wheelbase - reach - head_tube_h - fork_h1 - 
    rake_h
  
  chainstay <- sqrt(chainstay_h^2 + bbd^2)
  
  return(chainstay)
}
```

```{r get-fork-offset, echo=FALSE}
get_fork_offset <- function(stack, reach, head_tube_angle, chainstay_length, bottom_bracket_drop, wheelbase){
  # steer_axis_h is base of triangle from top-head-tube to vertex created by steering axis and wheelbase.
  # tan hta <- stack/steer_axis_h
  steer_axis_v <- stack - bottom_bracket_drop
  steer_axis_h <- steer_axis_v /
    tan(deg_2_rad(head_tube_angle))
  chainstay_h <- get_chainstay_h(chainstay_length,
                                 bottom_bracket_drop)
  rake_h <- wheelbase - chainstay_h - reach - steer_axis_h
  rake <- rake_h * sin(deg_2_rad(head_tube_angle))
  return(rake)
}
```

```{r get-effective-top-tube-length, echo=FALSE}
get_effective_top_tube_length <- function(stack,
                                          reach,
                                          seat_tube_angle){
  # amigo bug out is missing this
  #
  seat_h <- stack/tan(deg_2_rad(seat_tube_angle))
  effective_top_tube_length <- seat_h + reach
  return(effective_top_tube_length)
}
```

```{r, echo=FALSE}
geom_checker <- function(chainstay_length, # chainstay length
                         bottom_bracket_drop, # bottom bracket drop
                         reach,
                         stack,
                         head_tube_angle, # head tube angle
                         rake, # head tube length
                         wheelbase){ # wheelbase
  # do all the horizontal components add to wheelbase?
  chainstay_length_h <- get_chainstay_h(chainstay_length,
                                        bottom_bracket_drop)
  steer_axis_v <- stack - bottom_bracket_drop
  steer_axis_h <- steer_axis_v /
    tan(deg_2_rad(head_tube_angle))

  rake_h <- get_rake_h(rake,
                       head_tube_angle)
  wheelbase_computed <- chainstay_length_h + reach +
    steer_axis_h + rake_h

  }
```

```{r read-bike-function, echo=FALSE}
# data_path <- here(data_folder, "ghost_grappler.txt")
# dt <- fread(data_path)
# bike_label = "Tumbleweed Stargazer 2022"
# bike_range = "b1:h21"

read_bike <- function(bike_label = "Breezer Radar X Pro 2022",
                      bike_range = "B1:I19"){
  data_file <- "bikes.xlsx"
  data_path <- here(data_folder, data_file)
  bike_wide <- read_excel(data_path,
                          sheet = bike_label,
                          range = bike_range) %>%
    data.table
  # re-read with coltype = numeric
  # col_type_list <- c("text", "text", rep("numeric", ncol(bike_wide)-2))
  # bike_wide <- read_excel(data_path,
  #                         sheet = bike_label,
  #                         range = bike_range,
  #                         col_types = col_type_list) %>%
  #   data.table
  
  
  bike_model <- substr(bike_label, 1, nchar(bike_label) - 5)
  model_year <- substr(bike_label,
                       nchar(bike_label) - 4,
                       nchar(bike_label))
  bike_wide <- bike_wide[, -2]
  bike <- data.table(
    model = bike_model,
    year = model_year,
    transpose(bike_wide,
              keep.names = "frame_size",
              make.names = 1)
  )
  keep_names <- c("model","frame_size", "seat_tube_length", "top_tube_effective_length", "head_tube_length", "seat_tube_angle", "head_tube_angle", "chainstay_length", "wheelbase", "bottom_bracket_drop", "fork_offset_rake", "stack", "reach", "standover", "stem_length", "handlebar_width", "crank_length", "wheel_size", "tire_width_spec", "tire_width_max")
  bike <- bike[, .SD, .SDcols = keep_names]
  
  # fill in missing
    # chainstay_length
  bike[, chainstay_length := 
         ifelse(is.na(chainstay_length),
                get_chainstay_length(fork_offset_rake,
                                     reach,
                                     stack,
                                     wheelbase,
                                     head_tube_angle,
                                     head_tube_length,
                                     bottom_bracket_drop),
                chainstay_length)]
    # fork_offset_rake
  bike[, fork_offset_rake := 
         ifelse(is.na(fork_offset_rake),
                get_fork_offset(stack,
                                reach,
                                head_tube_angle,
                                chainstay_length,
                                bottom_bracket_drop,
                                wheelbase),
                fork_offset_rake)]
  # top_tube_effective_length
  bike[, top_tube_effective_length := 
         ifelse(is.na(top_tube_effective_length),
                get_effective_top_tube_length(stack,
                                              reach,
                                              seat_tube_angle),
                top_tube_effective_length)] 
  
  # constructed measures
  radius <- (ifelse(bike$wheel_size == 700 | bike$wheel_size == 29, 622, 584) + bike$tire_width_spec*2)/2
  ## trail
  bike[, trail := radius/tan(head_tube_angle*pi/180) - 
         get_rake_h(fork_offset_rake, head_tube_angle)]
  ## bb height
  bike[, bb_height := radius - bottom_bracket_drop]
  
# from wikipedia
# bike[, trail := ((diameter + tire_width_spec*2)/2 * cos(head_tube_angle*pi/180) -
#                     fork_offset_rake) / sin(head_tube_angle*pi/180)]
  bike[, model_size := paste(model, frame_size)]
  bike[, rear_center := sqrt(chainstay_length^2 - bottom_bracket_drop^2)] # horizontal
  bike[, front_center := wheelbase - rear_center] # horizontal
  bike[, seat_center := stack/tan(deg_2_rad(seat_tube_angle))]
  
  # ratios
  bike[, stack_reach := stack/reach]
  bike[, front_rear := front_center/rear_center]
  bike[, rear_wheelbase := rear_center/wheelbase]
  bike[, front_wheelbase := front_center/wheelbase]
  bike[, sta_hta := seat_tube_angle/head_tube_angle]

  # decompositions
  # seat_tube_v and seat_tube_h are decomp of seat tube
  bike[, seat_tube_v := seat_tube_length *
         sin(deg_2_rad(seat_tube_angle))]
  bike[, seat_tube_h := seat_tube_length *
         cos(deg_2_rad(seat_tube_angle))]
  # seat_v and seat_h are decomp of seat positioned at stack height
  # tan(STA) = seat_h/seat_v
  bike[, seat_v := stack]
  bike[, seat_h := stack /
         tan(deg_2_rad(seat_tube_angle))]
  # head_v and head_h are decomp of head tube
  bike[, head_v := head_tube_length * sin(deg_2_rad(head_tube_angle))]
  bike[, head_h := head_tube_length * cos(deg_2_rad(head_tube_angle))]

  # landmarks with rear axle as origin
  bike[, x1 := 0] # rear axle
  bike[, y1 := 0]
  bike[, x2 := rear_center - seat_h] # seat at stack height
  bike[, y2 := stack - bottom_bracket_drop]
  bike[, x3 := rear_center + reach] # head tube top
  bike[, y3 := stack - bottom_bracket_drop]
  bike[, x4 := x3 + head_h] # head tube base
  bike[, y4 := y3 - head_v]
  bike[, x5 := wheelbase] # front axle
  bike[, y5 := 0]
  bike[, x6 := rear_center] # bottom bracket
  bike[, y6 := -bottom_bracket_drop]
  bike[, x7 := rear_center - seat_tube_h] # seat tube
  bike[, y7 := seat_tube_v]
  
  # landmarks_named
  bike[, rear_x := x1]
  bike[, rear_y := y1]
  bike[, seat_x := x2]
  bike[, seat_y := y2]
  bike[, head_x := x3]
  bike[, head_y := y3]
  bike[, crown_x := x4]
  bike[, crown_y := y4]
  bike[, front_x := x5]
  bike[, front_y := y5]
  bike[, bottom_x := x6]
  bike[, bottom_y := y6]
  bike[, seattube_x := x7]
  bike[, seattube_y := y7]
  
  return(bike)
}

```

```{r import-bikes, echo=FALSE}
import_it <- TRUE
if(import_it != TRUE){
  geo_bike_path <- here("rds", "geobike.Rds")
  geobike <- readRDS(geo_bike_path)
  my_fit_path <- here("rds", "my_fit.Rds")
  my_fit <- readRDS(my_fit_path)
}else{
  data_path <- here(data_folder, "bike_list.txt")
  bike_list <- fread(data_path)
  geobike <- data.table(NULL)
  for(i in 1:nrow(bike_list)){
    bike_label_i <- as.character(bike_list[i, "model"])
    bike_range_i <- as.character(bike_list[i, "data_range"])
    bike_i <- read_bike(bike_label = bike_label_i,
                        bike_range = bike_range_i)
    bike_i[, my_fit := ifelse(frame_size == c(bike_list[i, "my_fit"]), TRUE, FALSE)]
    geobike <- rbind(geobike, bike_i)
  }
  
  # my_fit: use 176 cm (I am 175.5)
  # add Breezer small to my_fit
  # geobike[model == "Breezer Radar X Pro" & frame_size == "48cm (S)", my_fit := TRUE]
  # add Boone 54 to my_fit
  # geobike[model == "Trek Boone 6" & frame_size == "54 cm", my_fit := TRUE]
  
  
  # add column of shape id for plots
  shape_list <- c(15,17,19,0,2)
  n_shapes <- length(shape_list)
  n_models <- length(unique(geobike[, model]))
  n_recycles <- floor(n_models/n_shapes)
  left_over <- n_models - n_recycles*n_shapes
  model_2_shape_map <- c(rep(shape_list, n_recycles), shape_list[1:left_over])
  geobike[, shape_id := model_2_shape_map[as.integer(as.factor(model))]]
  
  y_cols <- c("rear_x", "rear_y",
              "seat_x", "seat_y",
              "head_x", "head_y",
              "crown_x", "crown_y",
              "front_x", "front_y",
              "bottom_x", "bottom_y",
              "seattube_x", "seattube_y")
  
  # center X at bottom bracket
  geobike[, rear_x := rear_x - bottom_x]
  geobike[, seat_x := seat_x - bottom_x]
  geobike[, head_x := head_x - bottom_x]
  geobike[, crown_x := crown_x - bottom_x]
  geobike[, front_x := front_x - bottom_x]
  geobike[, bottom_x := bottom_x - bottom_x]
  geobike[, seattube_x := seattube_x - bottom_x]  
}


```

```{r my-fit, echo=FALSE}
my_fit <- geobike[my_fit == TRUE,]
```

```{r reduced-set-dendrogram-V2, fig.height=10, fig.width=10}
y_cols <- c("stack", "reach", "front_center", "rear_center", "head_tube_angle", "seat_tube_angle")

geobike_subset <- geobike[my_fit == TRUE,]
scale_it <- TRUE
center_it <- TRUE

tree_v2 <- get_tree(geobike_subset,
                y_cols,
                scale_it,
                center_it,
                hclust_method = "ward.D2")
tree_v2_color <- dendro_data_k(tree_v2, k = 3)
gg <- plot_ggdendro(tree_v2_color,
                      direction   = "lr",
                      expand.y    = 0.2,
                      scale.color = pal_okabe_ito)
 
gg
```

```{r style-table-V2}
options(knitr.kable.NA = '')

style_class <- tree_v2_color$labels %>%
  data.table()
style_class[, model := tstrsplit(label, ",", keep = 1)]

cluster_labels <- numeric(3)
trail <- "Breezer Radar X Pro"
cluster_labels[style_class[model == trail, clust]] <- "Trail"
all_road <- "OPEN U.P."
cluster_labels[style_class[model == all_road, clust]] <- "All-Road"
endurance <- "Mason InSearchOf"
cluster_labels[style_class[model == endurance, clust]] <- "Endurance"

style_class[, restyle := cluster_labels[clust]]
style_class[, restyle := factor(restyle,
                              levels = cluster_labels)]

# add style to geobike
if(import_it == TRUE){
  geobike <- plyr::join(geobike,
                        style_class[, .SD, .SDcols = c("model", "restyle")],
                        by = "model")
  my_fit <- geobike[my_fit == TRUE,]
}

style_table <-dcast(setDT(style_class), rowid(restyle) ~ restyle, value.var = "model")[, .SD, .SDcols = cluster_labels]

style_table %>%
  kable() %>%
  kable_styling(full_width = FALSE)


```

```{r saveRDS, echo=FALSE, eval=TRUE}
geo_bike_path <- here("rds", "geobike.Rds")
saveRDS(my_fit, geo_bike_path)
my_fit_path <- here("rds", "my_fit.Rds")
saveRDS(my_fit, my_fit_path)
```

```{r, echo=FALSE}
y_cols <- c(
  "reach", # 1
  "stack", # 2
  "seat_tube_length", # 3
  "top_tube_effective_length", # 4
  "head_tube_length", # 5
  "seat_tube_angle", # 6
  "head_tube_angle", # 7
  "chainstay_length", # 8
  "wheelbase", # 9
  "bottom_bracket_drop", # 10
  "fork_offset_rake", # 11
  "standover", # 12
  "trail", # 13
  "bb_height", # 14
  "rear_center", # 15
  "front_center", # 16
  "seat_center", # 17
  "stack_reach", # 18
  "front_rear", # 19
  "rear_wheelbase", # 20
  "front_wheelbase", # 21
  "sta_hta" # 22
  )

y_labels <- c(
  "reach", # 1
  "stack", # 2
  "seat tube length", # 3
  "top tube effective length", # 4
  "head tube length", # 5
  "seat tube angle", # 6
  "head tube angle", # 7
  "chainstay length", # 8
  "wheelbase", # 9
  "bottom bracket drop", # 10
  "fork offset", # 11
  "standover", # 12
  "trail", # 13
  "bottom bracket height", # 14
  "rear center", # 15
  "front center", # 16
  "seat center", # 17
  "stack:reach", # 18
  "front center:rear center", # 19
  "rear center:wheelbase", # 20
  "front center:wheelbase", # 21
  "sta:hta" # 22
  )

```

```{r scatterplot, echo=FALSE}

# x_menu.x <- -.1
# x_menu.y <- .9
# y_menu.x <- -.1
# y_menu.y <- .7
# annot.x <- -0.45
# annot.y <- 0.06
# 
# annot <- list(list(text = "Measure 1", x = annot.x, y = x_menu.y + annot.y, xref = 'paper', yref = 'paper', showarrow = FALSE),
#             list(text = "Measure 2", x = annot.x, y = y_menu.y + annot.y, xref = 'paper', yref = 'paper', showarrow = FALSE))
# 
x_menu.x <- .6
x_menu.y <- 1.1
y_menu.x <- -0.1
y_menu.y <- .5
annot_x.x <- x_menu.x - 0.3
annot_x.y <- x_menu.y
annot_y.x <- y_menu.x - 0.3
annot_y.y <- y_menu.y + 0.06

annot <- list(list(text = "Measure 1", x = annot_x.x, y = annot_x.y, xref = 'paper', yref = 'paper', showarrow = FALSE),
            list(text = "Measure 2", x = annot_y.x, y = annot_y.y, xref = 'paper', yref = 'paper', showarrow = FALSE))

update_menus <- list(
    list( # x menu
      x = x_menu.x,
      y = x_menu.y,
      buttons = list(
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[1])])),  # put it in a list
             label = y_labels[1]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[2])])),  # put it in a list
             label = y_labels[2]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[3])])),  # put it in a list
             label = y_labels[3]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[4])])),  # put it in a list
             label = y_labels[4]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[5])])),  # put it in a list
             label = y_labels[5]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[6])])),  # put it in a list
             label = y_labels[6]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[7])])),  # put it in a list
             label = y_labels[7]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[8])])),  # put it in a list
             label = y_labels[8]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[9])])),  # put it in a list
             label = y_labels[9]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[10])])),  # put it in a list
             label = y_labels[10]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[11])])),  # put it in a list
             label = y_labels[11]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[12])])),  # put it in a list
             label = y_labels[12]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[13])])),  # put it in a list
             label = y_labels[13]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[14])])),  # put it in a list
             label = y_labels[14]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[15])])),  # put it in a list
             label = y_labels[15]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[16])])),  # put it in a list
             label = y_labels[16]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[17])])),  # put it in a list
             label = y_labels[17]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[18])])),  # put it in a list
             label = y_labels[18]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[19])])),  # put it in a list
             label = y_labels[19]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[20])])),  # put it in a list
             label = y_labels[20]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[21])])),  # put it in a list
             label = y_labels[21]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[22])])),  # put it in a list
             label = y_labels[22])
        )),
    list( # y menu
      x = y_menu.x,
      y = y_menu.y,
      buttons = list(
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[2])])),
             label = y_labels[2]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[1])])),  # put it in a list
             label = y_labels[1]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[3])])),  # put it in a list
             label = y_labels[3]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[4])])),  # put it in a list
             label = y_labels[4]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[5])])),  # put it in a list
             label = y_labels[5]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[6])])),  # put it in a list
             label = y_labels[6]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[7])])),  # put it in a list
             label = y_labels[7]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[8])])),  # put it in a list
             label = y_labels[8]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[9])])),  # put it in a list
             label = y_labels[9]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[10])])),  # put it in a list
             label = y_labels[10]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[11])])),  # put it in a list
             label = y_labels[11]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[12])])),  # put it in a list
             label = y_labels[12]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[13])])),  # put it in a list
             label = y_labels[13]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[14])])),  # put it in a list
             label = y_labels[14]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[15])])),  # put it in a list
             label = y_labels[15]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[16])])),  # put it in a list
             label = y_labels[16]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[17])])),  # put it in a list
             label = y_labels[17]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[18])])),  # put it in a list
             label = y_labels[18]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[19])])),  # put it in a list
             label = y_labels[19]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[20])])),  # put it in a list
             label = y_labels[20]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[21])])),  # put it in a list
             label = y_labels[21]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[22])])),  # put it in a list
             label = y_labels[22])
        ))
)

p <- plot_ly(data = my_fit, x = ~reach, y = ~stack,
             type = 'scatter', mode = 'markers',
             #              hoverinfo = 'text',
#             color = ~restyle,
             text = ~paste(model, frame_size))

p <- plot_ly() %>%
  add_trace(data = my_fit[restyle == "Trail",], x = ~reach, y = ~stack,
            type = "scatter", mode = "markers", 
            color = "blue",
            marker = list(showlegend = FALSE)) %>%
  add_trace(data = my_fit[restyle == "Endurance",], x = ~reach, y = ~stack,
            type = "scatter", mode = "markers", 
            color = "red",
            marker = list(showlegend = FALSE)) %>%
  add_trace(data = my_fit[restyle == "All-Road",], x = ~reach, y = ~stack,
            type = "scatter", mode = "markers", 
            color = "green",
            marker = list(showlegend = FALSE))


p <- p %>%
  layout(  xaxis = list(title = ""),
           yaxis = list(title = ""),
           #           annotations = annot,
           legend = list(x = -0.3, y = .9),
           updatemenus = update_menus)

p
```

```{r scatterplot-2, eval=FALSE, echo=FALSE}

x_menu.x <- -.1
x_menu.y <- .9
y_menu.x <- -.1
y_menu.y <- .7
annot.x <- -0.45
annot.y <- 0.06
annot <- list(list(text = "Measure 1", x = annot.x, y = x_menu.y + annot.y, xref = 'paper', yref = 'paper', showarrow = FALSE),
            list(text = "Measure 2", x = annot.x, y = y_menu.y + annot.y, xref = 'paper', yref = 'paper', showarrow = FALSE))

update_menus <- list(
    list( # x menu
      x = x_menu.x,
      y = x_menu.y,
      buttons = list(
        list(method = "update",
             args = list("x",
                         list("visible", list(TRUE, FALSE, FALSE)),
                         list(xaxis = list(title = y_labels[1]))),
             label = y_labels[1]),
        list(method = "update",
             args = list("x",
                         list("visible", list(FALSE, TRUE, FALSE)),
                         list(xaxis = list(title = y_labels[2]))),
             label = y_labels[2]),
        list(method = "update",
             args = list("x",
                         list("visible", list(FALSE, FALSE, TRUE)),
                         list(xaxis = list(title = y_labels[3]))),
             label = y_labels[3])
        )),
    list( # y menu
      x = y_menu.x,
      y = y_menu.y,
      buttons = list(
        list(method = "update",
             args = list("y",
                         list("visible", list(FALSE, TRUE, FALSE)),
                         list(yaxis = list(title = y_labels[2]))),
             label = y_labels[2]),
        list(method = "update",
             args = list("y",
                         list("visible", list(TRUE, FALSE, FALSE)),
                         list(yaxis = list(title = y_labels[1]))),
             label = y_labels[1]),
        list(method = "update",
             args = list("y",
                         list("visible", list(FALSE, FALSE, TRUE)),
                         list(yaxis = list(title = y_labels[3]))),
             label = y_labels[3])
        ))
)

p <- plot_ly(data = my_fit, x = ~reach, y = ~stack,
               type = 'scatter', mode = 'markers',
 #              hoverinfo = 'text',
               text = ~paste(model, frame_size))

 p <- p %>%
  add_markers(x = ~get(y_cols[2]), name = y_labels[2], visible = FALSE) %>%
  add_markers(x = ~get(y_cols[3]), name = y_labels[3], visible = FALSE) %>%
  add_markers(y = ~get(y_cols[1]), name = y_labels[1], visible = FALSE) %>%
  add_markers(y = ~get(y_cols[3]), name = y_labels[3], visible = FALSE)


p <- p %>%
  layout(  xaxis = list(title = "Measure 1"),
           yaxis = list(title = "Measure 2"),
           showlegend = FALSE,
           annotations = annot,
           updatemenus = update_menus)

p
```

```{r}
# https://github.com/fjodor/exploring-plotly/blob/main/Shiny-like%20interactivity_selectors.Rmd
shared_data <- my_fit %>% 
  SharedData$new()

p <- shared_data %>% 
  plot_ly(x = ~reach, y = ~stack, color = ~restyle,
              hoverinfo = "text",
              text = ~paste(model, frame_size)) %>% 
  group_by(restyle) %>% 
  add_markers(size = 3) %>%
  layout(xaxis = list(title = ""),
         yaxis = list(title = ""),
         legend = list(x = -0.3, y = .9))


bscols(widths = c(3, 9),
       list(
            filter_checkbox(id = "style", label = "Style",
                    sharedData = shared_data, group = ~restyle)
      ),
       p)

```

```{r}

update_menus <- list(
    list( # x menu
      x = x_menu.x,
      y = x_menu.y,
      buttons = list(
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[1])])),  # put it in a list
             label = y_labels[1]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[2])])),  # put it in a list
             label = y_labels[2]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[3])])),  # put it in a list
             label = y_labels[3]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[4])])),  # put it in a list
             label = y_labels[4]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[5])])),  # put it in a list
             label = y_labels[5]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[6])])),  # put it in a list
             label = y_labels[6]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[7])])),  # put it in a list
             label = y_labels[7]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[8])])),  # put it in a list
             label = y_labels[8]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[9])])),  # put it in a list
             label = y_labels[9]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[10])])),  # put it in a list
             label = y_labels[10]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[11])])),  # put it in a list
             label = y_labels[11]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[12])])),  # put it in a list
             label = y_labels[12]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[13])])),  # put it in a list
             label = y_labels[13]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[14])])),  # put it in a list
             label = y_labels[14]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[15])])),  # put it in a list
             label = y_labels[15]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[16])])),  # put it in a list
             label = y_labels[16]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[17])])),  # put it in a list
             label = y_labels[17]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[18])])),  # put it in a list
             label = y_labels[18]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[19])])),  # put it in a list
             label = y_labels[19]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[20])])),  # put it in a list
             label = y_labels[20]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[21])])),  # put it in a list
             label = y_labels[21]),
        list(method = "restyle",
             args = list("x", list(my_fit[, get(y_cols[22])])),  # put it in a list
             label = y_labels[22])
        )),
    list( # y menu
      x = y_menu.x,
      y = y_menu.y,
      buttons = list(
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[2])])),
             label = y_labels[2]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[1])])),  # put it in a list
             label = y_labels[1]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[3])])),  # put it in a list
             label = y_labels[3]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[4])])),  # put it in a list
             label = y_labels[4]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[5])])),  # put it in a list
             label = y_labels[5]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[6])])),  # put it in a list
             label = y_labels[6]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[7])])),  # put it in a list
             label = y_labels[7]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[8])])),  # put it in a list
             label = y_labels[8]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[9])])),  # put it in a list
             label = y_labels[9]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[10])])),  # put it in a list
             label = y_labels[10]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[11])])),  # put it in a list
             label = y_labels[11]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[12])])),  # put it in a list
             label = y_labels[12]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[13])])),  # put it in a list
             label = y_labels[13]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[14])])),  # put it in a list
             label = y_labels[14]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[15])])),  # put it in a list
             label = y_labels[15]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[16])])),  # put it in a list
             label = y_labels[16]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[17])])),  # put it in a list
             label = y_labels[17]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[18])])),  # put it in a list
             label = y_labels[18]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[19])])),  # put it in a list
             label = y_labels[19]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[20])])),  # put it in a list
             label = y_labels[20]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[21])])),  # put it in a list
             label = y_labels[21]),
        list(method = "restyle",
             args = list("y", list(my_fit[, get(y_cols[22])])),  # put it in a list
             label = y_labels[22])
        ))
)

shared_data <- my_fit %>% 
  SharedData$new()

p <- shared_data %>% 
  plot_ly(x = ~reach, y = ~stack, color = ~restyle,
          hoverinfo = "text",
          text = ~paste(model, frame_size)) %>% 
  group_by(restyle) %>% 
  add_markers(size = 3) %>%
  layout(xaxis = list(title = ""),
         yaxis = list(title = ""),
         showlegend = FALSE,
         updatemenus = update_menus)


bscols(widths = c(3, 9),
       list(
            filter_checkbox(id = "style", label = "Style",
                    sharedData = shared_data, group = ~restyle)
      ),
       p)


```

```{r, out.width = "100%"}
shared_data <- my_fit %>% 
  SharedData$new()

p1 <- shared_data %>% 
  plot_ly(x = ~reach, y = ~stack, color = ~restyle,
          hoverinfo = "text",
          text = ~paste(model, frame_size,
          "<br>Cat:", restyle,
          "<br>Reach:", reach,
          "<br>Stack:", stack)) %>% 
  group_by(restyle) %>% 
  add_markers(size = 3) %>%
  layout(xaxis = list(title = "Reach"),
         yaxis = list(title = "Stack"),
         showlegend = FALSE)
p2 <- shared_data %>% 
  plot_ly(x = ~head_tube_angle, y = ~seat_tube_angle, color = ~restyle,
          hoverinfo = "text",
          text = ~paste(model, frame_size,
          "<br>Cat:", restyle,
          "<br>HTA:", head_tube_angle,
          "<br>STA:", seat_tube_angle)) %>% 
  group_by(restyle) %>% 
  add_markers(size = 3) %>%
  layout(xaxis = list(title = "Head Tube Angle"),
         yaxis = list(title = "Seat Tube Angle"),
         showlegend = FALSE)
p3 <- shared_data %>% 
  plot_ly(x = ~rear_center, y = ~front_center, color = ~restyle,
          hoverinfo = "text",
          text = ~paste(model, frame_size,
          "<br>Cat:", restyle,
          "<br>RC:", rear_center,
          "<br>FC:", front_center)) %>% 
  group_by(restyle) %>% 
  add_markers(size = 3) %>%
  layout(xaxis = list(title = "Rear Center (Horizontal)"),
         yaxis = list(title = "Front Center (Horizontal)"),
         showlegend = FALSE)
p4 <- shared_data %>% 
  plot_ly(x = ~trail, y = ~bottom_bracket_drop, color = ~restyle,
          hoverinfo = "text",
          text = ~paste(model, frame_size,
          "<br>Cat:", restyle,
          "<br>Trail:", round(trail, 0),
          "<br>BB Drop:", bottom_bracket_drop)) %>% 
  group_by(restyle) %>% 
  add_markers(size = 3) %>%
  layout(xaxis = list(title = "Trail"),
         yaxis = list(title = "Bottom Bracket Drop"),
         showlegend = FALSE)

bscols(widths = c(2, 5, 5),
       list(
         filter_checkbox(id = "style", label = "Style",
                         sharedData = shared_data, group = ~restyle)
       ),
       list(p1, p2),
       list(p3, p4)
       )

```
