---
title: "Bike Geometry Project"
author: "Jeffrey Walker"
date: "`r Sys.Date()`"
output: html_document
---

# Setup

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      knitr.kable.NA = '')
# wrangling packages
library(here) # here makes a project transportable
library(janitor) # clean_names
library(readxl) # read excel, duh!
library(openxlsx) # write excel
library(data.table) # magical data frames
library(magrittr) # pipes
library(stringr) # string functions
library(forcats) # factor functions
library(arules) # discretize function

# prediction packages for rider_height
library(glmnet)
library(ranger)
library(xgboost)

# cluster packages
library(ggdendro) # dendrogram
library(dendextend) # better dendrogram
library(bootcluster) # bootstrap dendrogram
library(fpc) # cluster stability
library(mclust) # clustering
library(COveR) # overlapping kmeans
library(ksharp) # sharpen kmeans
library(ktaucenters) # robust kmeans

# web helper packages
library(priceR)
Sys.setenv("EXCHANGERATEHOST_ACCESS_KEY"="4caf1c67ee8dfb8e14158a2e44616e16")

# graphing packages
library(ggsci) # color palettes
library(ggpubr) # publication quality plots
library(ggforce) # better jitter
library(cowplot) # combine plots
library(knitr) # kable tables
library(kableExtra) # kable_styling tables

# html packages
library(DT)
library(reactable)
library(htmltools)
library(jsonlite)

library(ggiraph)
library(GGally)

# plotly
library(plotly)
library(flexdashboard)
library(crosstalk)

# ggplot_the_model.R packages not loaded above
library(insight)
library(lazyWeave)

# use here from the here package
here <- here::here
# use clean_names from the janitor package
clean_names <- janitor::clean_names
# use transpose from data.table
transpose <- data.table::transpose

# load functions used by this text written by me
# ggplot_the_model.R needs to be in the folder "R"
# if you didn't download this and add to your R folder in your
# project, then this line will cause an error
#source_path <- here("R", "ggplot_the_model.R")
#source(source_path)

data_folder <- "data"
image_folder <- "images"
output_folder <- "output"

pal_okabe_ito <- c(
  "#E69F00",
  "#56B4E9",
  "#009E73",
  "#F0E442",
  "#0072B2",
  "#D55E00",
  "#CC79A7"
)
pal_okabe_ito_7 <- pal_okabe_ito[c(2,3,1,4,5,6,7)]
pal_okabe_ito_3 <- pal_okabe_ito[c(2,3,1)]
pal_okabe_ito_4 <- c(pal_okabe_ito_3, pal_okabe_ito[c(6)])
```

# Functions

## General

```{r deg_2_rad}
deg_2_rad <- function(x){
  rad <- x*pi/180
  return(rad)
}
  
```

```{r}
extract_country <- function(x) {
  # split once from the right; take last field
  parts <- tstrsplit(x, ",", fixed = TRUE)
  # `parts` is a list; the last element is the country
  trimws(parts[[length(parts)]])
}
```

## Dendrogram

```{r ggdendro-extensions}
# https://atrebas.github.io/post/2019-06-08-lightweight-dendrograms/
dendro_data_k <- function(hc, k) {
  hcdata    <-  ggdendro::dendro_data(hc, type = "rectangle")
  seg       <-  hcdata$segments
  labclust  <-  cutree(hc, k)[hc$order]
  segclust  <-  rep(0L, nrow(seg))
  heights   <-  sort(hc$height, decreasing = TRUE)
  height    <-  mean(c(heights[k], heights[k - 1L]), na.rm = TRUE)
  
  for (i in 1:k) {
    xi      <-  hcdata$labels$x[labclust == i]
    idx1    <-  seg$x    >= min(xi) & seg$x    <= max(xi)
    idx2    <-  seg$xend >= min(xi) & seg$xend <= max(xi)
    idx3    <-  seg$yend < height
    idx     <-  idx1 & idx2 & idx3
    segclust[idx] <- i
  }
  
  idx                    <-  which(segclust == 0L)
  segclust[idx]          <-  segclust[idx + 1L]
  hcdata$segments$clust  <-  segclust
  hcdata$segments$line   <-  as.integer(segclust < 1L)
  hcdata$labels$clust    <-  labclust
  
  hcdata
}

set_labels_params <- function(nbLabels,
                              direction = c("tb", "bt", "lr", "rl"),
                              fan       = FALSE) {
  if (fan) {
    angle       <-  360 / nbLabels * 1:nbLabels + 90
    idx         <-  angle >= 90 & angle <= 270
    angle[idx]  <-  angle[idx] + 180
    hjust       <-  rep(0, nbLabels)
    hjust[idx]  <-  1
  } else {
    angle       <-  rep(0, nbLabels)
    hjust       <-  0
    if (direction %in% c("tb", "bt")) { angle <- angle + 45 }
    if (direction %in% c("tb", "rl")) { hjust <- 1 }
  }
  list(angle = angle, hjust = hjust, vjust = 0.5)
}

plot_ggdendro <- function(hcdata,
                          direction   = c("lr", "rl", "tb", "bt"),
                          fan         = FALSE,
                          scale.color = NULL,
                          branch.size = 1,
                          label.size  = 3,
                          nudge.label = 0.01,
                          expand.y    = 0.1) {
  

  direction <- match.arg(direction) # if fan = FALSE
  ybreaks   <- pretty(segment(hcdata)$y, n = 5)
  ymax      <- max(segment(hcdata)$y)
  
  ## branches
  p <- ggplot() +
    geom_segment(data         =  segment(hcdata),
                 aes(x        =  x,
                     y        =  y,
                     xend     =  xend,
                     yend     =  yend,
                     linetype =  factor(line),
                     colour   =  factor(clust)),
                 lineend      =  "round",
                 show.legend  =  FALSE,
                 size         =  branch.size)
  
  ## orientation
  if (fan) {
    p <- p +
      coord_polar(direction = -1) +
      scale_x_continuous(breaks = NULL,
                         limits = c(0, nrow(label(hcdata)))) +
      scale_y_reverse(breaks = ybreaks)
  } else {
    p <- p + scale_x_continuous(breaks = NULL)
    if (direction %in% c("rl", "lr")) {
      p <- p + coord_flip()
    }
    if (direction %in% c("bt", "lr")) {
      p <- p + scale_y_reverse(breaks = ybreaks)
    } else {
      p <- p + scale_y_continuous(breaks = ybreaks)
      nudge.label <- -(nudge.label)
    }
  }
  
  # labels
  labelParams <- set_labels_params(nrow(hcdata$labels), direction, fan)
  hcdata$labels$angle <- labelParams$angle
  
  p <- p +
    geom_text(data        =  label(hcdata),
              aes(x       =  x,
                  y       =  y,
                  label   =  label,
                  colour  =  factor(clust),
                  angle   =  angle),
              vjust       =  labelParams$vjust,
              hjust       =  labelParams$hjust,
              nudge_y     =  ymax * nudge.label,
              size        =  label.size,
              show.legend =  FALSE)
  
  # theme
    # p <- p + theme_pubr() +
    #   theme(axis.text.x=element_blank())
  
  # colors and limits
  if (!is.null(scale.color)) {
    scale.color <- c("#000000", scale.color) #my addition
    p <- p + scale_color_manual(values = scale.color)
  }
  
  ylim <- -round(ymax * expand.y, 1)
  p    <- p + expand_limits(y = ylim)

  
  p
}

```

```{r treed}
get_tree <- function(geobike_subset,
                  y_cols,
                  scale_it = TRUE,
                  center_it = TRUE,
                  hclust_method = "ward.D2"
){
  # dd <- dist(scale(geobike_subset[, .SD, .SDcols = y_cols],
  #                  center = center_it,
  #                  scale = scale_it),
  #            method = "euclidean")
  # dendro <- hclust(dd, method = hclust_method) %>%
  #   as.dendrogram() %>%
  #   place_labels(paste(geobike_subset[, model],
  #                      geobike_subset[, frame_size],
  #                      sep = ", "))
  
  cluster_data <- geobike_subset[, .SD, .SDcols = y_cols] |>
    data.frame()
  row.names(cluster_data) <- paste(geobike_subset[, model],
                                   geobike_subset[, frame_size],
                                   sep = ", ")
  d_matrix <- dist(scale(cluster_data,
                         center = center_it,
                         scale = scale_it),
                   method = "euclidean")
  hc <- hclust(d_matrix, method = hclust_method)
  return(hc)
  
}
```

## Bike geometry helpers

```{r bike-geometry-helpers}
compute_axle_crown <- function(){
  
}

compute_chainstay_h <- function(bike){
  # the horizontal component of chainstay length 
  # bbd = bottom bracket drop
  # csl = chainstay length
  chainstay_h <- with(bike,
                      sqrt(chainstay_length^2 - bottom_bracket_drop^2))
  return(chainstay_h)
}


compute_offset_h <- function(bike){
  # the horizontal component of fork offset
  offset_h <- with(bike,
                 fork_offset_rake/sin(deg_2_rad(head_tube_angle)))
  return(offset_h)
}

compute_head_tube_h <- function(bike){
  # the horizontal component of head_tube
  head_tube_h <- with(bike,
               head_tube_length*cos(deg_2_rad(head_tube_angle)))
  return(head_tube_h)
}
compute_head_tube_v <- function(bike){
  # the vertical component of head_tube
  head_tube_v <- with(bike,
                      head_tube_length*sin(deg_2_rad(head_tube_angle)))
  return(head_tube_v)
}

compute_fork_angle <- function(bike){
  # angle of fork axle-crown axis to horizontal
  # beta is angle of fork axle-crow to offset line
  beta <- with(bike,
               acos(fork_offset_rake/axle_crown)*180/pi)
  # delta is angle from offset line to horizontal
  delta <- with(bike,
                90 - head_tube_angle)
  fork_angle <- beta - delta
  return(fork_angle)
}

compute_steering_v <- function(bike){
  # steering_v is the vertical component of the steering axis from top of head tube
  # to the horizontal line through wheel axles - so height from axle to head tube crown
  steering_v <- with(bike,
                     stack - bottom_bracket_drop)
  return(steering_v)
}

compute_steering_h <- function(bike){
  steering_v <- compute_steering_v(bike)
  steering_h <- with(bike,
                     steering_v/tan(deg_2_rad(head_tube_angle)))
  return(steering_h)
}

```

## Compute missing data

```{r missing data}
compute_wheelbase <- function(bike){
  steering_h <- compute_steering_h(bike[is.na(wheelbase)])
  offset_h <- compute_offset_h(bike[is.na(wheelbase)])
  chainstay_h <- compute_chainstay_h(bike[is.na(wheelbase)])
  reach <- bike[is.na(wheelbase), reach]
  wheelbase <- chainstay_h + reach + steering_h + offset_h
  return(wheelbase)
}

compute_head_tube_length <- function(bike){
  hta <- bike[, deg_2_rad(head_tube_angle)]
  fs <- bike[, stack] # frame stack
  bbd <- bike[, bottom_bracket_drop] # bb drop
  ac <- bike[, axle_crown] # axle_crown
  rake <- bike[, fork_offset_rake]
  cr <- ifelse(bike[1, material] == "steel" | bike[1, material] == "titanium", 10, 0)
  cr.v <- cr * sin(hta)
  beta <- acos(rake/ac)
  delta <- pi/2 - hta
  gamma <- beta - delta
  ac.v <- ac * sin(gamma)
  h.v <- fs - ac.v - cr.v - bbd
  htle <- h.v / sin(hta)
  # data.table(
  #   htl = bike[, head_tube_length],
  #   htle = htle
  # )
  return(htle)
}

# Vagabond Genesis does not specify chainstay length.
compute_chainstay_length <- function(bike){
  head_tube_h <- compute_head_tube_h(bike)
  head_tube_v <- compute_head_tube_v(bike)
  fork_v <- with(bike,
                 stack - bottom_bracket_drop - head_tube_v)
  
  fork_h1 = with(bike,
                 fork_v/tan(deg_2_rad(head_tube_angle)))
  offset_h <- compute_offset_h(bike)
  chainstay_h <- with(bike,
                      wheelbase - reach - head_tube_h - fork_h1 - 
                        offset_h)
  
  chainstay <- with(bike,
                    sqrt(chainstay_h^2 + bottom_bracket_drop^2))
  
  return(chainstay)
}

compute_fork_offset <- function(bike){
  # steer_axis_h is base of triangle from top-head-tube to vertex created by steering axis and wheelbase.
  # tan hta <- stack/steer_axis_h
  steer_axis_v <- with(bike,
                       stack - bottom_bracket_drop)
  steer_axis_h <- with(bike,
                       steer_axis_v /
                         tan(deg_2_rad(head_tube_angle)))
  chainstay_h <- compute_chainstay_h(bike)
  offset_h <- with(bike,
                   wheelbase - chainstay_h - reach - steer_axis_h)
  offset <- with(bike,
                 offset_h * sin(deg_2_rad(head_tube_angle)))
  return(offset)
}

compute_effective_top_tube_length <- function(bike){
  # amigo bug out is missing this
  #
  seat_h <- with(bike,
                 stack/tan(deg_2_rad(seat_tube_angle)))
  effective_top_tube_length <- with(bike,
                                    seat_h + reach)
  return(effective_top_tube_length)
}

compute_bottom_bracket_drop <- function(bike){
}
```

```{r}
estimate_axle_crown <- function(bike, material){
  # wb = rear_center + reach + headtube_h + headset_h + fork_h + rake_h
  hta <- bike[, head_tube_angle]
  wb <- bike[, wheelbase]
  rc <- bike[, rear_center]
  reach <- bike[, reach]
  headtube_h <- bike[, head_h]
  # would really need headset info, integrated vs zero stack vs external
  if(material == "carbon" | material == "aluminum"){
    headset_l <- 2
  }
  if(material == "titanium" | material == "steel"){
    headset_l <- 10
  }
  headset_h <- headset_l * cos(hta * pi/180)
  rake_h <- compute_offset_h(bike)
  zero_offset_fork_h <- wb - rc - reach - headtube_h - headset_h - rake_h # fork h wi
  fork_v <- tan(hta * pi/180) * zero_offset_fork_h
  fork_h <- zero_offset_fork_h + rake_h
  axle_crown <- sqrt(fork_v^2 + fork_h^2)
#  axle_crown <- rep(mean(axle_crown), length(axle_crown))
  return(axle_crown)

}
```

## geometery checker

```{r}
geom_checker <- function(chainstay_length, # chainstay length
                         bottom_bracket_drop, # bottom bracket drop
                         reach,
                         stack,
                         head_tube_angle, # head tube angle
                         rake, # head tube length
                         wheelbase){ # wheelbase
  # do all the horizontal components add to wheelbase?
  chainstay_length_h <- compute_chainstay_h(bike)
  steer_axis_v <- stack - bottom_bracket_drop
  steer_axis_h <- steer_axis_v /
    tan(deg_2_rad(head_tube_angle))

  offset_h <- compute_offset_h(bike)
  wheelbase_computed <- chainstay_length_h + reach +
    steer_axis_h + offset_h

  }
```

# Add sus fork modifications

```{r}
geometry_with_sus_fork <- function(frame,
                                   sus_length = 435,
                                   sus_travel = 40,
                                   sus_rake = 45,
                                   sus_sag = 0.1,
                                   headset_stack = 12){
  
  # note headset stack doesn't matter for this
  # AC length 30 mm is 425
  # AC length 40 mm is 435
  # Rockshox Rudy: 5% sag recommended. 435 - .05*40 = 433
  # Fox Taper-Cast: 15-20% sag recommended. 435 - 0.15*40 = 429
  # Cane Creek Invert has a PSI recommend but not a sag recommend
  # Lauf fork spec is 419 mm sagged at 6%, so 425 mm AC
  # 30 mm travel
  # Rudy: 425 - 0.05*30 = 423.5
  # Fox TC: 425 - 0.2*30 = 419
  # Cane Creek = Fox TC
  # Lauf 419 mm AC, 47mm rake
  # 40 mm travel
  # Rudy: 435 - 0.05*40 = 433
  # Fox TC: 435 - 0.2*40 = 427
  # Cane Creek = Fox TC
  # 50 mm travel
  # Fox: 445 - .2*50 = 435
  
  # frame <- geobike[model == "BMC URS AL 2022" & frame_size == "M", ]
  # frame <- geobike[model == "Sklar SS Ti 2025" & frame_size == "ML", ]
  # frame <- geobike[model == "Santa Cruz Stigmata CC 2023" & frame_size == "M", ]
  # check geom
  # stack = bbdrop + fork.v + headtube.v
  
  hta <- frame[1, head_tube_angle]
  sta <- frame[1, seat_tube_angle]
  rake <- frame[1, fork_offset_rake]
  wheelbase <- frame[1, wheelbase]
  fork_length <- frame[1, axle_crown]
  headtube_length <- frame[1, head_tube_length]
  bb_drop <- frame[1, bottom_bracket_drop]
  front_center <- frame[1, front_center]
  rear_center <- frame[1, rear_center]
  stack <- frame[1, stack]
  reach <- frame[1, reach]
 
  
  hta_r <- hta * pi/180
  fork_angle_r <- hta_r - asin(rake/fork_length)
  fork_angle <- fork_angle_r * 180/pi
  
  headtube.h <- headtube_length * cos(hta_r)
  headtube.v <- headtube_length * sin(hta_r)
  headset_h <- headset_stack * cos(hta_r)
  headset_v <- headset_stack * sin(hta_r)
  fork.h <- fork_length * cos(fork_angle_r)
  fork.v <- fork_length * sin(fork_angle_r)
  # check geom
  # bb_drop + fork.v + headtube.v + headset_v # computed stack
  # stack
  # rear_center + reach + headtube.h + headset_h + fork.h
  # wheelbase
  
  # check geom
  # stack = bbdrop + fork.v + headtube.v
  

  # new fork
  sag_length <- sus_length - sus_sag * sus_travel
  sus_fork_angle_r <- hta_r - asin(sus_rake/sag_length)
  sus_fork_angle <- sus_fork_angle_r * 180/pi # axle is now below horizon
  fork.h.new <- sag_length * cos(sus_fork_angle_r)
  fork.v.new<- sag_length * sin(sus_fork_angle_r)
  # sqrt(fork.x.new^2 + fork.y.new^2)

  dv = fork.v.new - fork.v
  dh = fork.h.new - fork.h

  alpha_r <- atan(dv/(wheelbase + dh)) # angle of rotation about rear axle
  alpha <- alpha_r * 180/pi
  wheelbase.new <- sqrt(dv^2 + (wheelbase + dh)^2)
  d_bb_drop <- rear_center/wheelbase * dv
  d_stack <- (rear_center+reach)/wheelbase * dv
  
  # rotate frame coordinates by alpha_r
  x_coords <- frame[1, .SD, .SDcols = paste0("x", 1:7)] |>
    as.numeric()
  y_coords <- frame[1, .SD, .SDcols = paste0("y", 1:7)] |>
    as.numeric()
  bike_coords <- matrix(c(x_coords, y_coords), ncol = 2)
  row.names(bike_coords) <- c("rear_axle", "top_effect_seat_tube", "top_head_tube",
                              "top_crown", "front_axle", "bottom_bracket",
                              "top_seat_tube")
  H = matrix(c(cos(alpha_r), -sin(alpha_r), sin(alpha_r), cos(alpha_r)),
             nrow = 2)
  new_coords <- bike_coords %*% H
  stack.new <- new_coords["top_head_tube", 2] - new_coords["bottom_bracket", 2]
  reach.new <- new_coords["top_head_tube", 1] - new_coords["bottom_bracket", 1]
  hta.new <- hta - alpha
  sta.new <- sta - alpha
  bb_drop.new <- -new_coords["bottom_bracket", 2]
  rear_center.new <- new_coords["bottom_bracket", 1]
  front_center.new <- wheelbase.new - rear_center.new

  # trail
  tire_width <- 45
  radius <- (ifelse(frame$wheel_size == 700 | frame$wheel_size == 29, 622, 584) +
               tire_width*2)/2
  offset_h <- sus_rake/sin(deg_2_rad(hta.new))

  trail_45.new <- radius/tan(hta_r) - offset_h
  
  # rear_axle = 1, top_seat = 2, top_head_tube = 3, top_crown = 4,
  # front_axle = 5, bottom_bracket = 6, top_seat_tube = 7
  
  measure_set <- c(
    sag_length = sag_length,
    wheelbase = wheelbase.new,
    stack = stack.new,
    reach = reach.new,
    hta = hta.new,
    sta = sta.new,
    bb_drop = bb_drop.new,
    rc = rear_center.new,
    fc = front_center.new,
    trail_45 = trail_45.new
  )
  names(measure_set) <- c("axle_crown_sag", "wheelbase", "stack", "reach", "hta", "sta", "bb_drop", "rc", "fc", "trail_45")

  return(measure_set)


}  

  
```

```{r sus-checker, eval=FALSE}
    sus_measures <- geometry_with_sus_fork(frame,
                                           sus_length = 435,
                                           sus_travel = 40,
                                           sus_rake = 45,
                                           sus_sag = .1,
                                           headset_stack = 0)
  
  measure_list <- c("axle_crown", "wheelbase", "stack", "reach", "head_tube_angle", "seat_tube_angle", "bottom_bracket_drop", "rear_center", "front_center", "trail")
  
  rigid_measures <- frame[, .SD, .SDcols = measure_list]
  
  data.table(
    measure = measure_list,
    rigid = rigid_measures |> as.numeric(),
    sus = sus_measures |> as.numeric()
  )
```

## stack sus columns to plot
```{r stack-sus-columns}
stack_sus_columns <- function(dt){
  frame_cols <- c("model", "frame_size", "model_size", "my_fit",
                  "frame_size_std", "kmeans_style", "color", "fork_offset_rake")
  geom_rigid <- c("stack", "reach", "head_tube_angle", "seat_tube_angle", "front_center", "rear_center", "bottom_bracket_drop", "trail_45")
  geom_30_45 <- paste(geom_rigid, "30 45")
  geom_30_51 <- paste(geom_rigid, "30 51")
  geom_40_45 <- paste(geom_rigid, "40 45")
  geom_40_51 <- paste(geom_rigid, "40 51")
  geom_50_45 <- paste(geom_rigid, "50 45")
  geom_50_50 <- paste(geom_rigid, "50 50")
  
  forks <- c("30 45", "30 51", "40 45", "40 51", "50 45", "50 50")
  stack_cols <- c("stack", paste("stack", forks))
  reach_cols <- c("reach", paste("reach", forks))
  sta_cols <- c("seat_tube_angle", paste("seat_tube_angle", forks))
  hta_cols <- c("head_tube_angle", paste("head_tube_angle", forks))
  bb_cols <- c("bottom_bracket_drop", paste("bottom_bracket_drop", forks))
  trail_cols <- c("trail_45", paste("trail_45", forks))
  fc_cols <- c("front_center", paste("front_center", forks))
  rc_cols <- c("rear_center", paste("rear_center", forks))
  
  sus_dt_wide <- dt[, .SD, .SDcols = c(frame_cols, geom_rigid,
                                       stack_cols, reach_cols, 
                                       sta_cols, hta_cols,
                                       bb_cols, trail_cols,
                                       fc_cols, rc_cols)]
  
  sus_dt <- melt(sus_dt_wide,
                 id.vars = frame_cols,
                 measure.vars = list(stack_cols, reach_cols, sta_cols, hta_cols,
                                     bb_cols, trail_cols, fc_cols, rc_cols),
                 variable.name = "fork",
                 value.name = c("stack", "reach", "seat_tube_angle", "head_tube_angle",
                                "bottom_bracket_drop", "trail_45", "front_center",
                                "rear_center"))
  # map fork id to fork label
  sus_dt[, fork := c("rigid", forks)[fork]] # this is used for popup and hover
  sus_dt[, fork_key := factor(fork, levels = c("rigid", forks))] # this is used for checkbox filter
  # replace rigid with fork specs
  sus_dt[fork == "rigid", fork := paste("0", round(fork_offset_rake,0))]
  
  # test columns
  sus_dt[substr(fork,1,2) == "0 ", travel := "rigid"]
  sus_dt[substr(fork,1,2) == "30", travel := "30 mm"]
  sus_dt[substr(fork,1,2) == "40", travel := "40 mm"]
  sus_dt[substr(fork,1,2) == "50", travel := "50 mm"]
  sus_dt[, travel := factor(travel, levels = c("rigid", "30 mm", "40 mm", "50 mm"))]
  sus_dt[, label := ifelse(travel == "rigid", "rigid", NA)]
  
  sus_dt[, row_id := paste(model_size, fork)]
  sus_dt[, row_id := .I]
  # make highlight column
  # highlight info text
  sus_dt[, highlight_text := paste(substr(fork, 1, 2), "travel;",
                                        substr(fork, 3, 5), "offset")]
  
  return(sus_dt)
}

```


# Read bike data

```{r}
get_frame_size_letters <- function(frame_size){
  frame_size_letters <- str_replace_all(frame_size, "[^A-Za-z0-9]", "")
  
  frame_size_letters <- str_replace(frame_size_letters, "2X", "XX")
  frame_size_letters <- str_replace(frame_size_letters, "3X", "XXX")

# Extract letters
  frame_size_letters <- str_extract_all(frame_size_letters,
                                        "[A-Za-z]+")[[1]] |>
    paste0(collapse = "")

  frame_size_letters <- toupper(frame_size_letters)
  frame_size_letters <- str_remove(frame_size_letters, "CM")
  frame_size_letters <- str_remove(frame_size_letters, "SIZE")
  frame_size_letters <- str_replace(frame_size_letters, "SMALL", "S")
  frame_size_letters <- str_replace(frame_size_letters, "MEDIUM", "M")
  frame_size_letters <- str_replace(frame_size_letters, "LARGE", "L")
  frame_size_letters <- str_replace(frame_size_letters, "SM", "S")
  frame_size_letters <- str_replace(frame_size_letters, "MD", "M")
  frame_size_letters <- str_replace(frame_size_letters, "LG", "L")
  frame_size_letters <- str_replace(frame_size_letters, "SL", "S")
  frame_size_letters <- str_replace(frame_size_letters, "MED", "M")
  frame_size_letters <- str_replace(frame_size_letters, "LRG", "L")
  frame_size_letters <- str_replace(frame_size_letters, "EXTRA", "X")
  frame_size_letters <- str_replace(frame_size_letters, "XM", "ML")
  frame_size_letters <- str_replace(frame_size_letters, "LA", "L")
 
  # something like "SmallMedium" maps to small but should map to "SM"
  # I think this can be deleted
  if(frame_size == "Small/Medium"){frame_size_letters <- "SM"}

  return(frame_size_letters)
}
```

```{r}
get_frame_size_numbers <- function(frame_size){
  frame_size_numbers <- str_replace_all(frame_size, "[^A-Za-z0-9]", "")
  frame_size_numbers <- str_replace(frame_size_numbers, "2X", "XX")
  frame_size_numbers <- str_replace(frame_size_numbers, "3X", "XXX")

# Extract numbers
  frame_size_numbers <- str_extract_all(frame_size_numbers,
                                        "[0-9]+")[[1]] |>
    paste0(collapse = "")
  frame_size_numbers <- str_replace(frame_size_numbers, "4446", "45")
  frame_size_numbers <- str_replace(frame_size_numbers, "4750", "49")
  frame_size_numbers <- str_replace(frame_size_numbers, "5153", "52")
  frame_size_numbers <- str_replace(frame_size_numbers, "5456", "55")
  frame_size_numbers <- str_replace(frame_size_numbers, "5759", "58")
  frame_size_numbers <- str_replace(frame_size_numbers, "6062", "61")
  if(nchar(frame_size_numbers) > 0){
    if(as.numeric(frame_size_numbers) > 100){
      frame_size_numbers <- as.numeric(frame_size_numbers)/10 
      frame_size_numbers <- as.character(frame_size_numbers)
    }
  }
  if(frame_size_numbers == ""){
    frame_size_numbers <- as.numeric(NA)
  }
  frame_size_numbers <- as.numeric(frame_size_numbers)

  return(frame_size_numbers)
}
```


```{r}
clean_frame_size <- function(bike){
  
  bike[, frame_size_orig := frame_size]
  
  # preprocess specific models
  
  # Norco search
  bike[frame_size == "S1", frame_size := "XS"]
  bike[frame_size == "S2", frame_size := "S"]
  bike[frame_size == "S3", frame_size := "M"]
  bike[frame_size == "S4", frame_size := "L"]
  bike[frame_size == "S5", frame_size := "XL"]

  # Pilot SCRAM
  bike[frame_size == "P1", frame_size := "XS"]
  bike[frame_size == "P2", frame_size := "S"]
  bike[frame_size == "P3", frame_size := "M"]
  bike[frame_size == "P4", frame_size := "L"]
  bike[frame_size == "P5", frame_size := "XL"]
  
  # Light Blue Darwin
  bike[frame_size == "Small/Medium", frame_size := "SMMD"] # this will convert to SM
  
  # Haute Sauce
  bike[frame_size == "S/M", frame_size := "SMMD"] # this will convert to SM

  # Esker bikes
  bike[frame_size == "S1/SM", frame_size := "S"]
  bike[frame_size == "S2/MD", frame_size := "M"]
  bike[frame_size == "S3/LG", frame_size := "L"]
  bike[frame_size == "S4/XL", frame_size := "XL"]
  
  # fustle causway
  bike[frame_size == "XS/SM", frame_size := "S"]
  bike[frame_size == "SM/MD", frame_size := "M"]
  bike[frame_size == "MD/LG", frame_size := "L"]
  bike[frame_size == "LG/XL", frame_size := "XL"]
  
  # Manzanita Whippet - use Lemond Size -- see excel sheet
  # 48.7	50.3	51.9	53.4	54.8	56.9	58.2	59.7
  bike[frame_size == "M1", frame_size := 48.7]
  bike[frame_size == "M2", frame_size := 50.3]
  bike[frame_size == "M3", frame_size := 51.9]
  bike[frame_size == "M4", frame_size := 53.4]
  bike[frame_size == "M5", frame_size := 54.8]
  bike[frame_size == "M6", frame_size := 56.9]
  bike[frame_size == "M7", frame_size := 58.2]
  bike[frame_size == "M8", frame_size := 59.7]

  # viral wanderer
  bike[frame_size == "V2", frame_size := "S"]
  bike[frame_size == "V3", frame_size := "M"]
  bike[frame_size == "V4", frame_size := "L"]
  bike[frame_size == "V5", frame_size := "XL"]

  # clean
  bike[, frame_size_working := toupper(frame_size)]

  bike[, frame_size_working := str_remove_all(frame_size_working, " ")]
  bike[, frame_size_letters := lapply(frame_size_working, get_frame_size_letters) |>
         unlist()]
  bike[, frame_size_numbers := lapply(frame_size_working, get_frame_size_numbers) |>
         unlist()]
  bike[frame_size_letters == "", frame_size_letters := NA]
  bike[frame_size_letters == "R", frame_size_letters := NA]
  bike[frame_size_letters == "T", frame_size_letters := NA]

  return(bike)

}
```

```{r read-geometry, echo=FALSE}
# data_path <- here(data_folder, "ghost_grappler.txt")
# dt <- fread(data_path)
# bike_label = "Tumbleweed Stargazer 2022"
# bike_range = "b1:h21"

read_geometry <- function(bike_label = "Alchemy Lycos 2023",
                      bike_range = "a1:h23",
                      data_file = "gravel.xlsx",
                      sheet = "Sheet1",
                      material = "carbon"){
  data_path <- here(data_folder, data_file)
  bike_wide <- read_excel(data_path,
                          sheet = sheet,
                          range = bike_range) |>
    data.table()
  # re-read with coltype = numeric
  # col_type_list <- c("text", "text", rep("numeric", ncol(bike_wide)-2))
  # bike_wide <- read_excel(data_path,
  #                         sheet = bike_label,
  #                         range = bike_range,
  #                         col_types = col_type_list) %>%
  #   data.table
  
  
  bike_model <- substr(bike_label, 1, nchar(bike_label) - 5)
  model_year <- substr(bike_label,
                       nchar(bike_label) - 3,
                       nchar(bike_label))
  bike_wide <- bike_wide[, -2]
  bike <- data.table(
    model = paste(bike_model, model_year),
    year = model_year,
    transpose(bike_wide,
              keep.names = "frame_size",
              make.names = 1)
  )

  if(!("frame_weight" %in% colnames(bike))){
    bike[, frame_weight := as.numeric(NA)]
  }
  if(!("rider_min" %in% colnames(bike))){
    bike[, rider_min := as.numeric(NA)]
    bike[, rider_max := as.numeric(NA)]
  }
  if(!("trail" %in% colnames(bike))){
    bike[, trail := as.numeric(NA)]
  }
  if("axle_to_crown" %in% colnames(bike)){
    setnames(bike, old = "axle_to_crown", new = "axle_crown")
  }
  if(!("axle_crown" %in% colnames(bike))){
    bike[, axle_crown := as.numeric(NA)]
  }
  bike[, axle_crown_in_data := ifelse(!is.na(axle_crown), TRUE, FALSE)]

  keep_names <- c("model", "year", "frame_size",
                  "stack", "reach", "seat_tube_length", "top_tube_effective_length",
                  "head_tube_length", "seat_tube_angle", "head_tube_angle",
                  "chainstay_length", "wheelbase", "bottom_bracket_drop", "frame_weight",
                  "fork_offset_rake", "axle_crown_in_data", "axle_crown", "trail",
                  "standover", "stem_length", "handlebar_width", "crank_length",
                  "wheel_size", "tire_width_spec", "tire_width_max",
                  "rider_min", "rider_max"
  )
  bike <- bike[, .SD, .SDcols = keep_names]
  return(bike)
}
```

```{r clean_and_compute, echo=FALSE}
# data_path <- here(data_folder, "ghost_grappler.txt")
# dt <- fread(data_path)
# bike_label = "Tumbleweed Stargazer 2022"
# bike_range = "b1:h21"

clean_and_compute <- function(bike){
 
       # clean strings
  bike[is.na(udh), udh := "NO/Unknown"]
  bike[udh == "no", udh := "NO/Unknown"]
  bike[udh == "yes", udh := "YES"]
  bike[udh == "optional", udh := "YES"]

  # axle spacing
  bike[, axle_spacing := rear_axle]
  bike[axle_spacing == "148", axle_spacing := "148 (boost)"]
  bike[axle_spacing == "142", axle_spacing := "142 (road)"]

  # max 1x chainring -- keep this NA if blank
  bike[, max_chainring_1x := ifelse(!is.na(max_chainring_1x),
                                    as.numeric(max_chainring_1x), NA_real_)]

  # dropper
  # bike[, stealth_dropper := as.character(NA)]
  bike[, stealth_dropper := "NO/Unknown"]
  bike[!is.na(routing_dropper) & routing_dropper == "internal", stealth_dropper := "YES"]
  bike[!is.na(routing_dropper) & routing_dropper == "yes", stealth_dropper := "YES"]

  # dropout
  bike[is.na(dropout), dropout := "fixed"]
  bike[dropout == "0", dropout := "fixed"]
  
  # suspension
  bike[, suspension_corrected := ifelse(!is.na(suspension_corrected), as.numeric(suspension_corrected), 0.0)]
  bike[, fork_suspension := ifelse(!is.na(fork_suspension), as.numeric(fork_suspension), 0.0)]
  
  # this should be temporary with only the old style where tire width is taken from geometry chart
  bike[is.na(tire_width_max_700c) & (wheel_size == 700 | wheel_size == 29), tire_width_max_700c := tire_width_max]
  bike[is.na(tire_width_max_650b) & (wheel_size == 650), tire_width_max_650b := tire_width_max]
  
  # process 700c and convert in to mm
  bike[, tire_width_max_700c := as.numeric(tire_width_max_700c)]
  bike[is.na(tire_width_max_700c), tire_width_max_700c := 0.0]
  bike[tire_width_max_700c < 6, tire_width_max_700c := tire_width_max_700c * 25.4]
  bike[, tire_width_max_700c := as.integer(tire_width_max_700c)]
  
  # process 650b and convert mm to in
  bike[, tire_width_max_650b := as.numeric(tire_width_max_650b)]
  bike[is.na(tire_width_max_650b), tire_width_max_650b := 0.0]
  bike[tire_width_max_650b > 6, tire_width_max_650b := round(tire_width_max_650b/25.4, 1)]
  
    # also temporary?
    # these should remain string
    # bike_i[, front_axle := as.integer(front_axle)]
    # bike_i[, rear_axle := as.integer(rear_axle)]

  # clean tire_width_max
  bike[tire_width_spec < 6, tire_width_spec := tire_width_spec * 25.4]
  bike[tire_width_max < 6, tire_width_max := tire_width_max * 25.4]
  bike[, tire_width_spec := round(tire_width_spec, 0)]
  bike[, tire_width_max := round(tire_width_max, 0)]
  
  # clean rider_spec
  bike[, rider_min_spec := rider_min]
  bike[, rider_max_spec := rider_max]
  n_sizes <- nrow(bike)
  if(n_sizes > 1){
    rider_min_vec <- bike[2:n_sizes, rider_min]
    rider_max_vec <- bike[1:(n_sizes-1), rider_max]
    rider_size <- (rider_min_vec + rider_max_vec)/2
    bike[2:n_sizes, rider_min := rider_size]
    bike[1:(n_sizes-1), rider_max := rider_size]
  }
  bike[, rider_height := (rider_min + rider_max)/2]

  # clean frame size
  bike <- clean_frame_size(bike)
  bike[!is.na(frame_size_numbers) & !is.na(frame_size_letters),
       frame_size := paste0(frame_size_numbers, frame_size_letters)]
  bike[!is.na(frame_size_numbers) & is.na(frame_size_letters),
       frame_size := frame_size_numbers |> as.character()]
  bike[is.na(frame_size_numbers) & !is.na(frame_size_letters),
       frame_size := frame_size_letters]
  
  # make country
  bike[, country := extract_country(location)]
  bike[country == "England", country := "United Kingdom"]
  bike[country == "Scotland", country := "United Kingdom"]
  bike[country == "Northern Ireland", country := "United Kingdom"]
  bike[country == "Wales", country := "United Kingdom"]
  bike[country == "UK", country := "United Kingdom"]

  # decompositions & missing
  # missing head_tube_length needed first
  bike[is.na(head_tube_length), head_tube_length :=
         compute_head_tube_length(bike[is.na(head_tube_length), ])]
  
  # need this
  bike[, rear_center := sqrt(chainstay_length^2 - bottom_bracket_drop^2)] # horizontal
  
  # seat_tube_v and seat_tube_h are decomp of seat tube
  bike[, seat_tube_v := seat_tube_length *
         sin(deg_2_rad(seat_tube_angle))]
  bike[, seat_tube_h := seat_tube_length *
         cos(deg_2_rad(seat_tube_angle))]
  # seat_v and seat_h are decomp of seat positioned at stack height
  # tan(STA) = seat_h/seat_v
  bike[, seat_v := stack]
  bike[, seat_h := stack /
         tan(deg_2_rad(seat_tube_angle))]
  # head_v and head_h are decomp of head tube
  bike[, head_v := head_tube_length * sin(deg_2_rad(head_tube_angle))]
  bike[, head_h := head_tube_length * cos(deg_2_rad(head_tube_angle))]

  # fill in missing
  # add axle crown if it and wheelbase are missing
#  bike[is.na(wheelbase) & is.na(axle_crown), axle_crown := 395]

  # wheelbase
  bike[is.na(wheelbase), wheelbase := compute_wheelbase(bike[is.na(wheelbase)])]

  # chainstay_length
  bike[is.na(chainstay_length), chainstay_length := compute_chainstay_length(bike)]

  # fork_offset_rake
  bike[is.na(fork_offset_rake), fork_offset_rake := compute_fork_offset(bike)]

  # top_tube_effective_length
  bike[is.na(top_tube_effective_length), top_tube_effective_length := compute_effective_top_tube_length(bike)]

  # axle crown
  frame_material <- bike[1, material]
  bike[, axle_crown_est := estimate_axle_crown(bike, frame_material)]
#  axle_crown_mean <- mean(bike[, axle_crown_est])
  if(diff(range(bike[, axle_crown_est])) < 5){
    axle_crown_mean <- median(bike[, axle_crown_est])
  }else{
    axle_crown_mean <- bike[, axle_crown_est]
  }
  bike[is.na(axle_crown), axle_crown := axle_crown_mean]
  
  # more stuff

  # effective seat post length
  bike[, seat_tube_effective_length := sin(seat_tube_angle*pi/180)*stack]
  
  # top tube angle
  bike[, seat_post_length := seat_tube_effective_length - seat_tube_length]
  bike[, top_tube_length := 
         sqrt(top_tube_effective_length^2 +
         seat_post_length^2 -
         2 * top_tube_effective_length * seat_post_length *
         cos(seat_tube_angle*pi/180))]
  bike[, top_tube_angle := 
         acos(
           -(seat_post_length^2 - 
              top_tube_length^2 - 
              top_tube_effective_length^2)/ 
             (2*top_tube_length*top_tube_effective_length)) * 180/pi]
  
  # constructed measures
  ## trail
  radius <- (ifelse(bike$wheel_size == 700 | bike$wheel_size == 29, 622, 584) + bike$tire_width_spec*2)/2
  # offset <- bike[, fork_offset_rake]
  # offset_h <- compute_offset_h(bike)
  # hta_r <- bike[, head_tube_angle] * pi/180
  # trail_est1 <- radius/tan(hta_r) - offset_h
  # trail_est2 <- (radius*cos(hta_r) - offset)/sin(hta_r)
  # trail_table <- data.table(
  #   radius = radius,
  #   offset = offset,
  #   offset_h = offset_h,
  #   hta = hta_r*180/pi,
  #   trail1 = trail_est1,
  #   trail2 = trail_est2
  # )
  
  # bike[, trail_est := radius/tan(head_tube_angle*pi/180) - 
  #        compute_offset_h(bike)]
  bike[, trail_est := (radius * cos(head_tube_angle*pi/180) - fork_offset_rake) /
         sin(head_tube_angle * pi / 180)]
  bike[is.na(trail), trail := trail_est]
  
  # trail_45 -- the trail that would occur with a 45 mmm tire on a 700c wheel
  radius_45 <- (622 + 45*2)/2
  bike[, trail_45 := (radius_45 * cos(head_tube_angle*pi/180) - fork_offset_rake) /
         sin(head_tube_angle * pi / 180)]
  
  ## bb height
  bike[, bb_height := radius - bottom_bracket_drop]

  
  bike[, model_size := paste(model, frame_size)]
  bike[, front_center := wheelbase - rear_center] # horizontal distance from bb to front axle
  bike[, front_end := front_center - reach] # horizontal distance from head tube to front axle
  bike[, seat_center := stack/tan(deg_2_rad(seat_tube_angle))]
  
  # ratios
  bike[, stack_reach := stack/reach]
  bike[, front_rear := front_center/rear_center]
  bike[, front_reach := front_end/reach]
  bike[, rear_wheelbase := rear_center/wheelbase]
  bike[, front_wheelbase := front_center/wheelbase]
  bike[, sta_hta := seat_tube_angle/head_tube_angle]

  
  bike[, effective_frame_reach := reach + seat_tube_h]
  bike[, effective_reach := reach + seat_tube_h + stem_length]

  # landmarks with rear axle as origin
  bike[, x1 := 0] # rear axle
  bike[, y1 := 0]
  bike[, x2 := rear_center - seat_h] # seat at stack height
  bike[, y2 := stack - bottom_bracket_drop]
  bike[, x3 := rear_center + reach] # head tube top
  bike[, y3 := stack - bottom_bracket_drop]
  bike[, x4 := x3 + head_h] # head tube base
  bike[, y4 := y3 - head_v]
  bike[, x5 := wheelbase] # front axle
  bike[, y5 := 0]
  bike[, x6 := rear_center] # bottom bracket
  bike[, y6 := -bottom_bracket_drop]
  bike[, x7 := rear_center - seat_tube_h] # seat tube
  bike[, y7 := seat_tube_v]
  
  # landmarks_named
  bike[, rear_x := x1]
  bike[, rear_y := y1]
  bike[, seat_x := x2]
  bike[, seat_y := y2]
  bike[, head_x := x3]
  bike[, head_y := y3]
  bike[, crown_x := x4]
  bike[, crown_y := y4]
  bike[, front_x := x5]
  bike[, front_y := y5]
  bike[, bottom_x := x6]
  bike[, bottom_y := y6]
  bike[, seattube_x := x7]
  bike[, seattube_y := y7]
  
  # geometry_with_sus_fork <- function(frame,
  #                                  sus_length = 425,
  #                                  sus_travel = 30,
  #                                  sus_rake = 45,
  #                                  headset_stack = 12){

  for(row_i in 1:nrow(bike)){
    # 5 % sag forks (Rudy)
    
    # 20% Sag forks (Fox, CC, Lauf)
    sus_length = 425
    sus_travel = 30
    sus_rake = 45
    sus_sag = 0.2
    headset_stack = 0
    sus_specs = paste(sus_travel, sus_rake)
    sus_measures <- geometry_with_sus_fork(
      bike[row_i], sus_length, sus_travel, sus_rake, sus_sag, headset_stack)
    bike[row_i, (paste("axle_crown", sus_specs)) :=
           sus_measures["axle_crown_sag"]]
    bike[row_i, (paste("wheelbase", sus_specs)) :=
           sus_measures["wheelbase"]]
    bike[row_i, (paste("stack", sus_specs)) :=
           sus_measures["stack"]]
    bike[row_i, (paste("reach", sus_specs)) :=
           sus_measures["reach"]]
    bike[row_i, (paste("head_tube_angle", sus_specs)) :=
           sus_measures["hta"]]
    bike[row_i, (paste("seat_tube_angle", sus_specs)) :=
           sus_measures["sta"]]
    bike[row_i, (paste("bottom_bracket_drop", sus_specs)) :=
           sus_measures["bb_drop"]]
    bike[row_i, (paste("rear_center", sus_specs)) :=
           sus_measures["rc"]]
    bike[row_i, (paste("front_center", sus_specs)) :=
           sus_measures["fc"]]
    bike[row_i, (paste("trail_45", sus_specs)) :=
           sus_measures["trail_45"]]

    sus_length = 435
    sus_travel = 40
    sus_rake = 45
    sus_specs = paste(sus_travel, sus_rake)
    sus_measures <- geometry_with_sus_fork(
      bike[row_i], sus_length, sus_travel, sus_rake, sus_sag, headset_stack)
    bike[row_i, (paste("axle_crown", sus_specs)) :=
           sus_measures["axle_crown_sag"]]
    bike[row_i, (paste("wheelbase", sus_specs)) :=
           sus_measures["wheelbase"]]
    bike[row_i, (paste("stack", sus_specs)) :=
           sus_measures["stack"]]
    bike[row_i, (paste("reach", sus_specs)) :=
           sus_measures["reach"]]
    bike[row_i, (paste("head_tube_angle", sus_specs)) :=
           sus_measures["hta"]]
    bike[row_i, (paste("seat_tube_angle", sus_specs)) :=
           sus_measures["sta"]]
    bike[row_i, (paste("bottom_bracket_drop", sus_specs)) :=
           sus_measures["bb_drop"]]
    bike[row_i, (paste("rear_center", sus_specs)) :=
           sus_measures["rc"]]
    bike[row_i, (paste("front_center", sus_specs)) :=
           sus_measures["fc"]]
    bike[row_i, (paste("trail_45", sus_specs)) :=
           sus_measures["trail_45"]]

    sus_length = 425
    sus_travel = 30
    sus_rake = 51
    sus_specs = paste(sus_travel, sus_rake)
    sus_measures <- geometry_with_sus_fork(
      bike[row_i], sus_length, sus_travel, sus_rake, sus_sag, headset_stack)
    bike[row_i, (paste("axle_crown", sus_specs)) :=
           sus_measures["axle_crown_sag"]]
    bike[row_i, (paste("wheelbase", sus_specs)) :=
           sus_measures["wheelbase"]]
    bike[row_i, (paste("stack", sus_specs)) :=
           sus_measures["stack"]]
    bike[row_i, (paste("reach", sus_specs)) :=
           sus_measures["reach"]]
    bike[row_i, (paste("head_tube_angle", sus_specs)) :=
           sus_measures["hta"]]
    bike[row_i, (paste("seat_tube_angle", sus_specs)) :=
           sus_measures["sta"]]
    bike[row_i, (paste("bottom_bracket_drop", sus_specs)) :=
           sus_measures["bb_drop"]]
    bike[row_i, (paste("rear_center", sus_specs)) :=
           sus_measures["rc"]]
    bike[row_i, (paste("front_center", sus_specs)) :=
           sus_measures["fc"]]
    bike[row_i, (paste("trail_45", sus_specs)) :=
           sus_measures["trail_45"]]

    sus_length = 435
    sus_travel = 40
    sus_rake = 51
    sus_specs = paste(sus_travel, sus_rake)
    sus_measures <- geometry_with_sus_fork(
      bike[row_i], sus_length, sus_travel, sus_rake, sus_sag, headset_stack)
    bike[row_i, (paste("axle_crown", sus_specs)) :=
           sus_measures["axle_crown_sag"]]
    bike[row_i, (paste("wheelbase", sus_specs)) :=
           sus_measures["wheelbase"]]
    bike[row_i, (paste("stack", sus_specs)) :=
           sus_measures["stack"]]
    bike[row_i, (paste("reach", sus_specs)) :=
           sus_measures["reach"]]
    bike[row_i, (paste("head_tube_angle", sus_specs)) :=
           sus_measures["hta"]]
    bike[row_i, (paste("seat_tube_angle", sus_specs)) :=
           sus_measures["sta"]]
    bike[row_i, (paste("bottom_bracket_drop", sus_specs)) :=
           sus_measures["bb_drop"]]
    bike[row_i, (paste("rear_center", sus_specs)) :=
           sus_measures["rc"]]
    bike[row_i, (paste("front_center", sus_specs)) :=
           sus_measures["fc"]]
    bike[row_i, (paste("trail_45", sus_specs)) :=
           sus_measures["trail_45"]]

    sus_length = 445
    sus_travel = 50
    sus_rake = 45
    sus_specs = paste(sus_travel, sus_rake)
    sus_measures <- geometry_with_sus_fork(
      bike[row_i], sus_length, sus_travel, sus_rake, sus_sag, headset_stack)
    bike[row_i, (paste("axle_crown", sus_specs)) :=
           sus_measures["axle_crown_sag"]]
    bike[row_i, (paste("wheelbase", sus_specs)) :=
           sus_measures["wheelbase"]]
    bike[row_i, (paste("stack", sus_specs)) :=
           sus_measures["stack"]]
    bike[row_i, (paste("reach", sus_specs)) :=
           sus_measures["reach"]]
    bike[row_i, (paste("head_tube_angle", sus_specs)) :=
           sus_measures["hta"]]
    bike[row_i, (paste("seat_tube_angle", sus_specs)) :=
           sus_measures["sta"]]
    bike[row_i, (paste("bottom_bracket_drop", sus_specs)) :=
           sus_measures["bb_drop"]]
    bike[row_i, (paste("rear_center", sus_specs)) :=
           sus_measures["rc"]]
    bike[row_i, (paste("front_center", sus_specs)) :=
           sus_measures["fc"]]
    bike[row_i, (paste("trail_45", sus_specs)) :=
           sus_measures["trail_45"]]
    
    sus_length = 445
    sus_travel = 50
    sus_rake = 50
    sus_specs = paste(sus_travel, sus_rake)
    sus_measures <- geometry_with_sus_fork(
      bike[row_i], sus_length, sus_travel, sus_rake, sus_sag, headset_stack)
    bike[row_i, (paste("axle_crown", sus_specs)) :=
           sus_measures["axle_crown_sag"]]
    bike[row_i, (paste("wheelbase", sus_specs)) :=
           sus_measures["wheelbase"]]
    bike[row_i, (paste("stack", sus_specs)) :=
           sus_measures["stack"]]
    bike[row_i, (paste("reach", sus_specs)) :=
           sus_measures["reach"]]
    bike[row_i, (paste("head_tube_angle", sus_specs)) :=
           sus_measures["hta"]]
    bike[row_i, (paste("seat_tube_angle", sus_specs)) :=
           sus_measures["sta"]]
    bike[row_i, (paste("bottom_bracket_drop", sus_specs)) :=
           sus_measures["bb_drop"]]
    bike[row_i, (paste("rear_center", sus_specs)) :=
           sus_measures["rc"]]
    bike[row_i, (paste("front_center", sus_specs)) :=
           sus_measures["fc"]]
    bike[row_i, (paste("trail_45", sus_specs)) :=
           sus_measures["trail_45"]]

    
  }
  
  return(bike)
}

```

```{r}
standardize_geometry_with_suspension <- function(){
  geobike[my_fit == TRUE & fork == "suspension" & fork_suspension == 0, model]
}
```

```{r}
assign_std_size_pred <- function(geobike){
  # assign std size from predictor
  median_sizes <- c(
    # XS
    (median(geobike[frame_size_letters == "XS", rider_min_pred], na.rm=TRUE) +
      median(geobike[frame_size_letters == "XS", rider_max_pred], na.rm=TRUE))/2,
    # S
    (median(geobike[frame_size_letters == "S", rider_min_pred], na.rm=TRUE) +
      median(geobike[frame_size_letters == "S", rider_max_pred], na.rm=TRUE))/2,
    # M
    (median(geobike[frame_size_letters == "M", rider_min_pred], na.rm=TRUE) +
      median(geobike[frame_size_letters == "M", rider_max_pred], na.rm=TRUE))/2,
    # L
    (median(geobike[frame_size_letters == "L", rider_min_pred], na.rm=TRUE) +
      median(geobike[frame_size_letters == "L", rider_max_pred], na.rm=TRUE))/2,
    # XL
    (median(geobike[frame_size_letters == "XL", rider_min_pred], na.rm=TRUE) +
      median(geobike[frame_size_letters == "XL", rider_max_pred], na.rm=TRUE))/2
  ) |> round(0)
  
# [1] 159 167 175 183 190
  m <- median_sizes[3]
  geobike[, frame_size_std_m := ifelse(rider_min_pred <= m & rider_max_pred > m, TRUE, NA)]
  geobike[frame_size_std_m == TRUE, frame_size_std := m]
  model_list_all <- unique(geobike[, model])
  model_list_med <- unique(geobike[frame_size_std_m == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_med)
  geobike[model == "Stooge Dirt Tracker 2025", frame_size_std_m := TRUE]

  s <- median_sizes[2]
  geobike[, frame_size_std_s := ifelse(rider_min_pred <= s & rider_max_pred > s, TRUE, NA)]
  geobike[frame_size_std_s == TRUE, frame_size_std := s]
  model_list_all <- unique(geobike[, model])
  model_list_med <- unique(geobike[frame_size_std_s == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_med)
  # geobike[model == model_list_diff[2], .SD, .SDcols = c("model", "frame_size", "rider_min", "rider_max", "rider_min_pred", "rider_max_pred")]
  
  l <- median_sizes[4]
  geobike[, frame_size_std_l := ifelse(rider_min_pred <= l & rider_max_pred >= l, TRUE, NA)]
  geobike[frame_size_std_l == TRUE, frame_size_std := l]
  model_list_all <- unique(geobike[, model])
  model_list_med <- unique(geobike[frame_size_std_l == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_med)
  # geobike[model == model_list_diff[6], .SD, .SDcols = c("model", "frame_size", "rider_min", "rider_max", "rider_min_pred", "rider_max_pred")]
  
  # assign each frame to a frame_size_std_fine
  # see "bike size classes.xlsx" and computations on "gravel_scatter.qmd"
  # rider_size <- c(151, 155, 159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199)
  # for(i in 1:nrow(geobike)){
  #   size_deltas <- abs(geobike[i, rider_height_pred] - rider_size)
  #   target_size <- which(size_deltas == min(size_deltas))
  #   geobike[i, frame_size_std_fine := rider_size[target_size]]
  # }
  
  # create columns for all cm heights
  geobike[, h0 := "all"]
  ticks <- seq(150, 200, by = 1)
  for (h in ticks) {
    col <- paste0("h", h)
    geobike[, (col) := ifelse(rider_min <= h & rider_max >= h, as.character(h), NA_character_)]
  }
  # create columns for all in heights
  geobike[, h0 := "all"]
  ticks <- seq(150, 200, by = 1)
  for (h in ticks) {
    col <- paste0("h", h)
    geobike[, (col) := ifelse(rider_min <= h & rider_max >= h, as.character(h), NA_character_)]
  }
  ticks <- seq(59, 79, by = 0.5)
  for (h in ticks) {
    col <- paste0("h", h)
    geobike[, (col) := ifelse(rider_min_inch <= h & rider_max_inch >= h, as.character(h), NA_character_)]
  }
  

  return(geobike)
}

# geobike[model == models[1], .SD, .SDcols = c("frame_size", paste0("rider_size_", 1:13))]
# 
# med <- geobike[frame_size_std_l == TRUE, c("model", "frame_size")]
# counts <- med[, .(N = .N), by = model]
# bad_models <- counts[N > 1, model]
# geobike[model == bad_models[1], .SD, .SDcols = c("frame_size", "rider_min", "rider_max", "rider_min_pred", "rider_max_pred", "frame_size_std_l")]
# 
# geobike[frame_size_std_s == TRUE & frame_size_std_m == TRUE, model_size]

```



```{r size-classes}

assign_std_size <- function(geobike){
  
  # Trek checkpoint mapping old (numbers) to new (sizes) sizing
  # xs - less than 49
  # small - 49, 52
  # medium - 52, 54
  # ml - 56
  # large - 58
  # xl - 61
  
  # get some data on average size for M and L
  # average M is 175
  # average L is 183.5
  median_sizes <- c(
    # XS
    (median(geobike[frame_size_letters == "XS", rider_min], na.rm=TRUE) +
      median(geobike[frame_size_letters == "XS", rider_max], na.rm=TRUE))/2,
    # S
    (median(geobike[frame_size_letters == "S", rider_min], na.rm=TRUE) +
      median(geobike[frame_size_letters == "S", rider_max], na.rm=TRUE))/2,
    # M
    (median(geobike[frame_size_letters == "M", rider_min], na.rm=TRUE) +
      median(geobike[frame_size_letters == "M", rider_max], na.rm=TRUE))/2,
    # L
    (median(geobike[frame_size_letters == "L", rider_min], na.rm=TRUE) +
      median(geobike[frame_size_letters == "L", rider_max], na.rm=TRUE))/2,
    # XL
    (median(geobike[frame_size_letters == "XL", rider_min], na.rm=TRUE) +
      median(geobike[frame_size_letters == "XL", rider_max], na.rm=TRUE))/2
  ) |> round(0)
  
  median_sizes <- c(159, 167, 175, 183, 191)


#  geobike[, frame_size_std := as.numeric(NA)]
  for(i in 1:nrow(geobike)){
    rider_min <- geobike[i, rider_min]
    rider_max <- geobike[i, rider_max]
    if(!is.na(rider_min)){
      for(j in 1:length(median_sizes)){
        if(median_sizes[j] >= rider_min & median_sizes[j] < rider_max){
          geobike[i, frame_size_std := median_sizes[j]]
        }
      }
    }else{
      geobike[i, frame_size_std := NA]
    }
  }
  
  # exceptions
  geobike[model == "Stooge Dirt Tracker 2025", frame_size_std := 175]

  # assign s/m/l classes
  model_list_all <- unique(geobike[, model])
  geobike[, frame_size_std_s := ifelse(frame_size_std == 167, TRUE, NA)]
  geobike[, frame_size_std_m := ifelse(frame_size_std == 175, TRUE, NA)]
  geobike[, frame_size_std_l := ifelse(frame_size_std == 183, TRUE, NA)]

# do Medium
  model_list_med <- unique(geobike[frame_size_std_m == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_med)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] & frame_size_letters == "M", frame_size_std_m := TRUE]
  }

  model_list_med <- unique(geobike[frame_size_std_m == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_med)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] &
              frame_size_numbers >= 53.5 &
              frame_size_numbers <= 54.5, frame_size_std_m := TRUE]
    
  }
  geobike[model == "Binary Groler (short) 2025" & frame_size_numbers == 53.5, frame_size_std_m := NA]

  # grab bigger
  model_list_med <- unique(geobike[frame_size_std_m == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_med)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] &
              frame_size_numbers >= 53 &
              frame_size_numbers <= 54.9, frame_size_std_m := TRUE]
    
  }
  model_list_med <- unique(geobike[frame_size_std_m == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_med)
  nrow(geobike[frame_size_std_m == TRUE, ])
  temp <- geobike[frame_size_std_m == TRUE, .(N = .N), by = model]
#  temp[N > 1] |> View()

# do small
  model_list_small <- unique(geobike[frame_size_std_s == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_small)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] & frame_size_letters == "S", frame_size_std_s := TRUE]
  }

  model_list_small <- unique(geobike[frame_size_std_s == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_small)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] &
              frame_size_numbers >= 51.5 &
              frame_size_numbers <= 52.5, frame_size_std_s := TRUE]
    
  }
  # grab bigger
  model_list_small <- unique(geobike[frame_size_std_s == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_small)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] &
              frame_size_numbers >= 50 &
              frame_size_numbers <= 52.9, frame_size_std_s := TRUE]
    
  }
  model_list_small <- unique(geobike[frame_size_std_s == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_small)
  nrow(geobike[frame_size_std_s == TRUE, ])
  temp <- geobike[frame_size_std_s == TRUE, .(N = .N), by = model]
#  temp[N > 1] |> View()

  # do large
  model_list_lg <- unique(geobike[frame_size_std_l == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_lg)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] & frame_size_letters == "M", frame_size_std_l := TRUE]
  }

  model_list_lg <- unique(geobike[frame_size_std_l == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_lg)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] &
              frame_size_numbers >= 55.5 &
              frame_size_numbers <= 56.5, frame_size_std_l := TRUE]
    
  }
  #grab 57
  model_list_lg <- unique(geobike[frame_size_std_l == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_lg)
  for(i in 1:length(model_list_diff)){
    geobike[model == model_list_diff[i] &
              frame_size_numbers >= 55 &
              frame_size_numbers <= 56.9, frame_size_std_l := TRUE]
    
  }
  model_list_lg <- unique(geobike[frame_size_std_l == TRUE, model])
  model_list_diff <- setdiff(model_list_all, model_list_lg)
  nrow(geobike[frame_size_std_l == TRUE, ])
  temp <- geobike[frame_size_std_l == TRUE, .(N = .N), by = model]
#  temp[N > 1] |> View()

  # total models
  # length(unique(geobike$model))
  # nrow(geobike[frame_size_std_s == TRUE, ])
  # nrow(geobike[frame_size_std_m == TRUE, ])
  # nrow(geobike[frame_size_std_l == TRUE, ])
  # 

  return(geobike)
}
```


```{r}
better_assign_std_size <- function(geobike){
  # see "bike size classes.xlsx" and computations on "gravel_scatter.qmd"
  rider_size <- c(153, 159, 163, 167, 171, 175, 179, 183, 187, 191, 196)
  frame_size_char <- c("XXS", "XS", "XSS", "S", "SM", "M", "ML", "L", "LXL", "XL", "XXL")
  frame_size_num_lo <- c(40, 48.5, 49.5, 51, 52.5, 53.5, 54.5, 55.75, 57.25, 59, 60.75)
frame_size_num_hi <- c(48.5, 49.5, 51, 52.5, 53.5, 54.5, 55.75, 57.25, 59, 60.75, 68)


# first do bikes with rider height data
  for(i in 1:nrow(geobike)){
    rider_min <- geobike[i, rider_min]
    rider_max <- geobike[i, rider_max]
    if(!is.na(rider_min)){
      for(j in 1:length(rider_size)){
        if(rider_size[j] > rider_min & rider_size[j] <= rider_max){
          geobike[i, frame_size_std_fine := rider_size[j]]
        }
      }
    }else{
      geobike[i, frame_size_std_fine := NA]
    }
  }

# then do frame_size_char
for(i in 1:nrow(geobike)){
  if(is.na(geobike[i, frame_size_std_fine]) & !is.na(geobike[i, frame_size_letters])){
    if(geobike[i, frame_size_letters] == "XXXL"){
      j <- length(rider_size)
    }else{
      j <- which(frame_size_char == geobike[i, frame_size_letters])
    }
    geobike[i, frame_size_std_fine := rider_size[j]]
  }
}
# then do frame_size_num
for(i in 1:nrow(geobike)){
  if(is.na(geobike[i, frame_size_std_fine]) & !is.na(geobike[i, frame_size_numbers])){
    j <- which(frame_size_num_lo <= geobike[i, frame_size_numbers] &
                 frame_size_num_hi > geobike[i, frame_size_numbers])
    geobike[i, frame_size_std_fine := rider_size[j]]
  }
}

# geobike[, .SD, .SDcols = c("model", "frame_size_std", "frame_size_orig", "frame_size_letters", "frame_size_numbers")] |> View()

return(geobike)
}
```

```{r forest-boost-size-predictor}
set.seed(123)

# --- Median imputer (fit on TRAIN, apply to any data.table) ---
median_imputer <- function(DT, cols = NULL) {
  stopifnot(data.table::is.data.table(DT))
  if (is.null(cols)) cols <- names(DT)[vapply(DT, is.numeric, TRUE)]
  # medians computed on TRAIN only
  meds <- DT[, lapply(.SD, function(x) {
    m <- suppressWarnings(stats::median(x, na.rm = TRUE))
    if (is.infinite(m)) NA_real_ else m
  }), .SDcols = cols]
  setnames(meds, cols)

  impute <- function(DT2) {
    stopifnot(data.table::is.data.table(DT2))
    for (j in cols) {
      m <- meds[[j]]
      if (!is.na(m)) DT2[is.na(get(j)), (j) := m]
    }
    DT2
  }
  list(impute = impute, medians = meds)
}

# --- Z-score scaler (fit on TRAIN, apply to any data.table) ---
scaler_fit <- function(DT, cols = NULL) {
  stopifnot(data.table::is.data.table(DT))
  if (is.null(cols)) cols <- names(DT)[vapply(DT, is.numeric, TRUE)]
  mu  <- DT[, lapply(.SD, function(x) mean(x, na.rm = TRUE)), .SDcols = cols]
  sdv <- DT[, lapply(.SD, function(x) stats::sd(x, na.rm = TRUE)), .SDcols = cols]
  setnames(mu,  cols)
  setnames(sdv, cols)

  transform <- function(DT2) {
    stopifnot(data.table::is.data.table(DT2))
    for (j in cols) {
      s <- sdv[[j]]; if (is.na(s) || s == 0) s <- 1
      DT2[, (j) := (get(j) - mu[[j]]) / s]
    }
    DT2
  }
  list(transform = transform, mean = mu, sd = sdv)
}

prepare_new_frames <- function(frames_dt, x_cols, imp, sc) {
  stopifnot(data.table::is.data.table(frames_dt))
  DT <- data.table::copy(frames_dt)

  # Ensure all expected columns exist (add NA if missing)
  missing_cols <- setdiff(x_cols, names(DT))
  if (length(missing_cols)) DT[, (missing_cols) := NA_real_]

  # Keep only predictors (and any ID cols you want to carry through)
  keep_cols <- intersect(x_cols, names(DT))
  stopifnot(length(keep_cols) > 0)

  # Apply the TRAIN-fitted imputer & scaler
  DT <- imp$impute(DT)
  DT <- sc$transform(DT)

  # Return both the processed table and the numeric matrix for models
  list(
    DT_processed = DT,
    X = as.matrix(DT[, ..keep_cols])
  )
}

predict_height_unscaled <- function(model, frames_dt, x_cols, imp, sc, ys = NULL) {
  # prepare new frames like training
  DT <- copy(frames_dt)
  missing <- setdiff(x_cols, names(DT))
  if (length(missing)) DT[, (missing) := NA_real_]

  DT  <- imp$impute(DT)
  DT  <- sc$transform(DT)
  X   <- as.matrix(DT[, ..x_cols])

  p <- as.numeric(predict(model, X))  # replace with the right predict(...) for your model

  if (!is.null(ys)) p <- ys$inverse(p)  # only if model was trained on scaled y
  p
}

# dt: your full dataset
# Columns: rider_height, stack, reach, hta, sta, chainstay, front_center, bb_drop, wb, ht_len, st_len, etc.

frame_size_predictor <- function(geobike){
  
  set.seed(123)

  # process categorical variable
  geobike[, handlebar_dummy := ifelse(handlebar == "drop bar", 0, 
                                      ifelse(handlebar == "both", 0.5, 1))]
  geobike[, steerer_length := head_tube_length + axle_crown]

  y_col <- c("rider_height")
  x_cols <- c("stack", "reach", "head_tube_angle", "seat_tube_angle", "chainstay_length", "front_center",
              "head_tube_length",
              "axle_crown",
              # "steerer_length",
"top_tube_effective_length")
  cat_cols <- "handlebar_dummy"
  
 # x_cols <- c(x_cols, cat_cols)
  dt <- geobike[!is.na(rider_height), .SD, .SDcols = c(y_col, x_cols)]

  # Split first
  idx   <- sample(seq_len(nrow(dt)), 0.8*nrow(dt))
  train <- dt[idx]
  test <- dt[-idx]
  
  # Fit imputer/scaler on TRAIN predictors only
  imp <- median_imputer(train, x_cols)
  sc  <- scaler_fit(train, x_cols)
  
  # Apply to both sets (predictors only)
  train <- imp$impute(copy(train))
  test  <- imp$impute(copy(test))
  train <- sc$transform(train)
  test  <- sc$transform(test)
  
  # Build matrices for X; y stays on original scale
  x_tr <- as.matrix(train[, ..x_cols])
  y_tr <- train[[y_col]]          # UNscaled outcome
  x_te <- as.matrix(test[, ..x_cols])
  y_te <- test[[y_col]]
  
  summary(train[[y_col]])
  sd(train[[y_col]], na.rm = TRUE)
  
  # regularized linear regression
  cv_fit <- cv.glmnet(x_tr, y_tr, alpha = 0.5, nfolds = 10)
  y_pred <- predict(cv_fit, newx = x_te, s = "lambda.min")[, "lambda.min"]
  rmse_glm <- sqrt(mean((y_te - y_pred)^2))
  r2_glm   <- cor(y_te, y_pred)^2
  list(model="glmnet", RMSE=rmse_glm, R2=r2_glm)
  
  # random forest
  rf_fit <- ranger(rider_height ~ ., data = train[, c(y_col, x_cols), with=FALSE],
                   num.trees = 1000, mtry = floor(sqrt(length(x_cols))),
                   importance = "impurity")
  y_pred <- predict(rf_fit, data=test)$predictions
  rmse_rf <- sqrt(mean((y_te - y_pred)^2))
  r2_rf   <- cor(y_te, y_pred)^2
  list(model="ranger", RMSE=rmse_rf, R2=r2_rf)
  
  # xgboost
  K <- length(x_cols)
  mono <- rep(0, K)
  mono[which(x_cols %in% c("stack","reach","wheelbase"))] <- 1
  mono[which(x_cols %in% c("bb_drop"))] <- -1  # lower BB = smaller frames roughly
  
  dtrain <- xgb.DMatrix(x_tr, label=y_tr)
  dtest  <- xgb.DMatrix(x_te, label=y_te)
  
  xgb_fit <- xgb.train(
    params=list(
      objective="reg:squarederror", eta=0.1, max_depth=6,
      subsample=0.9, colsample_bytree=0.9,
      monotone_constraints=paste0("(", paste(mono, collapse=","), ")")
    ),
    data=dtrain, nrounds=500, early_stopping_rounds=30,
    watchlist=list(train=dtrain, val=dtest), verbose=0
  )
  
  y_pred <- predict(xgb_fit, dtest)
  rmse_xgb <- sqrt(mean((y_te - y_pred)^2))
  r2_xgb   <- cor(y_te, y_pred)^2
  list(model="xgboost", RMSE=rmse_xgb, R2=r2_xgb)
  
  results <- rbindlist(list(
    data.table(model="glmnet", RMSE=rmse_glm, R2=r2_glm),
    data.table(model="ranger", RMSE=rmse_rf, R2=r2_rf),
    data.table(model="xgb",    RMSE=rmse_xgb, R2=r2_xgb)
  ))
  results[order(RMSE)]
  
  # predict from models
  
  prep <- prepare_new_frames(geobike, x_cols, imp, sc)
  Xnew <- prep$X
  DTp  <- prep$DT_processed
  
  dnew    <- xgb.DMatrix(Xnew)
  pred_xg <- as.numeric(predict(xgb_fit, dnew))
  geobike[, rider_height_pred := pred_xg]

  return(geobike)
  
}

# geobike[model == "Trek Checkmate 2025", .SD, .SDcols = c("frame_size", "rider_height", "rider_height_pred_xgb")]
# geobike[model == "Sklar SuperSomething 2025", .SD, .SDcols = c("frame_size", "rider_height", "rider_height_pred_xgb")]
# geobike[model == "Santa Cruz Stigmata CC 2025", .SD, .SDcols = c("frame_size", "rider_height", "rider_height_pred_xgb")]
# geobike[model == "Fairlight Holt 2.0 2025", .SD, .SDcols = c("frame_size", "rider_height", "rider_height_pred_xgb")]
# geobike[model == "Breezer Radar X 2025", .SD, .SDcols = c("frame_size", "rider_height", "rider_height_pred_xgb")]
# ggplot(data = geobike,
#        aes(x = rider_height_pred,
#            y = rider_height,
#            color = handlebar)) +
#   geom_point()
# 
# 
# geobike[, rider_height_residual := rider_height_pred - rider_height]
# test_geobike <- geobike[, .SD, .SDcols = c("model_size", "rider_height_residual", "rider_height", "rider_height_pred")]
# setorder(test_geobike, rider_height_residual)
# test_geobike[, abs_resid := abs(rider_height_residual)]
# View(test_geobike[!is.na(rider_height_residual)])
# a <- "Breezer Radar X 2025"
# a <- "Ventum GS1 2025"
# bike_i <- geobike[model == "Breezer Radar X 2025", .SD, .SDcols = c("model", "frame_size", "rider_min", "rider_max", "rider_height", "rider_height_pred")]
# setorder(bike_i, rider_height)
# bike_i[, dev_low := rider_min - rider_height]
# bike_i[, dev_hi := rider_max - rider_height]
# bike_i
```

```{r}
rider_range <- function(geobike){
  models <- unique(geobike[, model])
  for(i in 1:length(models)){
    sizes <- geobike[model == models[i], frame_size]
    p <- length(sizes)
    if(p > 1){
      rider_height <- geobike[model == models[i], rider_height_pred]
      rider_height <- c(rider_height[1] - (rider_height[2] - rider_height[1]),
                        rider_height,
                        rider_height[p] + (rider_height[p] - rider_height[p-1]))
      q <- length(rider_height)
      mids <- (rider_height[2:q] + rider_height[1:(q-1)])/2
      geobike[model == models[i], rider_min_pred := mids[1:p]]
      geobike[model == models[i], rider_max_pred := mids[2:(p+1)]]
      geobike[model == models[i], rider_min_inch := rider_min_pred/2.54]
      geobike[model == models[i], rider_max_inch := rider_max_pred/2.54]
      geobike[model == models[i] & !is.na(rider_min), 
              specified_rider_height := 
                paste0(round(rider_min, 0), "cm - ", round(rider_max, 0), "cm")]
      geobike[model == models[i] & is.na(rider_min), 
              specified_rider_height := NA]
      geobike[model == models[i], 
              estimated_rider_height := 
                paste0(round(rider_min_pred, 0), "cm - ", round(rider_max_pred, 0), "cm")]
    }
  }
  
  # stooge dirt tracker
  geobike[model == "Stooge Dirt Tracker 2025", rider_min_pred := 
            rider_height_pred - (187.96-170.18)/2]
  geobike[model == "Stooge Dirt Tracker 2025", rider_max_pred := 
            rider_height_pred + (187.96-170.18)/2]
  return(geobike)
}
```


# Import bikes

```{r}
import_bikes_excel_single <- function(style_folder = "gravel", exchange_rates){
  # bike_list_file = paste0(paste0(style_folder, "/"), style_folder, "_list.txt")
  # bike_list_path <- here(data_folder, bike_list_file)
  # bike_list <- fread(bike_list_path, sep = "\t", header = FALSE)
  
  filelist_path <- here(data_folder,style_folder)
  bike_list <- list.files(filelist_path, pattern = "\\.xlsx$", full.names = FALSE)
  bike_list <- bike_list[!grepl("^~\\$", basename(bike_list))] # delete excel hidden

  # exchange_rates
  euro_2_usd <- exchange_rates$eur
  gbp_2_usd <- exchange_rates$gbp
  dkk_2_usd <- exchange_rates$dkk

  geobike <- data.table(NULL)
  for(i in 1:length(bike_list)){
    bike_file = bike_list[i]
    print(bike_file)
    bike_path <- here(data_folder, style_folder, bike_file)
    model_data <- read_excel(bike_path, range = "A1:B6", col_names = FALSE,
                          .name_repair = "unique_quiet") |>
      data.table()

    # geometry range
    geom_range <- read_excel(bike_path, range = "B7:B7", col_names = FALSE,
                          .name_repair = "unique_quiet") |> as.character()
    last_row <- substr(geom_range, (nchar(geom_range)-1), nchar(geom_range)) |>
      as.integer()
    
    # specs table
    first_row <- last_row + 2
    last_row <- first_row + 100
    specs_range <- paste0("a", first_row, ":b", last_row)
    
    bike_specs <- read_excel(bike_path, range = specs_range, col_names = TRUE) |>
      clean_names() |>
      data.table()
    bike_specs <- bike_specs[!apply(is.na(bike_specs), 1, all), ]
    bike_specs_t <- transpose(bike_specs, make.names = 1)

    bike_label <- paste(model_data[1, 2], model_data[2, 2], model_data[3, 2])
    bike_geo <- read_geometry(bike_label = bike_label,
                        bike_range = geom_range,
                        data_file = paste0(style_folder,"/", bike_file))
    bike_i <- cbind(bike_geo, bike_specs_t )
    if(!"location" %in% names(bike_i)){
      bike_i[, location := NA]
    }
    bike_i <- clean_and_compute(bike_i)
    # bike_i <- read_bike(bike_label = bike_label,
    #                     bike_range = geom_range,
    #                     data_file = paste0(style_folder,"/", bike_file),
    #                     material = frame_material)
    bike_i[, url := model_data[5,2]]
    bike_i[, image_url := model_data[6,2]]
    bike_i[, my_fit := NA]
    
    # price data
    bike_i[, base_build := as.numeric(base_build)]
    bike_i[, frameset := as.numeric(frameset)]
    
    bike_i[, frameset_usd := frameset]
    bike_i[, base_build_usd := base_build]
    currency <- bike_i[1, currency]
    if(!is.na(currency) & (currency == "euro" | currency == "EUR")){
      bike_i[!is.na(frameset), frameset_usd := eur_2_usd * frameset]
      bike_i[!is.na(base_build), base_build_usd := eur_2_usd * base_build]
    }
    if(!is.na(currency) & (currency == "pound" | currency == "GBP")){
      bike_i[!is.na(frameset), frameset_usd := gbp_2_usd * frameset]
      bike_i[!is.na(base_build), base_build_usd := gbp_2_usd * base_build]
   }
    if(!is.na(currency) & (currency == "dkk" | currency == "DKK")){
      bike_i[!is.na(frameset), frameset_usd := dkk_2_usd * frameset]
      bike_i[!is.na(base_build), base_build_usd := dkk_2_usd * base_build]
   }
    if(!is.na(currency) & (currency == "cad" | currency == "CAD")){
      bike_i[!is.na(frameset), frameset_usd := cad_2_usd * frameset]
      bike_i[!is.na(base_build), base_build_usd := cad_2_usd * base_build]
   }
    
    # Stuff for filters
    
    # suspension class
    # 30 mm travel
    # Rudy: 425 - 0.05*30 = 423.5
    # Fox TC: 425 - 0.2*30 = 419
    # Cane Creek = Fox TC
    # Lauf 419 mm AC, 47mm rake
    # 40 mm travel
    # Rudy: 435 - 0.05*40 = 433
    # Fox TC: 435 - 0.2*40 = 427
    # Cane Creek = Fox TC
    # 50 mm travel
    # Fox: 445 - .2*50 = 435
    # 60 mm travel
    # MRP Baxter: 456 - .2*60 = 444
    # Rockshox 60 mm on trek
    min_0 <- 411 # 30 mm
    min_1 <- 415 # 30 mm
    min_2 <- 423 # (419 + 427)/2 # 40 mm
    min_3 <- 431 # (427 + 435)/2 # 50 mm
    min_4 <- 439.5 # (435 + 444)/2 # 60 mm
    min_5 <- 460 # 
    bike_i[fork == "rigid" & axle_crown < min_0, fork_class := "0 mm"]
    bike_i[fork == "rigid" & axle_crown >= min_0 & axle_crown < min_1, fork_class := "20 mm"]
    bike_i[fork == "rigid" & axle_crown >= min_1 & axle_crown < min_2, fork_class := "30 mm"]
    bike_i[fork == "rigid" & axle_crown >= min_2 & axle_crown < min_3, fork_class := "40 mm"]
    bike_i[fork == "rigid" & axle_crown >= min_3 & axle_crown < min_4, fork_class := "50 mm"]
    bike_i[fork == "rigid" & axle_crown >= min_4 & axle_crown < min_5, fork_class := "60 mm"]
    bike_i[fork == "rigid" & axle_crown >= 471 & axle_crown < 489, fork_class := "100 mm"]
    bike_i[fork == "rigid" & axle_crown >= 489 & axle_crown < 507, fork_class := "120 mm"]
    bike_i[fork == "suspension", fork_class := paste(suspension_corrected, "mm")]
    # make a factor and order
    fork_classes <- c("0 mm", "20 mm", "30 mm", "40 mm", "50 mm", "60 mm", "100 mm", "120 mm")
    bike_i[, fork_class := factor(fork_class, levels = fork_classes)]
    
    # bind it
    geobike <- rbind(geobike, bike_i)
  }
 return(geobike)
}
```

```{r import-bike-list, echo=FALSE}
import_bike_list <- function(style = "gravel", exchange_rates){
  
  geobike <- rbind(
    import_bikes_excel_single("gravel", exchange_rates),
    import_bikes_excel_single("gravel incomplete", exchange_rates)
  )
  geobike[, id := .I]

  
  # add column of shape id for plots
  shape_list <- c(15,17,19,0,2)
  n_shapes <- length(shape_list)
  n_models <- length(unique(geobike[, model]))
  n_recycles <- floor(n_models/n_shapes)
  left_over <- n_models - n_recycles*n_shapes
  model_2_shape_map <- c(rep(shape_list, n_recycles), shape_list[1:left_over])
  geobike[, shape_id := model_2_shape_map[as.integer(as.factor(model))]]
  

  # center X at bottom bracket
  geobike[, rear_x := rear_x - bottom_x]
  geobike[, seat_x := seat_x - bottom_x]
  geobike[, head_x := head_x - bottom_x]
  geobike[, crown_x := crown_x - bottom_x]
  geobike[, front_x := front_x - bottom_x]
  geobike[, bottom_x := bottom_x - bottom_x]
  geobike[, seattube_x := seattube_x - bottom_x]
 
  setorder(geobike, "model")
  
  # get rider_height
  geobike <- frame_size_predictor(geobike)
  setorder(geobike, model, rider_height_pred)
  geobike <- rider_range(geobike)
  
  geobike_working <- copy(geobike)
  # geobike <- geobike_working
  
  # get classifier size medium
  geobike <- assign_std_size_pred(geobike)
#  geobike <- better_assign_std_size(geobike)

  # set my_fit or classifier fit
  geobike[, my_fit := frame_size_std_m] 
  
  # set bike class
  geobike[, terrain_class := "Rigid Gravel"]
  geobike[axle_crown >= 473 &
            handlebar == "flat bar" &
            (tire_width_max_700c >= 2.1*25.4 |
            tire_width_max_650b >= 2.1*25.4),
          terrain_class := "MTB"]
  geobike[axle_crown >= 473 &
            (handlebar == "drop bar" |
            handlebar == "both") &
            (tire_width_max_700c >= 2.1*25.4 |
            tire_width_max_650b >= 2.1*25.4),
          terrain_class := "Drop Bar MTB"]
  geobike[axle_crown < 473 &
            handlebar == "flat bar" &
            (tire_width_max_700c >= 2.1*25.4 |
            tire_width_max_650b >= 2.1*25.4),
          terrain_class := "Flat Bar ATB"]
  geobike[axle_crown < 473 &
            (handlebar == "drop bar" |
            handlebar == "both") &
            (tire_width_max_700c >= 2.1*25.4 |
            tire_width_max_650b >= 2.1*25.4),
          terrain_class := "Drop Bar ATB"]
  geobike[axle_crown >= 417.5 &
            (tire_width_max_700c < 2.1*25.4 &
            tire_width_max_650b < 2.1*25.4),
          terrain_class := "Suspension Gravel"]
  class_levels <- c("Rigid Gravel", 
                    "Suspension Gravel",
                    "Drop Bar ATB", 
                    "Flat Bar ATB",
                    "Drop Bar MTB",
                    "MTB"
                    )
  geobike[, terrain_class := factor(terrain_class,
                                    levels = class_levels)]

#  geobike[terrain_class == "Drop Bar MTB", model] |> unique()
  geobike[, material := factor(material,
                                    levels = c("carbon", "aluminum", "steel", "titanium"))]
  
  # add model-frame_size column
  geobike[, model_size := paste(model, frame_size)]
  setorder(geobike, model)
  geobike[, model_size := factor(model_size,
                                 levels = unique(model_size))]
  
  # create my_fit alternative
  geobike[, Size := ifelse(my_fit == TRUE, "M/L (54-56)", "All sizes")] # was focal/non-focal

  return(geobike)
}
```

```{r}
classifier_scores <- function(dt, means){
  # create scores 
  # Get variables for each centroid
  V <- A_classifier_cols
  # example for A/B split
  W <- B_classifier_cols  # example for B1/B2 split
  data_scaled_A <- cbind(data_scaled[, .SD, .SDcols = c("model", "frame_size", "kmeans_cut_1")],
                         Y1)
  data_scaled_B <- cbind(data_scaled[, .SD, .SDcols = c("model", "frame_size", "kmeans_cut_2")],
                         Y3)
  # Compute centroids
  centroid_A <- colMeans(data_scaled_A[kmeans_cut_1 == 1, ..V]) |> t()
  centroid_B1 <- colMeans(data_scaled_B[kmeans_cut_2 == 1, ..W]) |> t()
  centroid_B2 <- colMeans(data_scaled_B[kmeans_cut_2 == 2, ..W]) |> t()
  
  # Compute distances (Euclidean)
  n <- nrow(data_scaled_A)
  k <- nrow(centroid_A)
  pA <- length(V)
  pB <- length(W)
  distances <- as.matrix(dist(rbind(centroid_A, data_scaled_A[, ..V])))
  dist_to_A <- distances[(k+1):(k+n), 1:k]/sqrt(pA)
  distances <- as.matrix(dist(rbind(centroid_B1, data_scaled_B[, ..W])))
  dist_to_B1 <- distances[(k+1):(k+n), 1:k]/sqrt(pB)
  distances <- as.matrix(dist(rbind(centroid_B2, data_scaled_B[, ..W])))
  dist_to_B2 <- distances[(k+1):(k+n), 1:k]/sqrt(pB)
  
  # Convert to similarity scores
  sim_A <- 1 / (dist_to_A + 1e-6)
  sim_B1 <- 1 / (dist_to_B1 + 1e-6)
  sim_B2 <- 1 / (dist_to_B2 + 1e-6)
  total <- sim_A + sim_B1 + sim_B2
  
  data_scaled <- data_scaled[, .SD, .SDcols = c("model", "frame_size", "kmeans_style")]
  data_scaled[, kmeans_racy_score := sim_A/total]
  data_scaled[, kmeans_relaxed_score := sim_B1/total]
  data_scaled[, kmeans_rowdy_score := sim_B2/total]
  
}
```

```{r get_centroids}
get_centroids <- function(Y, cluster){
  centroids <- rowsum(Y, group = cluster) / as.vector(table(cluster))
  return(centroids)
}
```


```{r d_scores}
d_scores <- function(Y, class_dt, cluster_col = "init_cluster", prefix = "kmeans"){
  # projections onto axis through cluster centroid. Y is the matrix of data
  # and must be centered at the origin. The results are exactly the same as
  # r_scores, which computes the axes from the correlations between cluster and variable.
  k <- max(class_dt$init_cluster)
  centroids <- get_centroids(Y, class_dt[, get(cluster_col)]) # axis is row, measure is col
  E_raw <- centroids |> t()
  E <- apply(E_raw, 2, FUN = function(x) x/sqrt(sum(x^2)))
  # E <- matrix(
  #   c(centroids[1,]/sqrt(sum(centroids[1,]^2)),
  #     centroids[2,]/sqrt(sum(centroids[2,]^2)),
  #     centroids[3,]/sqrt(sum(centroids[3,]^2))),
  #   ncol = 3
  # )

  
  # apply(E, 2, function(x) sum(x^2)) check!
  # sum(axis1^2) # check!
  # t(E) %*% E # check!
  scores <- Y %*% E # projections
  loadings <- cor(Y, scores) # this is precisely the loadings using r_scores

  scores_scaled <- apply(scores, 2, function(x) (x - min(x))/(max(x) - min(x))) * 100
  colnames(scores_scaled) <- paste("clust", 1:k)
  # apply(scores_scaled, 2, min) # check!
  # apply(scores_scaled, 2, max) # check!

  # assign style to axes
  style_levels <- c("racy", "relaxed", "rowdy", "allroad")[1:k]
  relaxed <- which.max(loadings[rownames(loadings) == "rear_center"])
#  relaxed <- class_dt[model == "Tumbleweed Stargazer 2025", init_cluster]
  colnames(scores_scaled)[relaxed] <- "relaxed"
  rowdy <- which.max(loadings[rownames(loadings) == "front_center"])
#  rowdy <- class_dt[model == "Specialized Chisel 2022", init_cluster]
  colnames(scores_scaled)[rowdy] <- "rowdy"
  racy <- which.max(loadings[rownames(loadings) == "head_tube_angle"])
#  racy <- class_dt[model == "Cervelo Aspero 2024", init_cluster]
  colnames(scores_scaled)[racy] <- "racy"
  if(k==4){
    allroad <- setdiff(1:4, c(racy, relaxed, rowdy))
    colnames(scores_scaled)[allroad] <- "allroad"
  }
    scores_scaled <- data.table(scores_scaled)
  
  class_dt[get(cluster_col) == racy, style := "racy"]
  class_dt[get(cluster_col) == relaxed, style := "relaxed"]
  class_dt[get(cluster_col) == rowdy, style := "rowdy"]
  if(k==4){
    class_dt[get(cluster_col) == allroad, style := "allroad"]
  }
  
  scores_out <- data.table(
    class_dt[, .SD, .SDcols = c("model", "frame_size", "style")],
    scores_scaled[, .SD, .SDcols = style_levels]
  )
  scores_out[, style := factor(style, style_levels)]
  
  old_labels <- c("style", style_levels)
  setnames(scores_out,
          old = old_labels,
          new = paste0(prefix, "_", old_labels))
  
  
  return(scores_out)
}
```

```{r r_scores}
r_scores <- function(Y, class_dt, cluster_col = "cluster"){
  dummy <- data.table(
    clust1 = ifelse(class_dt[, get(cluster_col)] == 1, 1, 0),
    clust2 = ifelse(class_dt[, get(cluster_col)] == 2, 1, 0),
    clust3 = ifelse(class_dt[, get(cluster_col)] == 3, 1, 0)
  ) |>
    as.matrix()
    
  # style vector
  E_raw <- cor(dummy, Y) |>
    t()
  EtE <- diag(3)
  diag(EtE) <- 1/sqrt(diag(t(E_raw) %*% E_raw))
  E <- E_raw %*% EtE
  # t(E) %*% E # check!
  scores <- Y %*% E # projections
  loadings <- cor(Y, scores)
  # cor(dummy, scores) # better
  
  # assign style to axes
  style_levels <- c("racy", "relaxed", "rowdy")
  relaxed <- which.max(loadings[rownames(loadings) == "rear_center"])
  colnames(scores)[relaxed] <- "relaxed"
  rowdy <- which.max(loadings[rownames(loadings) == "reach"])
  colnames(scores)[rowdy] <- "rowdy"
  racy <- which.max(loadings[rownames(loadings) == "head_tube_angle"])
  colnames(scores)[racy] <- "racy"

  scores_scaled <- apply(scores, 2, function(x) (x - min(x))/(max(x) - min(x))) * 100
  # apply(scores_scaled, 2, min) # check!
  # apply(scores_scaled, 2, max) # check!
  colnames(scores_scaled) <- colnames(scores)
  scores_scaled <- data.table(scores_scaled)

  scores_out <- data.table(
    class_dt[, .SD, .SDcols = c("model", "frame_size")],
    scores_scaled[, .SD, .SDcols = style_levels]
  )
  
  return(scores_scaled)
}
```

```{r mclust_classifier}
mclust_classifier <- function(dt,
                              k = 3,
                              classifier_cols = c(
                                "stack",
                                "reach",
                                "front_center",
                                "rear_center",
                                "head_tube_angle",
                                "seat_tube_angle",
                                "trail_45"
                                )
                              ){
  # dt should be my_fit
  # dt <- geobike_import[my_fit == TRUE,]
  data_info <- dt[, .SD,
                         .SDcols = c("model", "frame_size")]
  model <- data_info[, model]
  Y <- dt[my_fit == TRUE, .SD, .SDcols = classifier_cols] |>
    scale()
  row.names(Y) <- model

  mclust_result <- Mclust(Y, G = k)

  mclust_class <- data.table(
    data_info,
    init_cluster = mclust_result$classification
  )
  
  mclust_scores <- d_scores(Y, mclust_class,
                            cluster_col = "init_cluster",
                            prefix = "mclust")
  return(mclust_scores)
}
```

```{r kmeans-classifier}
kmeans_classifier <- function(dt,
                              k = 3,
                              method = "rkm",
                              classifier_cols = c(
                                "stack",
                                "reach",
                                "front_center",
                                "rear_center",
                                "head_tube_angle",
                                "seat_tube_angle",
                                "trail_45"
                              ),
                              nested = FALSE
                              ){
  # dt should be my_fit
  dt_info <- dt[, .SD,.SDcols = c("model", "frame_size")]
  model <- dt_info[, model]
  Y <- dt[my_fit == TRUE, .SD, .SDcols = classifier_cols] |>
    scale()
  row.names(Y) <- model

  kmeans_result <- kmeans(Y, centers = k)
  okm_result <- okm(Y, centers = k) # overlapping kmeans
  rkm_result <- ktaucenters(Y, k)
  explore_table <- data.table(
    dt_info,
    km_cluster = kmeans_result$cluster,
    rkm_cluster = rkm_result$cluster
  )


  kmeans_class <- data.table(
    dt_info,
    init_cluster = kmeans_result$cluster)
  if(method == "rkm"){
    kmeans_class[, init_cluster := rkm_result$cluster]
  }

  # scores
  kmeans_scores <- d_scores(Y,
                            kmeans_class,
                            cluster_col = "init_cluster",
                            prefix = "kmeans")
  
  # multidimensional scaling
  # these are scores but I'm using the d-scores below
  # Step 2: Classical MDS (k=2 for 2D plot)
  D <- dist(Y, method = "euclidean")
  mds_coords <- cmdscale(D, k = 2) # two dimensions for three groups
  # kmeans_scores[, c("mds1", "mds2") := mds_coords[, 1:2]]
  kmeans_scores[, mds1 := mds_coords[, 1]]
  kmeans_scores[, mds2 := mds_coords[, 2]]

  if(nested == TRUE){
  # dt should be my_fit
    reclassifier_cols <- c("stack_reach", "chainstay_length")
    subset_rows <- which(kmeans_scores$kmeans_style == "relaxed")
    dt_sub <- dt[subset_rows]
    dt_info <- dt_sub[, .SD,.SDcols = c("model", "frame_size")]
    model <- dt_info[, model]
    Y <- dt_sub[, .SD, .SDcols = reclassifier_cols] |>
      scale()
    row.names(Y) <- model
    
    kmeans_result <- kmeans(Y, centers = 2)
    rkm_result <- ktaucenters(Y, 2)
    explore_table <- data.table(
      dt_info,
      km_cluster = kmeans_result$cluster,
      rkm_cluster = rkm_result$cluster
    )
    # cor(cbind(explore_table$km_cluster, explore_table$rkm_cluster, Y))
    relaxed <- explore_table[model == "Tumbleweed Stargazer Gen 2 2025", rkm_cluster]
    explore_table[, kmeans_restyle := ifelse(rkm_cluster == relaxed, "relaxed", "rowdy")]
    old_scores <- kmeans_scores
    kmeans_scores[kmeans_style == "rowdy", kmeans_style := "xtra rowdy"]
    kmeans_scores <- merge(old_scores, 
                            explore_table[, .SD, .SDcol = c("model", "frame_size", "kmeans_restyle")], 
                            by = c("model", "frame_size"),
                            all.x = TRUE)
    kmeans_scores[kmeans_style == "relaxed", kmeans_style := kmeans_restyle]
  }
  
  # make kmeans_scores = mds scores
  min1 <- min(kmeans_scores$mds1)
  max1 <- max(kmeans_scores$mds1)
  min2 <- min(kmeans_scores$mds2)
  max2 <- max(kmeans_scores$mds2)
  range1 <- max1 - min1
  range2 <- max2 - min2
  kmeans_scores[, kmeans_racy := 1-(mds1 - min1)/range1]
  kmeans_scores[, kmeans_rowdy := (mds1 - min1)/range1]
  kmeans_scores[, kmeans_relaxed := (mds2 - min2)/range2]
  
  return(kmeans_scores)

}
```

```{r kmeans-classifier-4}
kmeans_classifier_4 <- function(dt,
                              k = 3,
                              classifier_cols = c(
                                "stack",
                                "reach",
                                "front_center",
                                "rear_center",
                                "head_tube_angle",
                                "seat_tube_angle",
                                "trail_45"
                              )){
  # dt should be my_fit
  dt_info <- dt[, .SD,.SDcols = c("model", "frame_size")]
  model <- dt_info[, model]
  Y <- dt[my_fit == TRUE, .SD, .SDcols = classifier_cols] |>
    scale()
  row.names(Y) <- model

  kmeans_result <- kmeans(Y, centers = k)
  okm_result <- okm(Y, centers = k) # overlapping kmeans
  rkm_result <- ktaucenters(Y, k)
  explore_table <- data.table(
    dt_info,
    km_cluster = kmeans_result$cluster,
    rkm_cluster = rkm_result$cluster
  )

  kmeans_class <- data.table(
    dt_info,
    init_cluster = rkm_result$cluster
  )
  
  # scores
  kmeans_scores <- d_scores(Y, kmeans_class,
                            cluster_col = "init_cluster",
                            prefix = "kmeans")
  kmeans_scores[is.na(kmeans_style), kmeans_style := "group_4"]
  
    # multidimensional scaling
  # these are scores but I'm using the d-scores below
  # Step 2: Classical MDS (k=2 for 2D plot)
  D <- dist(Y, method = "euclidean")
  mds_coords <- cmdscale(D, k = 3) # two dimensions for three groups
  # kmeans_scores[, c("mds1", "mds2") := mds_coords[, 1:2]]
  kmeans_scores[, mds1 := mds_coords[, 1]]
  kmeans_scores[, mds2 := mds_coords[, 2]]
  kmeans_scores[, mds3 := mds_coords[, 3]]
  
  gg1 <- ggplot(data = kmeans_scores,
               aes(x = mds1, y = mds2, color = kmeans_style)) +
    geom_point()
  gg2 <- ggplot(data = kmeans_scores,
               aes(x = mds1, y = mds3, color = kmeans_style)) +
    geom_point()
  gg3 <- ggplot(data = kmeans_scores,
               aes(x = mds2, y = mds3, color = kmeans_style)) +
    geom_point()
  plot_grid(gg1, gg2, gg3)
  cor(c(kmeans_scores[,mds3]), Y)
  kmeans_scores[mds3 < -1 & (kmeans_style == "racy" | kmeans_style == "relaxed"), model]
  kmeans_scores[mds3 > 1 & (kmeans_style == "racy" | kmeans_style == "relaxed"), model]

  return(kmeans_scores)
  

}
```

```{r nested-kmeans-classifier}
nested_km_classifier <- function(dt){
  
  A_cols = c(
    "stack",
    "reach",
    "front_center",
    "rear_center",
    "head_tube_angle",
    "seat_tube_angle",
    "trail_45"
  )
  B_cols = c("stack_reach", "seat_tube_angle")
  
  # First find A and B groups
  # dt should be my_fit
  dt_info <- dt[, .SD,
                         .SDcols = c("model", "frame_size")]
  model <- dt_info[, model]
  Y <- dt[my_fit == TRUE, .SD, .SDcols = A_cols] |>
    scale()
  row.names(Y) <- model

  kmeans_result <- kmeans(Y, centers = 2)

  kmeans_class <- data.table(
    dt_info,
    cut1 = kmeans_result$cluster
  )
  # which class is santa cruz stigmata?
  rowdy_class <- kmeans_class[model == "Santa Cruz Stigmata CC 2023", cut1]
  if(rowdy_class == 1){
    # switch cluster id
    kmeans_class[, cut1 := ifelse(cut1 == 1, 2, 1)]
    rowdy_class <- 2
  }
  
  dt_info <- dt[kmeans_class[, cut1] == rowdy_class, .SD, .SDcols = c("model", "frame_size")]
  model <- dt_info[, model]
  
  Y2 <- dt[kmeans_class[, cut1] == rowdy_class, .SD, .SDcols = B_cols] |>
    scale()
  row.names(Y2) <- model

  kmeans_result <- kmeans(Y2, centers = 2)
  kmeans_class_B <- data.table(
    dt_info,
    cut2 = kmeans_result$cluster
  )
  rowdy_class <- kmeans_class_B[model == "Santa Cruz Stigmata CC 2023", cut2]
  if(rowdy_class == 1){
    # switch cluster id
    kmeans_class_B[, cut2 := ifelse(cut2 == 1, 2, 1)]
    rowdy_class <- 2
  }
  kmeans_class_B[, cut2 := cut2+1]
  kmeans_class <- merge(kmeans_class, kmeans_class_B, by = c("model", "frame_size"), all.x = TRUE)
  kmeans_class[, init_cluster := ifelse(cut1 == 1, 1, cut2)]

  kmeans_scores <- d_scores(Y, kmeans_class,
                            cluster_col = "init_cluster",
                            prefix = "nkmeans")
  return(kmeans_scores)

}
```

```{r kmeans-explore}
kmeans_classifier_explore <- function(dt){

  A_classifier_cols <- c(
      "stack",
      "reach",
      "front_center",
      "rear_center",
      "head_tube_angle",
      "seat_tube_angle",
      "trail_45"
  )
  dt_subset <- dt[my_fit == TRUE, .SD,
                         .SDcols = c("model", "frame_size", A_classifier_cols)]
  dt_info <- dt[my_fit == TRUE, .SD,
                         .SDcols = c("model", "frame_size")]
  model <- dt_subset[, model]
  Y1 <- dt_subset[, .SD, .SDcols = A_classifier_cols] |>
    scale()
  row.names(Y1) <- model
  dt_scaled_1 <- cbind(dt_info, Y1)
  
  # get kmeans
  kmeans_result_1 <- kmeans(Y1, centers = 2)
  dt_scaled_1[, kmeans_cut_1 := kmeans_result_1$cluster]
  # which class is santa cruz stigmata?
  rowdy_class <- dt_scaled[model == "Santa Cruz Stigmata CC 2023", kmeans_cut_1]
  if(rowdy_class == 1){
    # switch cluster id
    dt_scaled_1[, kmeans_cut_1 := ifelse(kmeans_cut_1 == 1, 2, 1)]
    rowdy_class <- 2
  }
  dt_subset <- dt_scaled_1[, .SD, .SDcols = c("model", "frame_size", "kmeans_cut_1")]
  dt <- merge(dt, dt_subset, by = c("model", "frame_size"), all.x = TRUE)

  B_classifier_cols <- c(
    "stack_reach",
    "rear_center"
  )
  racy_class <- 1
  dt_subset <- dt[my_fit == TRUE & kmeans_cut_1 == rowdy_class, .SD,
                         .SDcols = c("model", "frame_size", B_classifier_cols)]
  dt_info <- dt[my_fit == TRUE & kmeans_cut_1 == rowdy_class, .SD,
                         .SDcols = c("model", "frame_size")]
  model <- dt_subset[, model]
  Y2 <- dt_subset[, .SD, .SDcols = B_classifier_cols] |>
    scale()
  row.names(Y2) <- model
  dt_scaled_2 <- cbind(dt_info, Y2)
  kmeans_result_2 <- kmeans(Y2, centers = 2)
  dt_scaled_2[, kmeans_cut_2 := kmeans_result_2$cluster]
  if(dt_scaled_2[model == "Santa Cruz Stigmata CC 2023", kmeans_cut_2] == 1){
    # cluster 1 to cluster 2
    dt_scaled_2[, kmeans_cut_2 := ifelse(kmeans_cut_2 == 1, 2, 1)]
  }
  dt_scaled <- merge(dt_scaled_1, dt_scaled_2, by = c("model", "frame_size"), all.x = TRUE)
  dt_scaled[, kmeans_clust := ifelse(kmeans_cut_1 == racy_class, kmeans_cut_1, kmeans_cut_2 + 1)]
  style_levels <- c("Racy", "Relaxed", "Rowdy")
  dt_scaled[, kmeans_style := style_levels[kmeans_clust] |>
                  factor(levels = style_levels)]
  k_means_class_table <- merge(dt[, .SD, .SDcols = c("model", "frame_size")],
                               dt_scaled[, .SD, .SDcols = c("model", "kmeans_style")])
  
# get scaled values for B_classifier_cols for all bikes, centered and scaled by rows where kmeans_cut_1 = 2).
  dt_subset <- dt[my_fit == TRUE, .SD,
                         .SDcols = c(B_classifier_cols)]
  means <- attr(Y2, "scaled:center") |> t()
  sds <- attr(Y2, "scaled:scale") |> t()
  Y3 <- as.matrix(dt_subset) - matrix(means, nrow = nrow(dt_subset),
                                        ncol = length(means), byrow = TRUE)
  Y3 <- Y3/matrix(sds, nrow = nrow(dt_subset),
                                        ncol = length(sds), byrow = TRUE)
# create scores 
# Get variables for each centroid
V <- A_classifier_cols
      # example for A/B split
W <- B_classifier_cols  # example for B1/B2 split
dt_scaled_A <- cbind(dt_scaled[, .SD, .SDcols = c("model", "frame_size", "kmeans_cut_1")],
                       Y1)
dt_scaled_B <- cbind(dt_scaled[, .SD, .SDcols = c("model", "frame_size", "kmeans_cut_2")],
                       Y3)
# Compute centroids
centroid_A <- colMeans(dt_scaled_A[kmeans_cut_1 == 1, ..V]) |> t()
centroid_B1 <- colMeans(dt_scaled_B[kmeans_cut_2 == 1, ..W]) |> t()
centroid_B2 <- colMeans(dt_scaled_B[kmeans_cut_2 == 2, ..W]) |> t()

# Compute distances (Euclidean)
n <- nrow(dt_scaled_A)
k <- nrow(centroid_A)
pA <- length(V)
pB <- length(W)
distances <- as.matrix(dist(rbind(centroid_A, dt_scaled_A[, ..V])))
dist_to_A <- distances[(k+1):(k+n), 1:k]/sqrt(pA)
distances <- as.matrix(dist(rbind(centroid_B1, dt_scaled_B[, ..W])))
dist_to_B1 <- distances[(k+1):(k+n), 1:k]/sqrt(pB)
distances <- as.matrix(dist(rbind(centroid_B2, dt_scaled_B[, ..W])))
dist_to_B2 <- distances[(k+1):(k+n), 1:k]/sqrt(pB)

# Convert to similarity scores
sim_A <- 1 / (dist_to_A + 1e-6)
sim_B1 <- 1 / (dist_to_B1 + 1e-6)
sim_B2 <- 1 / (dist_to_B2 + 1e-6)
total <- sim_A + sim_B1 + sim_B2

dt_scaled <- dt_scaled[, .SD, .SDcols = c("model", "frame_size", "kmeans_style")]
dt_scaled[, kmeans_racy_score := sim_A/total]
dt_scaled[, kmeans_relaxed_score := sim_B1/total]
dt_scaled[, kmeans_rowdy_score := sim_B2/total]


return(k_means_class_table)
}
```

```{r}
jack_clust <- function(data, classifier_cols, two_deep = FALSE){
  
  #   kmeans k = 2, p.s = .84 cols = "stack", "reach", "front_center", "rear_center", "head_tube_angle", "seat_tube_angle", "trail_45",

  classifier_cols <- c(
      "stack",
      "reach",
      "front_center",
      "rear_center",
      "head_tube_angle",
      "seat_tube_angle",
      "trail_45",
      # # "trail",
      # # "axle_crown",
      # "tire_width_max",
      # "fork_offset_rake",
      # "bottom_bracket_drop",
      # "top_tube_angle",
      # "front_reach",
      # "front_rear",
      # "stack_reach",
      # "sta_hta",
      NULL)
  
  data <- geobike_import
  data_subset <- data[my_fit == TRUE, .SD,
                         .SDcols = c("model", "frame_size", classifier_cols)] |> na.omit()
  model <- data_subset[, model]

  Y <- data_subset[, .SD, .SDcols = classifier_cols] |>
    scale()
  row.names(Y) <- model
  prediction_strength <- prediction.strength(Y, Gmin=2, Gmax=5, M = 500,
                                             clustermethod = kmeansCBI)
  prediction_strength$mean.pred
  
  BIC <- mclustBIC(Y)
  plot(BIC)
  summary(BIC)

  mclust_result <- Mclust(Y, G = 3)
  mclust_scores <- data.table(
    model = model,
    class = mclust_result$classification
  )

  prediction_strength <- prediction.strength(Y, Gmin=2, Gmax=4, M = 50,
                                             clustermethod = hclustCBI,
                                             method = "ward.D2")
  prediction_strength$mean.pred
  
  kmeans_result <- kmeans(Y, centers = 2)
  data_subset[, kmeans_cut_1 := kmeans_result$cluster]
  data_subset <- data_subset[, .SD, .SDcols = c("model", "frame_size", "kmeans_cut_1")]
  data_out <- merge(data, data_subset, by = c("model", "frame_size"))

  # reclassify lev_1 = 2
    reclassifier_cols <- c(
      # "stack",
      # "reach",
      # "front_center",
      "rear_center",
      # "head_tube_angle",
      # "seat_tube_angle",
      # "trail_45",
      # "trail",
      # "axle_crown",
      # "tire_width_max",
      # "fork_offset_rake",
      # "bottom_bracket_drop",
      # "top_tube_angle",
      # "front_reach",
      # "front_rear",
      "stack_reach",
      NULL)

  stig_class <- data_subset[model == "Santa Cruz Stigmata CC 2023", kmeans_cut_1]

  data_subset2 <- data_out[my_fit == TRUE & kmeans_cut_1 == stig_class, .SD,
                         .SDcols = c("model", "frame_size", reclassifier_cols)] |> na.omit()
  model <- data_subset2[, model]
  Y2 <- data_subset2[, .SD, .SDcols = reclassifier_cols] |>
    scale()
  row.names(Y2) <- model
  prediction_strength <- prediction.strength(Y2, Gmin=2, Gmax=5, M = 500,
                                             clustermethod = kmeansCBI)
  prediction_strength$mean.pred
  
  
  prediction_strength <- prediction.strength(Y2, Gmin=2, Gmax=4, M = 50,
                                             clustermethod = hclustCBI,
                                             method = "ward.D2")
  prediction_strength$mean.pred

  kmeans_2 <- kmeans(Y2, centers = 2)
  data_subset2[, kmeans_cut_2 := kmeans_2$cluster]


  prediction_strength <- prediction.strength(Y2, Gmin=2, Gmax=4, M = 50,
                                             clustermethod = hclustCBI,
                                             method = "ward.D2")
  prediction_strength$mean.pred


  

  p <- ncol(Y)
  # single column deletes
  for(j in 1:p){
    Y_j <- Y[, -j]
    kmeans_result <- kmeans(Y_j, centers = 3)
    put_label <- paste0("v",j)
    kmeans_class[, (put_label) := kmeans_result$cluster]
  }
  
  if(two_deep == TRUE){
    # two column deletes
    for(j in 1:(p-1)){
      for(k in (j+1):p){
        Y_j <- Y[, -c(j,k)]
        kmeans_result <- kmeans(Y_j, centers = 3)
        put_label <- paste0("v",j,"_",k)
        kmeans_class[, (put_label) := kmeans_result$cluster]
      }
    }
  }
  
  kmeans_matrix <- kmeans_class[, 2:ncol(kmeans_class)]

  # convert each column to a pair of columns (not1 and not2)
  n <- nrow(kmeans_matrix)
  p <- ncol(kmeans_matrix)
  labels <- names(kmeans_matrix)
  l <- 0
  for(j in 1:p){
    l <- l+1
    get_label <- labels[j]
    put_label <- paste0("binary", l)
    kmeans_matrix[, (put_label) := ifelse(get(get_label)== 1, 0, 1)]
    l <- l+1
    put_label <- paste0("binary", l)
    kmeans_matrix[, (put_label) := ifelse(get(get_label)== 2, 0, 1)]
  }
  binary_cols <- paste0("binary", 1:l)
  cluster_data <- kmeans_matrix[, .SD, .SDcols = binary_cols] |>
    data.frame()
  row.names(cluster_data) <- model
  d_matrix <- dist(cluster_data, method = "binary")

  hclust_method = "complete"
  hc <- hclust(d_matrix, method = hclust_method)
  tree_v2_color <- dendro_data_k(hc, k = 3)

 
  

  

  
}
  
  
```


```{r tree-classifier, echo=FALSE}
tree_classifier <- function(
    dt,
    k = 3,
    classifier_cols = c(
      "stack",
      "reach",
      "front_center",
      "rear_center",
      "head_tube_angle",
      "seat_tube_angle",
      "trail_45"),
    method = "ward.D2",
    scores = FALSE
){
  
  # dt should be my_fit
  dt_info <- dt[, .SD,
                         .SDcols = c("model", "frame_size")]
  model <- dt_info[, model]
  Y <- dt[my_fit == TRUE, .SD, .SDcols = classifier_cols] |>
    scale()
  row.names(Y) <- model
  
  d_matrix <- dist(Y, method = "euclidean")
  tree_result <- hclust(d_matrix, method = method)
  k = 4
  labclust  <-  cutree(tree_result, k)

  tree_class <- data.table(
    dt_info,
    init_cluster = labclust
  )
  
  # tree_scores <- d_scores(Y, tree_class,
  #                           cluster_col = "init_cluster",
  #                           prefix = "tree")
  
  # save colored tree
  tree_v2_color <- dendro_data_k(tree_result, k)
  # use and save tree from all variables
  tree_path <- here("rds", "tree.Rds")
  saveRDS(tree_v2_color, tree_path)

  if(scores == TRUE){
    return(tree_scores)
  }else{
    return()
  }

}


```


```{r tree-classifier-old, echo=FALSE, eval=FALSE}
tree_classifier_old <- function(
    dt,
    k = 3,
    classifier_cols = c(
      "stack",
      "reach",
      "front_center",
      "rear_center",
      "head_tube_angle",
      "seat_tube_angle",
      "trail_45"),
    method = "ward.D2"
){
  
  # dt should be my_fit
  dt_info <- dt[, .SD,
                         .SDcols = c("model", "frame_size")]
  model <- dt_info[, model]
  Y <- dt[my_fit == TRUE, .SD, .SDcols = classifier_cols] |>
    scale()
  row.names(Y) <- model
  
  d_matrix <- dist(Y, method = "euclidean")
  tree_v2 <- hclust(d_matrix, method = method)
  tree_v2_color <- dendro_data_k(tree_v2, k = 3)
  

  style_class <- tree_v2_color$labels %>%
    data.table()
  style_class[, model := tstrsplit(label, ",", keep = 1)]
  
  cluster_labels <- numeric(3)
  rowdy <- "Santa Cruz Stigmata CC 2023"
  cluster_labels[style_class[model == rowdy, clust]] <- "Rowdy"
  racy <- "OPEN U.P. 2022"
  cluster_labels[style_class[model == racy, clust]] <- "Racy"
  cluster_labels[which(cluster_labels == 0)] <- "Relaxed"
  
  style_class[, restyle := cluster_labels[clust]]
  style_table <- merge(style_table, style_class[, .SD, .SDcols = c("model", "restyle")], by = "model",
                       all.x = TRUE)
  # relevel and make integer
  style_table[, restyle := factor(restyle,
                                  levels = style_levels)]


  # use and save tree from all variables
  tree_path <- here("rds", "tree.Rds")
  saveRDS(tree_v2_color, tree_path)
  
  
  return(style_table[, .SD, .SDcols = c("model", "restyle")])
}


```

```{r}
functional_classifier <- function(dt){
  # dt should be my_fit
  functional_class <- dt[my_fit == TRUE, .SD, .SDcols = c("model", "frame_size")]
  style_levels <- c("racy", "relaxed", "rowdy")
  
  # racy
  racy_cols <- c("stack_reach", "rear_center", "head_tube_angle", "trail_45")
  Y <- dt[my_fit == TRUE, .SD, .SDcols = racy_cols] |>
    as.matrix()
  # make more positive more racy
  Y[, "stack_reach"] <- -Y[, "stack_reach"] # low stack_reach = more racy
  Y[, "rear_center"] <- -Y[, "rear_center"] # short rear_center = more racy
  Y[, "trail_45"] <- -Y[, "trail_45"] # short trail = more racy
  Y <- scale(Y)
  row_sum <- apply(Y, 1, sum)
  # scale to 0-1 range
  # range set by actual score
  functional_class[, racy := 100 * (row_sum - min(row_sum))/diff(range(row_sum))]
  # range set by maximum possible score
  row_min <- min(Y[, 1]) + min(Y[, 2]) + min(Y[, 3]) + min(Y[, 4])
  row_max <- max(Y[, 1]) + max(Y[, 2]) + max(Y[, 3]) + max(Y[, 4])
  functional_class[, racy_xtrm := 100 * (row_sum - row_min)/(row_max - row_min)]
  
  # relaxed
  relaxed_cols <- c("stack_reach", "rear_center")
  Y <- dt[my_fit == TRUE, .SD, .SDcols = relaxed_cols] |>
    as.matrix()
  Y <- scale(Y)
  row_sum <- apply(Y, 1, sum)
  # scale to 0-1 range
  # range set by actual score
  functional_class[, relaxed := 100 * (row_sum - min(row_sum))/diff(range(row_sum))]
  # range set by maximum possible score
  row_min <- min(Y[, 1]) + min(Y[, 2]) 
  row_max <- max(Y[, 1]) + max(Y[, 2]) 
  functional_class[, relaxed_xtrm := (row_sum - row_min)/(row_max - row_min)]

  # rowdy
  rowdy_cols <- c("reach", "front_center", "head_tube_angle", "seat_tube_angle", "trail_45")
  Y <- dt[my_fit == TRUE, .SD, .SDcols = rowdy_cols] |>
    as.matrix()
  # make more positive more rowdy
  Y[, "head_tube_angle"] <- -Y[, "head_tube_angle"]
  Y <- scale(Y)
  row_sum <- apply(Y, 1, sum)
  # scale to 0-1 range
  # range set by actual score
  functional_class[, rowdy := 100* (row_sum - min(row_sum))/diff(range(row_sum))]
  # range set by maximum possible score
  row_min <- min(Y[, 1]) + min(Y[, 2]) + min(Y[, 3]) + min(Y[, 4])
  row_max <- max(Y[, 1]) + max(Y[, 2]) + max(Y[, 3]) + max(Y[, 4])
  functional_class[, rowdy_xtrm := (row_sum - row_min)/(row_max - row_min)]
  
  # cluster is max score
  score_matrix <- functional_class[, .SD,
                                    .SDcols =  style_levels]
  cluster <- apply(score_matrix, 1, which.max)
  functional_class[, style := style_levels[cluster]]
  
  # override max
#  functional_class[, style := NA]
  functional_class[rowdy > 50 & relaxed < 50, style := "rowdy"]
  functional_class[relaxed > 50 & rowdy < 50, style := "relaxed"]
#  functional_class[is.na(style), style := "racy"]
  
  functional_class[, style := factor(style, style_levels)]

  old_labels <- c("style", style_levels)
  new_labels <- paste0("functional_", old_labels)
  setnames(functional_class, old_labels, new_labels)
  
  functional_class <- functional_class[, .SD,
                                       .SDcols = c(
    "model", "frame_size", new_labels)]


  return(functional_class)
}
```

```{r gravel-scores, echo = FALSE}
gravel_scores <- function(data, y_cols){

  gravel_style <- data[, restyle]
  gravel_style_matrix <- data.table(
    racy = ifelse(gravel_style == "Racy", 1, 0),
    relaxed = ifelse(gravel_style == "Relaxed", 1, 0),
    rowdy = ifelse(gravel_style == "Rowdy", 1, 0)
  ) |>
    as.matrix()
    
  # are class labels correlated with PCA scores?
  Y <- data.table(
    scale(data[, .SD, .SDcols = y_cols])) |>
    as.matrix()
  R <- cor(Y)
  decomp <- eigen(R)
  E <- decomp$vectors
  scores <- Y %*% E
  # cor(gravel_style_matrix, scores[, 1:4]) # not good
  
  # style vector
  E_raw <- cor(gravel_style_matrix, Y) |>
    t()
  EtE <- diag(3)
  diag(EtE) <- 1/sqrt(diag(t(E_raw) %*% E_raw))
  E <- E_raw %*% EtE
  # t(E) %*% E # check!
  scores <- Y %*% E
  # cor(gravel_style_matrix, scores) # better

  
  scores_0 <- apply(scores, 2, function(x) x - min(x))
  scores_1 <- apply(scores_0, 1, function(x) x/sum(x)) |>
    t()
  # apply(scores_1, 1, sum) # check!

  data[, racy := scores_1[, 1] * 100]
  data[, relaxed := scores_1[, 2] * 100]
  data[, rowdy := scores_1[, 3] * 100]
  return(data)
}

```


```{r import-gravel, eval=TRUE}
import_it <-  TRUE # make false when creating .R file below!

   classifier_cols <- c(
      "stack",
      "reach",
      "front_center",
      "rear_center",
      "head_tube_angle",
      "seat_tube_angle",
      "trail_45"
  )   
  
equalize_tire_width = TRUE
geobike_path <- here("rds", "geobike.Rds")
geobike_sus_path <- here("rds", "geobike_sus.Rds")
my_fit_path <- here("rds", "my_fit.Rds")
if(import_it != TRUE){
  geobike <- readRDS(geobike_path)
  geobike_sus <- readRDS(geobike_sus_path)
  my_fit <- readRDS(my_fit_path)
}else{
  
  # exchange_rates
  get_exchange_rates <- FALSE
  if(get_exchange_rates == TRUE){
    eur_2_usd <- convert_currencies(1, "EUR", "USD")
    gbp_2_usd <- convert_currencies(1, "GBP", "USD")
    dkk_2_usd <- convert_currencies(1, "DKK", "USD")
    cad_2_usd <- convert_currencies(1, "CAD", "USD")
  }else{
    eur_2_usd <- 1.152452 # 31 Oct 2025
    gbp_2_usd <- 1.310659 # 31 Oct 2025
    dkk_2_usd <- 0.154319 # 31 Oct 2025
    cad_2_usd <- 0.7132362 # 31 Oct 2025
  }
  exchange_rates <- list(eur = eur_2_usd, gbp = gbp_2_usd, dkk = dkk_2_usd)

  # import from xlsx
  geobike <- import_bike_list(style = "gravel", exchange_rates)
  geobike_import <- copy(geobike)
  # geobike <- geobike_import
  
  
  # classify bikes by kmeans
  # kmeans first splits into k = 2 groups because there is only good support for 2. Then splits
  # group 2 into two groups because there is good support for this.
  # then combines into 3 clusters
  # classify bikes
  k <- 3
  style_levels <- c("racy", "relaxed", "rowdy", "allroad")[1:k]
  
  # kmeans
  kmeans_classes <- kmeans_classifier(
    geobike[my_fit == TRUE],
    k = k,
    method = "rkm", # km or rkm where rkm is robust
    nested = TRUE
  )
  geobike <- merge(geobike,
                   kmeans_classes[, .SD, .SDcols = c("model", "kmeans_style")],
                   by = c("model"), all.x = TRUE)
  geobike <- merge(geobike,
                   kmeans_classes[, .SD,
                                  .SDcols = c("model", "frame_size",
                                              paste0("kmeans_", style_levels),
                                              "mds1", "mds2")],
                   by = c("model", "frame_size"), all.x = TRUE)

  # nested kmeans
  # nkmeans_classes <- nested_km_classifier(
  #   geobike[my_fit == TRUE]
  # )
  # geobike <- merge(geobike,
  #                  nkmeans_classes[, .SD, .SDcols = c("model", "nkmeans_style")],
  #                  by = c("model"), all.x = TRUE)
  # geobike <- merge(geobike,
  #                  nkmeans_classes[, .SD, .SDcols = c("model", "frame_size", paste0("nkmeans_", style_levels))],
  #                  by = c("model", "frame_size"), all.x = TRUE)

  # # mclust
  # mclust_classes <- mclust_classifier(geobike[my_fit == TRUE,])
  # geobike <- merge(geobike,
  #                  mclust_classes[, .SD, .SDcols = c("model", "mclust_style")],
  #                  by = c("model"), all.x = TRUE)
  # geobike <- merge(geobike,
  #                  mclust_classes[, .SD, .SDcols = c("model", "frame_size", paste0("mclust_", style_levels))],
  #                  by = c("model", "frame_size"), all.x = TRUE)
  # 

  # tree classifier
  tree_classes <- tree_classifier(
    geobike[my_fit == TRUE],
    k = 3,
    method = "ward.D2",
    scores = FALSE
  )
  # tree_classes[is.na(tree_style), tree_style := "rowdy"]
  # geobike <- merge(geobike,
  #                  tree_classes[, .SD, .SDcols = c("model", "tree_style")],
  #                  by = c("model"), all.x = TRUE)
  # geobike <- merge(geobike,
  #                  tree_classes[, .SD, .SDcols = c("model", "frame_size", paste0("tree_", style_levels))],
  #                  by = c("model", "frame_size"), all.x = TRUE)

  # functional class
  # functional_classes <- functional_classifier(
  #   geobike[my_fit == TRUE]
  # )
  # geobike <- merge(geobike,
  #                  functional_classes[, .SD, .SDcols = c("model", "functional_style")],
  #                  by = c("model"), all.x = TRUE)
  # geobike <- merge(geobike,
  #                  functional_classes[, .SD, .SDcols = c("model", "frame_size", paste0("functional_", style_levels[1:3]))],
  #                  by = c("model", "frame_size"), all.x = TRUE)
  
  geobike[, color_kmeans := pal_okabe_ito_4[as.integer(kmeans_style)]]
#  geobike[, color_tree := pal_okabe_ito_3[as.integer(tree_style)]]
#  geobike[, color_function := pal_okabe_ito_3[as.integer(functional_style)]]
  geobike[, color := color_kmeans]
  geobike[, highlight_text := model_size]

  # my_fit
  my_fit <- geobike[my_fit == TRUE]

  # save
  saveRDS(geobike, geobike_path)
  saveRDS(my_fit, my_fit_path)
  
  # compute and save sus geometry
  geobike_sus <- stack_sus_columns(geobike)
  saveRDS(geobike_sus, geobike_sus_path)
  
  # make images for index page
  
}

```

# Modify Excel files

```{r eval=FALSE}
convert_multi_files <- function(){

  spec_data_labels <- c(
    "material",
    "udh",
    "dropout",
    "tire_width_max_700c",
    "tire_width_max_650b",
    "suspension_corrected",
    "fork_suspension",
    "stem_suspension",
    "rear_suspension",
    "rear_axle",
    "front_axle",
    "bottom_bracket",
    "q_factor",
    "seatpost_diameter",
    "front_derailleur",
    "max_chainring_1x",
    "max_chainring_2x",
    "rotor_max_front",
    "rotor_max_rear",
    "iso_astm",
    "routing_shifter",
    "routing_dropper",
    "routing_dynamo",
    "internal_storage",
    "mounts_inner",
    "mounts_under",
    "mounts_top",
    "mounts_fork",
    "mounts_fender",
    "mounts_rack_front",
    "mounts_rack_rear",
    "frameset",
    "base_build",
    "custom_builds",
    "currency"
)
  bike_path <- here(data_folder,"gravel orig excel file/gravel.xlsx")
  bike_list_file = "gravel orig excel file/gravel_list.txt"
  bike_list_path <- here(data_folder, bike_list_file)
  bike_list <- fread(bike_list_path, sep = "\t", header = TRUE)
  colnames(bike_list)[1] <- "model_year"
  
  bike_list[, brand_model := substr(model_year, 1, (nchar(model_year)-4))]
  bike_list[, year := substr(model_year, (nchar(model_year)-3), nchar(model_year))]
  bike_list[, first_row := substr(data_range, 2, 2) |> as.integer()]

  for(i in 1:nrow(bike_list)){

    bike_file <- paste0(bike_list[i, model_year], ".xlsx")
    bike_model_i <- data.table(
      spec = c("brand", "model", "model_year", "input_date", "url"),
      val = as.character(NA)
    )
    
    sheet_i <- bike_list[i, model_year]
    temp_split <- str_split(bike_list[i, brand_model], " ", n = 2)
    bike_model_i[1, val := temp_split[[1]][1]]
    bike_model_i[2, val := temp_split[[1]][2]]
    bike_model_i[3, val := bike_list[i, year]]
    
    range_i <- bike_list[i, data_range]
    first_row <- substr(range_i, 2, 2) |> as.integer()
    
    # if sheet has no model data
    if(first_row == 1){
      bike_model_i[4, val := bike_list[i, year]]
    }
    if(first_row == 6){
      input_date_i <- read_excel(bike_path,
                                sheet = sheet_i,
                                range = "B3", col_names = FALSE)
      colnames(input_date_i) <- c("input_date")
      input_date_str <- format(input_date_i$`input_date`, "%d-%b-%Y")
      
      url_i <- read_excel(bike_path,
                                sheet = sheet_i,
                                range = "B4", col_names = FALSE)
      
      bike_model_i[4, val := input_date_str]
      bike_model_i[5, val := url_i]
    }
    
    bike_specs_t <- data.table(
      spec_list = spec_data_labels,
      value = as.character(NA)
    )
    bike_specs_t[spec_list == "material", value := bike_list[i, frame]]
    

    # geometry
    bike_geo <- read_excel(bike_path,
                           sheet = sheet_i,
                           range = range_i, col_names = TRUE) |>
      data.table()
    colnames(bike_geo)[1:2] <- c("frame_size", "frame size")
    measures <- bike_geo[, frame_size]
    if(!"frame_weight" %in% measures){
      j <- which(measures == "wheel_size")
      if(length(j) == 2){
        # delete first wheel_size row
        bike_geo <- bike_geo[-j[1]]
        j <- j[2]
      }
      new_row <- data.table(
        colnames = colnames(bike_geo),
        frame_weight = as.numeric(NA)
      ) |>
        transpose(make.names = 1)
      new_row[, frame_size := "frame_weight"]
      bike_geo <- rbind(
        bike_geo[1:(j-1),],
        new_row,
        bike_geo[j:nrow(bike_geo)]
      )
    }
    data_range <- data.table(
      var = "data_range",
      range = paste0("a8:", letters[ncol(bike_geo)], (nrow(bike_geo) + 8))
    )


    # export
    bike_path_out <- here(data_folder, "gravel_temp_incomplete", bike_file)

    wb <- createWorkbook()
    addWorksheet(wb, "Sheet1") # Add a sheet if creating new
    modifyBaseFont(wb, fontSize = 14, fontName = "Futura")
    writeData(wb, sheet = "Sheet1", # model data
              x = bike_model_i,
              startRow = 1, startCol = 1,
              colNames = FALSE, rowNames = FALSE)
    writeData(wb, sheet = "Sheet1", # measured range
              x = data_range,
              startRow = 7, startCol = 1,
              colNames = FALSE, rowNames = FALSE)
    writeData(wb, sheet = "Sheet1", # geometry
              x = bike_geo,
              startRow = 8, startCol = 1,
              colNames = TRUE, rowNames = FALSE)
    writeData(wb, sheet = "Sheet1", # specs
              x = bike_specs_t,
              startRow = 10 + nrow(bike_geo), startCol = 1,
              colNames = TRUE, rowNames = FALSE)
    setColWidths(
      wb,
      sheet = "Sheet1",
      cols = 1:2,
      widths = 19
    )
    saveWorkbook(wb, bike_path_out, overwrite = TRUE)


  }
  
  

}
```

```{r eval=FALSE}
convert_single_files <- function(){
  input_spec_data_labels <- c(
    "material",
    "udh",
    "dropout",
    "tire_width_max_700c",
    "tire_width_max_650b",
    "suspension_corrected",
    "fork_suspension",
    "stem_suspension",
    "rear_suspension",
    "rear_axle",
    "front_axle",
    "q_factor",
    "seatpost_diameter",
    "routing_shifter",
    "routing_dropper",
    "routing_dynamo",
    "front_derailleur",
    "max_chainring_1x",
    "max_chainring_2x",
    "bottom_bracket",
    "mounts_inner",
    "mounts_under",
    "mounts_top",
    "mounts_fork",
    "mounts_fender",
    "mounts_fender_front",
    "mounts_rack_rear",
    "iso_astm",
    "rotor_max_front",
    "rotor_max_rear",
    "frameset",
    "base_build",
    "currency",
    "internal_storage"
)
  
    spec_data_labels <- c(
    "material",
    "udh",
    "dropout",
    "tire_width_max_700c",
    "tire_width_max_650b",
    "suspension_corrected",
    "fork_suspension",
    "stem_suspension",
    "rear_suspension",
    "rear_axle",
    "front_axle",
    "bottom_bracket",
    "q_factor",
    "seatpost_diameter",
    "front_derailleur",
    "max_chainring_1x",
    "max_chainring_2x",
    "rotor_max_front",
    "rotor_max_rear",
    "iso_astm",
    "routing_shifter",
    "routing_dropper",
    "routing_dynamo",
    "internal_storage",
    "mounts_inner",
    "mounts_under",
    "mounts_top",
    "mounts_fork",
    "mounts_fender",
    "mounts_rack_front",
    "mounts_rack_rear",
    "frameset",
    "base_build",
    "custom_builds",
    "currency"
)
  bike_list_file = "gravel old/gravel_list.txt"
  bike_list_path <- here(data_folder, bike_list_file)
  bike_list <- fread(bike_list_path, sep = "\t", header = FALSE)
  
  for(i in 1:nrow(bike_list)){
    
    bike_file = bike_list[i]
    bike_path <- here(data_folder, "gravel old", bike_file)
    bike_model_i <- read_excel(bike_path, range = "A1:B5", col_names = FALSE) |>
      data.table()
    # read date
    input_date_i <- read_excel(bike_path, range = "B4", col_names = FALSE)
    colnames(input_date_i) <- c("input_date")
    input_date_str <- format(input_date_i$`input_date`, "%d-%b-%Y")

    # specs table
    bike_specs <- read_excel(bike_path, range = "A6:AH7", col_names = TRUE) |>
      clean_names() |>
      data.table()
    colnames(bike_specs) <- input_spec_data_labels
    bike_specs$mounts_rack_front <- NA
    bike_specs$custom_builds <- NA
    bike_specs <- bike_specs[1, .SD, .SDcols = spec_data_labels]
    row.names(bike_specs) <- "value"
    bike_specs_t <- data.table(
      spec_list = colnames(bike_specs),
      value = bike_specs[1, .SD, .SDcols = spec_data_labels] |> as.character()
    )
    bike_specs_t[value == "NA", value := NA]

    # geometry
    bike_range_i <- read_excel(bike_path, range = "B9:B9", col_names = FALSE) |> as.character()
    bike_geo <- read_excel(bike_path, range = bike_range_i, col_names = TRUE) |>
      data.table()
    colnames(bike_geo)[1:2] <- c("frame_size", "frame size")
    measures <- bike_geo[, frame_size]
    if(!"frame_weight" %in% measures){
      a <- 3
    }
    
    data_range <- data.table(
      var = "data_range",
      range = paste0("a8:", letters[ncol(bike_geo)], (nrow(bike_geo) + 8))
    )

    # export
    bike_path_out <- here(data_folder, "gravel_temp", bike_file)

    wb <- createWorkbook()
    addWorksheet(wb, "Sheet1") # Add a sheet if creating new
    modifyBaseFont(wb, fontSize = 14, fontName = "Futura")
    writeData(wb, sheet = "Sheet1", # model data
              x = bike_model_i,
              startRow = 1, startCol = 1,
              colNames = FALSE, rowNames = FALSE) 
    writeData(wb, sheet = "Sheet1", # replace with formatted date
              x = input_date_str,
              startRow = 4, startCol = 2,
              colNames = FALSE, rowNames = FALSE) 
    writeData(wb, sheet = "Sheet1", # measured range
              x = data_range,
              startRow = 7, startCol = 1,
              colNames = FALSE, rowNames = FALSE) 
    writeData(wb, sheet = "Sheet1", # geometry
              x = bike_geo,
              startRow = 8, startCol = 1,
              colNames = TRUE, rowNames = FALSE) 
    writeData(wb, sheet = "Sheet1",
              x = bike_specs_t,
              startRow = 10 + nrow(bike_geo), startCol = 1,
              colNames = TRUE, rowNames = FALSE) 
    setColWidths(
      wb,
      sheet = "Sheet1",
      cols = 1:2,
      widths = 19
    )
    saveWorkbook(wb, bike_path_out, overwrite = TRUE)

  }
  
  

}
```




```{r add-bike-specs, eval=FALSE}
# this script adds 3 rows to specs and populates with style = gravel, handlebar = drop bar, fork = rigid

insert_after <- "spec_list"

filelist_path <- here("data/gravel incomplete")
excel_files <- list.files(filelist_path, pattern = "\\.xlsx$", full.names = TRUE)
for (file in excel_files) {
#  insert_row_num <- find_insert_row(file, named_range)
  data_range <- read_excel(file, range = "B7:B7", col_names = FALSE) |>
    as.character()
  last_row_data_block <- substr(data_range, 5, 6) |> as.integer()
  start_row_specs_block <- last_row_data_block + 2
  end_row_specs_block <- start_row_specs_block + 100
  specs_range <- paste0("A", start_row_specs_block,":A", end_row_specs_block)
  specs <- read_excel(file, range = specs_range, col_names = FALSE)
  insert_after_row <- which(specs == insert_after)
  
# Row to insert
  insert_row <- start_row_specs_block + insert_after_row  # +1 to insert 
  
# this script adds 3 rows to specs and populates with style = gravel, handlebar = drop bar, fork = rigid
  system(sprintf("osascript insert_row_with_values.scpt '%s' %d", file, insert_row))

}

```

# check colors
```{r eval=FALSE}
"#56B4E9" "#E69F00" "#009E73"
```

# check correlations

```{r eval=FALSE}

frontcenter_cols <- c("reach", "head_tube_angle", "fork_offset_rake") #
frontcenter_y <- my_fit[, .SD, .SDcols = frontcenter_cols] |>
  scale()
classifier_y <- my_fit[, .SD, .SDcols = classifier_cols] |>
  scale() |>
  data.table()
classifier_y[, fc_proxy := reach - head_tube_angle + fork_offset_rake]
cor(classifier_y)
```

# figure functions

```{r base-plot, echo = FALSE}
base_plot <- function(data = geobike,
                      x_col = "reach",
                      y_col = "stack",
                      legend_col = "model_size", # the column with values in the legend
                      color_col = "restyle", # the column of marker colors
                      x_label = "Reach", y_label = "Stack",
                      x_info = NULL, y_info = NULL,
                      digits = 0,
                      dot_palette = pal_okabe_ito_7,
                      dot_opacity = 0.3,
                      same_xy_scale = TRUE
                      ){
  if(is.null(x_info)){x_info <- x_label}
  if(is.null(y_info)){y_info <- y_label}
  show_trace_1_legend <- ifelse(color_col == legend_col, TRUE, FALSE)
  n_colors <- length(levels(data[, get(color_col)]))
  
  # set range of axes
  min_data_x <- min(data[, get(x_col)], na.rm = TRUE)
  min_data_y <- min(data[, get(y_col)], na.rm = TRUE)
  max_data_x <- max(data[, get(x_col)], na.rm = TRUE)
  max_data_y <- max(data[, get(y_col)], na.rm = TRUE)
  range_x <- max_data_x - min_data_x
  range_y <- max_data_y - min_data_y
  range_axis_x <- range_x * 1.1
  range_axis_y <- range_y * 1.1
  if(same_xy_scale == TRUE){
    if(range_x > range_y){
      range_axis_y <- range_axis_y * range_x/range_y
    }else{
      range_axis_x <- range_axis_x * range_y/range_x
    }}
  min_axis_x <- (min_data_x + max_data_x)/2 - 0.5*range_axis_x
  max_axis_x <- (min_data_x + max_data_x)/2 + 0.5*range_axis_x
  min_axis_y <- (min_data_y + max_data_y)/2 - 0.5*range_axis_y
  max_axis_y <- (min_data_y + max_data_y)/2 + 0.5*range_axis_y
 
  p <- plot_ly(data, evaluate=TRUE) %>%
  add_trace(type = "scatter", mode = "markers",
            x = ~get(x_col),
            y = ~get(y_col),
            color = ~get(color_col),
            colors = dot_palette[1:n_colors],
            opacity = dot_opacity,
            size = 10,
            name = ~get(color_col),
            hoverinfo = "text",
            text = ~paste(model, frame_size,
                          "<br>Cat:", restyle,
                          paste0("<br>", x_info, ":"),
                          round(get(x_col), digits),
                          paste0("<br>", y_info, ":"),
                          round(get(y_col), digits)),
            showlegend = show_trace_1_legend
  ) %>% 
    layout(xaxis = list(title = x_label,
                        tickfont = list(size = 16), titlefont = list(size = 16),
                        range = c(min_axis_x, max_axis_x)),
           yaxis = list(title = y_label,
                        tickfont = list(size = 16), titlefont = list(size = 16),
                        range = c(min_axis_y, max_axis_y)),
           title = list(text = paste(y_label, "vs.", x_label),
                        x = 0,
                        xanchor = "left"),
           legend = list(font = list(size = 10),
                         itemsizing = "constant"),
           autosize = F, width = 800, height = 600,
           NULL
    )
  
  if(legend_col != color_col){
  p <- p  %>%
    add_trace(
      type = "scatter",
      mode = "markers",
      x = ~get(x_col),
      y = ~get(y_col),
      marker = list( 
        size = 14,
        opacity = 1,
        color = ~color,
        colors = pal_okabe_ito_3
      ),
      text = ~paste("\U2B05", model, frame_size),
      textfont = list(size = 12),
      name = ~model_size,
      textposition = "right",
      visible = "legendonly",
      showlegend = TRUE
    )
  }
  
 
  return(p)
}

```


```{r annotate, echo = FALSE}
annotate_model <- function(p,
                           data = geobike,
                           x_col = "reach",
                           y_col = "stack",
                           g_col = "restyle",
                           text_col = "model",
                           text_target = "Giant Revolt X pro 1 long", # can be a vector
                           dx = 20,
                           dy = 20
                           ){
  subdata <- data[which(data[, get(text_col)] %in% text_target), ]
  p <- p %>%
    add_trace(data = subdata,
              x = ~get(x_col),
              y = ~get(y_col),
              color = ~get(g_col),
              type = "scatter",
              mode = "markers",
              marker = list(size = 16),
              showlegend = FALSE,
              NULL) %>%
    add_annotations(
      data = subdata,
      type = "text",
      x = ~get(x_col),
      y = ~get(y_col),
      xref = "x",
      yref = "y",
      ax = dx,
      ay = dy,
      showarrow = TRUE,
      text = ~paste(model, frame_size), 
      font = list(color = "black", size = 16))
  
  return(p) 
}
```

```{r base-ternary-plot, echo=FALSE}
base_ternary <- function(
    dt,
    axis_cols = c("racy","relaxed","rowdy"),
    axis_labels = c("Racy","Relaxed","Rowdy"),
    g_col = "restyle", # factor to determine color of plot points
    legend_color_col = "color", # column with color of legend
    round_to_place = 1,
    rescale = FALSE
){
  
  # a_dat <- dt[, get(axis_cols[1])]
  # b_dat <- dt[, get(axis_cols[2])]
  # c_dat <- dt[, get(axis_cols[3])]

  a_dat <- dt$origData()[, get(axis_cols[1])]
  b_dat <- dt$origData()[, get(axis_cols[2])]
  c_dat <- dt$origData()[, get(axis_cols[3])]
  if(rescale == TRUE){
    m <- matrix(c(a_dat, b_dat, c_dat), nrow = length(a_dat), ncol = 3) |>
      scale()
    mins <- apply(m, 2, min)
    m <- sweep(m, 2, mins, FUN = "-")
    maxs <- apply(m, 2, max)
    m <- sweep(m, 2, maxs, FUN = "/")
    # m[1:5,]
    a_dat <- m[, 1] * 100
    b_dat <- m[, 2] * 100
    c_dat <- m[, 3] * 100
  }

  axis_info <- function(title) {
    list(
      title = title,
      titlefont = list(
        size = 20
      ),
      tickfont = list(
        size = 15
      ),
      tickcolor = 'rgba(0,0,0,0)',
      ticklen = 5
    )
  }
  m <- list(
    l = 60,
    r = 60,
    b = 60,
    t = 60,
    pad = 4
  )
    a_col = axis_cols[1]
    b_col = axis_cols[2]
    c_col = axis_cols[3]

  fig <- dt %>% plot_ly()
  fig <- fig %>%
    add_trace(
      type = 'scatterternary',
      mode = 'markers',
      a = a_dat,
      b = b_dat,
      c = c_dat,
      color = ~get(g_col),
      colors = pal_okabe_ito_3,
      showlegend = FALSE,
      opacity = 0.5,
      marker = list( 
        size = 14,
        line = list('width' = 2)
      ),
      hoverinfo = "text",
      text = ~paste(model, frame_size,
                    "<br>Cat:", restyle,
                    paste("<br> ", axis_labels[1], ":", round(get(a_col), round_to_place)),
                    paste("<br> ", axis_labels[2], ":", round(get(b_col), round_to_place)),
                    paste("<br> ", axis_labels[3], ":", round(get(c_col), round_to_place))
      )
    )
  
  fig <- fig  %>%
    add_trace(
      type = 'scatterternary',
      mode = 'markers',
      a = a_dat,
      b = b_dat,
      c = c_dat,
      marker = list( 
        size = 14,
        opacity = 1,
        color = ~get(legend_color_col),
        colors = pal_okabe_ito_3
      ),
      text = ~paste(model, frame_size),
      textfont = list(size = 12),
      name = ~model,
      textposition = "right",
      visible = "legendonly",
      showlegend = TRUE
    )
  
  
  fig <- fig %>%
    layout(
      autosize = FALSE,
      margin = m,
      ternary = list(
        sum = 100,
        aaxis = axis_info(axis_labels[1]),
        baxis = axis_info(axis_labels[2]),
        caxis = axis_info(axis_labels[3])
      )
    )
  
  return(fig)  
}
```


```{r scatter-fig-global, echo=FALSE}
scatter_fig_global <- function(data = geobike,
                               x_col = "reach", y_col = "stack", g_col = "model_size",
                               x_label = "Reach", y_label = "Stack",
                               x_info = NULL, y_info = NULL,
                               xtra_info = NULL, # added to highlighted name
                               highlight_col = "model_size", # column for highlight info
                               digits = 0,
                               color_col = "kmeans_style",
                               dot_palette = pal_okabe_ito_7,
                               dot_opacity = 0.3,
                               same_xy_scale = TRUE,
                               set_autorange = TRUE,
                               add_regression = FALSE){ # if units are same on x and y then scales should be preserved
  
  # this version links all plots so that size can be filtered globally
  
  # y_cols <- c(x_col, y_col, g_col, "model_size", "restyle", "color", "Size")
  #subdata <- na.omit(data$origData()[, .SD, .SDcols = y_cols])
  
  #shared_data <- highlight_key(data, ~model)
  # bike_x <- highlight_key(subdata)
  
  # popup info box
  if(is.null(x_info)){x_info <- x_label}
  if(is.null(y_info)){y_info <- y_label}
  popup_text <- paste(data$origData()[, model_size],
                      "<br>Cat:", data$origData()[, get(color_col)],
                      paste0("<br>", x_info, ":"), round(data$origData()[, get(x_col)], digits),
                      paste0("<br>", y_info, ":"), round(data$origData()[, get(y_col)], digits))
  if(!is.null(xtra_info)){
    travel <- substr(data$origData()[, get(xtra_info)], 1, 2)
    offset <- substr(data$origData()[, get(xtra_info)], 3, 5)
    popup_text <- paste(popup_text,
                        paste0("<br>", "travel: ", travel, " mm"),
                        paste0("<br>", "offset: ", offset, " mm"))
  }
  
  # highlight info text
  if(highlight_col == "model_size"){
    highlight_text <- paste("\U2B05", data$origData()[, model_size])
  }else{
      travel <- substr(data$origData()[, get(xtra_info)], 1, 2)
      offset <- substr(data$origData()[, get(xtra_info)], 3, 5)
      highlight_text <- paste(paste0(travel, " travel; ",
                                     offset, " offset"))
  }
  

  
  n_colors <- length(levels(data$origData()[, get(color_col)]))
  
  # set range of axes
  min_data_x <- min(data$origData()[, get(x_col)], na.rm = TRUE)
  min_data_y <- min(data$origData()[, get(y_col)], na.rm = TRUE)
  max_data_x <- max(data$origData()[, get(x_col)], na.rm = TRUE)
  max_data_y <- max(data$origData()[, get(y_col)], na.rm = TRUE)
  range_x <- max_data_x - min_data_x
  range_y <- max_data_y - min_data_y
  range_axis_x <- range_x * 1.1
  range_axis_y <- range_y * 1.1
  if(same_xy_scale == TRUE){
    if(range_x > range_y){
      range_axis_y <- range_axis_y * range_x/range_y
    }else{
      range_axis_x <- range_axis_x * range_y/range_x
    }}
  min_axis_x <- (min_data_x + max_data_x)/2 - 0.5*range_axis_x
  max_axis_x <- (min_data_x + max_data_x)/2 + 0.5*range_axis_x
  min_axis_y <- (min_data_y + max_data_y)/2 - 0.5*range_axis_y
  max_axis_y <- (min_data_y + max_data_y)/2 + 0.5*range_axis_y
  
  
  fig <- data %>% plot_ly(width = 6.5*96, height = 4.5*96)
  # plot dots but no legend, because I don't want the legend to show/hide points
  fig <- fig %>%
    # add dots colored by get(color_col)
    add_trace(
      type = "scatter",
      mode = "markers",
      x = ~get(x_col),
      y = ~get(y_col),
      color = ~get(color_col),
      colors = dot_palette[1:n_colors],
      #      color = ~color, # this doesn't work for plot points
      opacity = dot_opacity,
      size = 10,
      showlegend = FALSE,
      marker = list( 
        size = 10,
        line = list('width' = 2)
      ),
      hoverinfo = "text",
      # text = popup_text,
      text = ~paste(model_size,
                    "<br>Cat:", get(color_col),
                    paste0("<br>", x_info, ":"), round(get(x_col), digits),
                    paste0("<br>", y_info, ":"), round(get(y_col), digits))
    )
  
  # superimpose dots colored by column "color" but using model_size as the legend item
  # plot legend, but no dots. Clicking on legend makes the dot appear. Since the dot is already there from above, only the text really appears
  fig <- fig  %>%
    add_trace(
      type = "scatter",
      mode = "markers",
      x = ~get(x_col),
      y = ~get(y_col),
      marker = list(
        size = 14,
        opacity = 1,
        # this doesn't work for the legend for some reason
        # color = ~get(color_col),
        # colors = dot_palette[1:n_colors]
        color = ~color # color is a column in the data with the hex code for the color
      ),
      # text = ~paste("\U2B05", model_size), # what pops up when legend item is clicked
      text = highlight_text, # what pops up when legend item is clicked
      # textfont = list(size = 12),
      name = ~get(g_col), # this is column for legend items
      textposition = "right",
      visible = "legendonly",
      showlegend = TRUE
    )
  
  fig <- fig |>
    layout(xaxis = list(title = x_label,
                        tickfont = list(size = 12), titlefont = list(size = 12)
    ),
    yaxis = list(title = y_label,
                 tickfont = list(size = 12), titlefont = list(size = 12)
    ),
    legend = list(font = list(size = 10),
                  itemsizing = "constant"),
    title = list(text = paste(y_label, "vs.", x_label),
                 x = 0.5,
                 xanchor = "center"),
    # autosize = F, width = 7*96, height = 5*96,
    NULL
    )


  if(set_autorange == TRUE){
    fig <- fig |>
      layout(xaxis = list(autorange = TRUE),
             yaxis = list(autorange = TRUE))
    
  }else{
    fig <- fig |>
      layout(xaxis = list(range = c(min_axis_x, max_axis_x)),
             yaxis = list(range = c(min_axis_y, max_axis_y)))
  }
  
  if(add_regression == TRUE){
    xy <- data.table(
      x = data$origData()[, get(x_col)],
      y = data$origData()[, get(y_col)],
      style = data$origData()[, get(color_col)]
    ) |>
      na.omit()
    
    fit <- lm(y ~ x, data = xy)
    r <- cor(xy$x, xy$y)
    
    # style means
    xy_means <- xy[, .(x = mean(x),
                       y = mean(y)),
                   by = .(style)]
    #     fit <- lm(y ~ x, data = xy_means)
    #     r <- cor(xy_means$x, xy_means$y)
    
    fig <- fig |>
      add_trace(
        type = "scatter",
        mode = "lines",
        x = xy$x,
        y = fitted(fit),
        alpha = 1,
        name = 'prediction',
        hoverinfo = "text",
        text = ~paste(
          "<br>Cor:", round(r, 2)),
        NULL
      )
  }
  
  
  return(fig)
}
```


```{r}
scatter_fig <- function(shared_data = geobike_shared,
                        link_group = "2dsus",
                        x_col = "reach", y_col = "stack", g_col = "model_size",
                        # this controls if the group label is shown with text
                        show_group_label = TRUE,
                        # these two arguments remove all rows except those with value filter_keep in the column filter_col. This is used in the sus geometry plot with stacked rows for each fork but in the first trace set I only want to plot the rigid fork.
                        filter_col = NULL, # 2nd filter column
                        filter_keep = NULL, # keep rows with these values
                        x_label = "Reach", y_label = "Stack",
                        x_info = NULL, y_info = NULL,
                        hover_info = NULL,
                        xtra_info = NULL, # added to highlighted name
                        highlight_col = "highlight_text", # column for highlight info
                        label_col = NULL,
                        digits = 0,
                        color_col = "kmeans_style",
                        dot_palette = pal_okabe_ito_7,
                        dot_opacity = 0.3,
                        same_xy_scale = FALSE,
                        set_autorange = TRUE,
                        add_regression = FALSE,
                        title = NULL){
  
  if(is.null(x_info)){x_info <- x_label}
  if(is.null(y_info)){y_info <- y_label}

  # Split by group
  groups <- unique(shared_data$origData()[, get(g_col)])
  

  # Create initial plot
  fig <- plot_ly()
  
  # Loop over groups to add two traces: one for points, one for labels
  for (grp in groups) {
    # Filter for group
    grp_data <- shared_data$data(withKey = FALSE) %>% filter(get(g_col) == grp)
    if(!is.null(filter_col)){
      grp_data <- grp_data[get(filter_col) == filter_keep, ]
    }
    grp_shared <- SharedData$new(grp_data, key = ~get(g_col), group = link_group)
    
    # set hover text
    if(is.null(hover_info)){
      grp_hovertext <- paste(grp_shared$origData()[, model_size],
                      "<br>Cat:", grp_shared$origData()[, get(color_col)],
                      paste0("<br>", x_info, ":"), round(grp_shared$origData()[, get(x_col)], digits),
                      paste0("<br>", y_info, ":"), round(grp_shared$origData()[, get(y_col)], digits))
    }else{
      if(hover_info == "filters"){
        grp_hovertext <- paste(grp_shared$origData()[, model_size],
                               "<br>Cat:", grp_shared$origData()[, get(color_col)],
                               paste0("<br>Material:"), grp_shared$origData()[, material],
                               paste0("<br>Handlebar:"), grp_shared$origData()[, handlebar],
                               paste0("<br>Spacing:"), grp_shared$origData()[, axle_spacing],
                               paste0("<br>UDH:"), grp_shared$origData()[, udh],
                               paste0("<br>Suspension Correction:"), grp_shared$origData()[, fork_class],
                               paste0("<br>Max 700c:"), grp_shared$origData()[, tire_width_max_700c],
                               paste0("<br>Max 650b:"), grp_shared$origData()[, tire_width_max_650b])
      }
    }
    
    # First trace: markers only, always visible
    fig <- fig |>
      add_trace(
        data = grp_shared,
        type = "scatter",
        mode = "markers",
        x = ~get(x_col),
        y = ~get(y_col),
        marker = list(size = 10, opacity = 0.2, color = ~color),
        hoverinfo = "text",
        hovertext = grp_hovertext,
        # hovertext = ~paste(model_size,
        #               "<br>Cat:", kmeans_style,
        #               paste0("<br>", x_info, ":"), round(get(x_col), digits),
        #               paste0("<br>", y_info, ":"), round(get(y_col), digits)),
        showlegend = FALSE
        # name = NULL
      )
  }
  
  # Loop over groups to add two traces: one for points, one for labels
  for (grp in groups) {
    # Filter for group
    grp_data <- shared_data$data(withKey = FALSE) %>% filter(get(g_col) == grp)
    grp_shared <- SharedData$new(grp_data, key = ~get(g_col), group = link_group)
    
    # set hover text
    if(is.null(hover_info)){
      grp_hovertext <- paste(grp_shared$origData()[, model_size],
                      "<br>Cat:", grp_shared$origData()[, get(color_col)],
                      paste0("<br>", x_info, ":"), round(grp_shared$origData()[, get(x_col)], digits),
                      paste0("<br>", y_info, ":"), round(grp_shared$origData()[, get(y_col)], digits))
    }else{
      if(hover_info == "filters"){
        grp_hovertext <- paste(grp_shared$origData()[, model_size],
                               "<br>Cat:", grp_shared$origData()[, get(color_col)],
                               paste0("<br>material:"), grp_shared$origData()[, material],
                               paste0("<br>max 700c:"), grp_shared$origData()[, tire_width_max_700c])
      }
    }
    
    if(link_group == "2dsus"){
      text_col <- label_col
      hover_text <- ~paste(model_size,
                           "<br>Cat:", kmeans_style,
                           paste0("<br>", x_info, ":"), round(get(x_col), digits),
                           paste0("<br>", y_info, ":"), round(get(y_col), digits),
                           paste0("<br>Fork:", get(highlight_col)))
    }else{
      text_col <- g_col
      hover_text <- grp_hovertext
      # hover_text <- ~paste(model_size,
      #                      "<br>Cat:", kmeans_style,
      #                      paste0("<br>", x_info, ":"), round(get(x_col), digits),
      #                      paste0("<br>", y_info, ":"), round(get(y_col), digits))
    }
    
    
    # Second trace: text only, initially hidden, toggled via legend
    fig <- fig |>
      add_trace(
        data = grp_shared,
        type = "scatter",
        mode = "markers+text",
        x = ~get(x_col),
        y = ~get(y_col),
        # hover text
        hoverinfo = "text",
        hovertext = hover_text,
        # highlight text
        text = ~get(text_col),
        textposition = "right",
        textfont = list(size = 12),
        marker = list(size = 12, opacity = 1, color = ~color),
        name = grp,  # Same legend label
        showlegend = TRUE,
        visible = "legendonly",
        legendgroup = grp
      )
  }
  
  if(is.null(title)){
    title <- paste(y_label, "vs.", x_label)
  }
  
  fig <- fig |>
    layout(xaxis = list(title = x_label,
                        tickfont = list(size = 12), titlefont = list(size = 12),
                        legend = list(
                          tracegroupgap = 0  # minimizes space between legend groups
                        )
    ),
    yaxis = list(title = y_label,
                 tickfont = list(size = 12), titlefont = list(size = 12)
    ),
    legend = list(font = list(size = 10),
                  itemsizing = "constant"),
    title = list(text = title,
                 x = 0.5,
                 xanchor = "center"),
    # autosize = F, width = 7*96, height = 5*96,
    NULL
    )
  
  if(add_regression == TRUE){
    xy <- data.table(
      x = shared_data$origData()[, get(x_col)],
      y = shared_data$origData()[, get(y_col)],
      style = shared_data$origData()[, get(color_col)]
    ) |>
      na.omit()
    
    fit <- lm(y ~ x, data = xy)
    r <- cor(xy$x, xy$y)
    
    # style means
    xy_means <- xy[, .(x = mean(x),
                       y = mean(y)),
                   by = .(style)]
    #     fit <- lm(y ~ x, data = xy_means)
    #     r <- cor(xy_means$x, xy_means$y)
    
    fig <- fig |>
      add_trace(
        type = "scatter",
        mode = "lines",
        x = xy$x,
        y = fitted(fit),
        alpha = 1,
        name = 'prediction',
        hoverinfo = "text",
        text = ~paste(
          "<br>Cor:", round(r, 2)),
        NULL
      )
  }
  
  
  return(fig)}
```

```{r}
t <- geobike[material == "aluminum" & frame_weight < 2000, .SD, .SD = c("model", "frame_size", "frame_weight")]
t |> knitr::kable(digits = c(0,0,0)) |> kableExtra::kable_styling()
```

```{r output-as-R-file}
# highlight and run to put update into R folder
write_it_as_R <- FALSE
if(write_it_as_R == TRUE){
  knitr::purl("bike_geometry_project.Rmd")
  file_name <- "bike_geometry_project.R"
  r_path <- here::here(file_name)
  file.rename(file_name, r_path)
}
```
